import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,dirname,basename} from 'node:path';import {once} from 'node:events';import WebSocket from 'ws';
test('future server defaults off; optional account login and guest WebSocket work when explicitly enabled',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'9lives-test-'));const start=async(enabled:boolean)=>{const child=spawn(process.execPath,['--import','tsx','server/index.ts'],{env:{...process.env,MULTIPLAYER_PORT:'0',MULTIPLAYER_ENABLED:String(enabled),DATA_DIR:dir},stdio:['ignore','pipe','pipe']});const port=await new Promise<number>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill();reject(Error('Server did not start.'));},10000);child.stdout.on('data',data=>{const match=String(data).match(/backend :(\d+)/);if(match){clearTimeout(timer);resolve(Number(match[1]));}});child.on('error',reject);child.stderr.on('data',data=>{clearTimeout(timer);reject(Error(String(data)));});});return {child,url:`http://127.0.0.1:${port}`};};
 let instance:Awaited<ReturnType<typeof start>>|undefined;let ws:WebSocket|undefined;
 try{instance=await start(false);const status=await fetch(instance.url+'/api/status');assert.equal((await status.json()).enabled,false);assert.equal((await fetch(instance.url+'/api/guest',{method:'POST'})).status,503);instance.child.kill();await once(instance.child,'exit');instance=await start(true);
 const post=(path:string,body:unknown)=>fetch(instance!.url+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const registration=await post('/api/register',{username:'tester',password:'test-password-123'});assert.equal(registration.status,201);assert.match(registration.headers.get('set-cookie')??'',/HttpOnly/);assert.equal((await post('/api/login',{username:'tester',password:'wrong-password'})).status,401);assert.equal((await post('/api/login',{username:'tester',password:'test-password-123'})).status,200);
 const guest=await post('/api/guest',{name:'Guest without email'});assert.equal(guest.status,200);const cookie=guest.headers.get('set-cookie')!.split(';')[0];ws=new WebSocket(instance.url.replace('http','ws')+'/ws',{headers:{Cookie:cookie,Origin:'http://localhost:5173'}});const welcomePromise=new Promise<string>(resolve=>ws!.once('message',data=>resolve(String(data))));await once(ws,'open');const welcome=JSON.parse(await welcomePromise);assert.equal(welcome.type,'welcome');
 const world=new Promise<Record<string,unknown>>(resolve=>ws!.on('message',data=>{const m=JSON.parse(String(data));if(m.type==='world')resolve(m);}));ws.send(JSON.stringify({type:'chat',text:'Ready for the future city.'}));const snapshot=await world;assert.ok(Array.isArray(snapshot.players));assert.ok(!JSON.stringify(snapshot).includes('test-password'));assert.equal((snapshot.chat as {text:string}[])[0].text,'Ready for the future city.');ws.close();await once(ws,'close');
 }finally{ws?.terminate();if(instance){instance.child.kill();await Promise.race([once(instance.child,'exit'),new Promise(r=>setTimeout(r,1000))]);}assert.equal(dirname(resolve(dir)),resolve(tmpdir()));assert.ok(basename(dir).startsWith('9lives-test-'));await rm(dir,{recursive:true,force:true});}
});
