// Future multiplayer backend. Disabled by default; the current client shows Coming soon.
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { randomBytes, scrypt, timingSafeEqual, createHash } from 'node:crypto';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile, rename } from 'node:fs/promises';
import { resolve } from 'node:path';
import { WebSocketServer, WebSocket } from 'ws';
import { Room, makePlayer, type Player } from './room';
const enabled=process.env.MULTIPLAYER_ENABLED==='true';const port=Number(process.env.MULTIPLAYER_PORT??3001);const dataDir=resolve(process.env.DATA_DIR??'.data');const hashPassword=promisify(scrypt);
type Account={username:string;salt:string;hash:string;email?:string;player:Player};type Session={id:string;expires:number};
const room=new Room(),accounts=new Map<string,Account>(),sessions=new Map<string,Session>(),guests=new Map<string,Player>(),limits=new Map<string,{count:number;reset:number}>();let writing=Promise.resolve();
async function persist(){const data=JSON.stringify({accounts:[...accounts],sessions:[...sessions],guests:[...guests]});writing=writing.catch(()=>{}).then(async()=>{await mkdir(dataDir,{recursive:true});await writeFile(resolve(dataDir,'state.tmp'),data,{mode:0o600});await rename(resolve(dataDir,'state.tmp'),resolve(dataDir,'state.json'));});await writing;}
async function load(){try{const data=JSON.parse(await readFile(resolve(dataDir,'state.json'),'utf8'));for(const [k,v] of data.accounts??[])accounts.set(k,v);for(const [k,v] of data.sessions??[])if(v.expires>Date.now())sessions.set(k,v);for(const [k,v] of data.guests??[])guests.set(k,v);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}}
const digest=(token:string)=>createHash('sha256').update(token).digest('hex');
function session(req:IncomingMessage){const token=req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('9lives_session='))?.slice(15);if(!token)return null;const s=sessions.get(digest(token));return s&&s.expires>Date.now()?s:null;}
function respond(res:ServerResponse,status:number,data:unknown){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function sameOrigin(req:IncomingMessage){if(!req.headers.origin)return true;const origins=(process.env.ALLOWED_ORIGINS??'http://localhost:5173,http://localhost:3001').split(',');return origins.includes(req.headers.origin);}
function rateLimit(key:string,max=20,window=60000){const now=Date.now(),old=limits.get(key);if(!old||old.reset<now){limits.set(key,{count:1,reset:now+window});return false;}return ++old.count>max;}
async function body(req:IncomingMessage){let value='';for await(const chunk of req){value+=chunk;if(value.length>8192)throw Error('Request too large.');}return JSON.parse(value||'{}') as Record<string,unknown>;}
async function issue(res:ServerResponse,id:string){const token=randomBytes(32).toString('hex');sessions.set(digest(token),{id,expires:Date.now()+86400000});res.setHeader('Set-Cookie',`9lives_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${process.env.COOKIE_SECURE==='true'?'; Secure':''}`);await persist();}
const server=createServer(async(req,res)=>{try{if(req.url==='/api/status')return respond(res,200,{enabled,status:enabled?'available':'coming-soon'});if(!enabled)return respond(res,503,{error:'Multiplayer and online accounts are coming soon.'});if(!sameOrigin(req))return respond(res,403,{error:'Origin is not allowed.'});if(req.method!=='POST')return respond(res,404,{error:'Not found.'});if(rateLimit(req.socket.remoteAddress??'local'))return respond(res,429,{error:'Too many requests. Try again later.'});const data=await body(req);
  if(req.url==='/api/guest'){if(sessions.size>=10000)return respond(res,503,{error:'Server is at capacity.'});const p=makePlayer(undefined,typeof data.name==='string'?data.name.trim().slice(0,24)||'Guest':'Guest');guests.set(p.id,p);await issue(res,p.id);return respond(res,200,{id:p.id,name:p.name,guest:true});}
  if(req.url==='/api/register'||req.url==='/api/login'){const username=typeof data.username==='string'?data.username.toLowerCase().trim():'';const password=typeof data.password==='string'?data.password:'';if(!/^[a-z0-9_]{3,24}$/.test(username)||password.length<10||password.length>128)return respond(res,400,{error:'Use a 3–24 character username and a 10–128 character password. Email is optional.'});if(req.url==='/api/register'){if(accounts.has(username))return respond(res,409,{error:'Username already taken.'});const email=typeof data.email==='string'?data.email.trim():'';if(email&&(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254))return respond(res,400,{error:'Check the optional email address.'});const salt=randomBytes(16).toString('hex');const hash=(await hashPassword(password,salt,64) as Buffer).toString('hex');if(accounts.has(username))return respond(res,409,{error:'Username already taken.'});const player=makePlayer(undefined,username);accounts.set(username,{username,salt,hash,email:email||undefined,player});await issue(res,player.id);return respond(res,201,{id:player.id,name:username});}const account=accounts.get(username);const hashed=await hashPassword(password,account?.salt??'missing-account',64) as Buffer;if(!account||!timingSafeEqual(hashed,Buffer.from(account.hash,'hex')))return respond(res,401,{error:'Username or password is incorrect.'});await issue(res,account.player.id);return respond(res,200,{id:account.player.id,name:username});}
  if(req.url==='/api/logout'){const s=session(req);const token=req.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('9lives_session='))?.slice(15);if(token)sessions.delete(digest(token));if(s)for(const socket of sockets.keys())if(sockets.get(socket)===s.id)socket.close();res.setHeader('Set-Cookie','9lives_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');await persist();return respond(res,200,{ok:true});}return respond(res,404,{error:'Not found.'});
}catch(e){console.error('Request failed:',(e as Error).message);respond(res,400,{error:'The request could not be processed.'});}});
const wss=new WebSocketServer({noServer:true,maxPayload:8192});const sockets=new Map<WebSocket,string>();
server.on('upgrade',(req,socket,head)=>{const auth=session(req);if(!enabled||req.url!=='/ws'||!auth||!sameOrigin(req)||!req.headers.origin){socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');socket.destroy();return;}if(sockets.size>=100){socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>{for(const [existing,id] of sockets)if(id===auth.id)existing.close();const account=[...accounts.values()].find(a=>a.player.id===auth.id);const p=account?.player??guests.get(auth.id);if(!p){ws.close();return;}if(!p.lives&&!p.breakUntil)p.breakUntil=Date.now()+3600000;p.protectedUntil=Date.now()+15000;p.lastMove=Date.now();room.players.set(p.id,p);sockets.set(ws,p.id);ws.send(JSON.stringify({type:'welcome',id:p.id}));ws.on('message',raw=>{try{if(rateLimit(`ws:${p.id}`,40,1000))throw Error('Slow down.');const message=JSON.parse(raw.toString());if(!message||typeof message!=='object'||Array.isArray(message))throw Error('Invalid message.');if(message.type==='move')room.move(p.id,message.x,message.z,message.driving);else {const result=room.action(p.id,message);ws.send(JSON.stringify({type:'result',result}));}}catch(e){ws.send(JSON.stringify({type:'error',error:(e as Error).message}));}});ws.on('error',()=>ws.close());ws.on('close',()=>{sockets.delete(ws);if(![...sockets.values()].includes(p.id)){room.players.delete(p.id);void persist().catch(console.error);}});});});
const tick=setInterval(()=>{if(!enabled)return;room.tick();const snapshot=JSON.stringify({type:'world',time:Date.now(),players:room.publicPlayers(),chat:room.chat});for(const ws of sockets.keys())if(ws.readyState===WebSocket.OPEN&&ws.bufferedAmount<65536)ws.send(snapshot);},200);
const cleanup=setInterval(()=>{const now=Date.now();for(const [k,v] of sessions)if(v.expires<now)sessions.delete(k);for(const [k,v] of limits)if(v.reset<now)limits.delete(k);if(enabled)void persist().catch(console.error);},30000);
async function stop(){clearInterval(tick);clearInterval(cleanup);for(const ws of sockets.keys())ws.close();await persist();server.close(()=>process.exit(0));}
process.on('SIGINT',()=>void stop());process.on('SIGTERM',()=>void stop());
if(enabled)await load();server.listen(port,'0.0.0.0',()=>{const address=server.address();console.log(`9LIVES future multiplayer backend :${typeof address==='object'&&address?address.port:port} · ${enabled?'enabled for development':'COMING SOON — disabled'}`);});
