import {test} from 'node:test';import assert from 'node:assert/strict';import {Room,makePlayer} from './room';
const setup=()=>{const r=new Room(),a=makePlayer('a','Ada'),b=makePlayer('b','Bayo');a.x=20;a.z=0;b.x=21;b.z=0;a.protectedUntil=b.protectedUntil=0;r.players.set(a.id,a);r.players.set(b.id,b);return {r,a,b};};
test('server rejects teleporting, invalid coordinates and unowned vehicle movement',()=>{const {r,a}=setup();const now=Date.now();a.lastMove=now;assert.equal(r.move('a',100,0,null,now+200),false);assert.equal(r.move('a',NaN,0,null,now+200),false);assert.equal(r.move('a',20.2,0,'car',now+200),false);assert.equal(r.move('a',20.2,0,null,now+200),true);});
test('authoritative purchases use catalog prices and consume funds',()=>{const {r,a}=setup();r.action('a',{type:'buy',item:'gun',price:0});assert.equal(a.money,500);assert.ok(a.inventory.includes('Pistol'));assert.throws(()=>r.action('a',{type:'buy',item:'ammo'}),/Insufficient/);});
test('combat consumes ammunition and a life only on lethal damage',()=>{const {r,a,b}=setup();a.lives=7;a.inventory.push('Pistol');a.ammo=3;const now=Date.now();r.action('a',{type:'attack',target:'b'},now);r.action('a',{type:'attack',target:'b'},now+1000);r.action('a',{type:'attack',target:'b'},now+2000);assert.equal(b.lives,8);assert.equal(a.ammo,0);assert.equal(a.lives,8);assert.ok(!a.inventory.includes('Life token'));assert.throws(()=>r.action('a',{type:'attack',target:'b'},now+2100),/protected/);});
test('safe zones and teammates cannot be attacked or robbed',()=>{const {r,a,b}=setup();a.inventory.push('Pistol');a.ammo=10;b.x=-6;b.z=-3;assert.throws(()=>r.action('a',{type:'attack',target:'b'}),/protected/);b.x=21;b.z=0;a.team=b.team='a';assert.throws(()=>r.action('a',{type:'rob',target:'b'}),/teammate/);});
test('robbery and gifts conserve money and transfer purchased items',()=>{const {r,a,b}=setup();b.health=20;b.inventory.push('Protective vest');const total=a.money+b.money;r.action('a',{type:'rob',target:'b'});assert.equal(a.money+b.money,total);assert.ok(a.inventory.includes('Protective vest'));r.action('a',{type:'gift',target:'b',amount:300});r.action('a',{type:'gift',target:'b',item:'Protective vest'});assert.equal(a.money+b.money,total);assert.ok(b.inventory.includes('Protective vest'));assert.throws(()=>r.action('a',{type:'gift',target:'b',amount:-1}),/Invalid/);});
test('bodyguards reduce combat damage and team invites require an invitation',()=>{const {r,a,b}=setup();a.inventory.push('Pistol');a.ammo=1;b.guards=3;r.action('a',{type:'attack',target:'b'});assert.equal(b.health,90);assert.throws(()=>r.action('b',{type:'accept-team',target:'a'}),/No matching/);r.action('a',{type:'invite',target:'b'});r.action('b',{type:'accept-team',target:'a'});assert.equal(a.team,b.team);});
test('server enforces one-hour break, then restarts with a fresh inventory and wallet',()=>{const {r,b}=setup(),now=Date.now();b.lives=1;b.health=10;b.inventory=['Pistol'];r.damage(b,20,now);assert.equal(b.lives,0);assert.equal(b.breakUntil,now+3600000);assert.throws(()=>r.action('b',{type:'restart'},now+3599999),/one-hour/);r.action('b',{type:'restart'},now+3600000);assert.equal(b.lives,9);assert.equal(b.money,5000);assert.deepEqual(b.inventory,[]);});
