import { randomInt, randomUUID } from 'node:crypto';
import { canMove, giftRewards, safeZone, shopItems, trafficAt, vehicles, type VehicleKind } from '../shared/city';
export type Player = { id:string; name:string; x:number; z:number; gender:'male'|'female'; shirt:string; skin:string; money:number; lives:number; health:number; inventory:string[]; ammo:number; guards:number; wanted:number; team:string|null; driving:VehicleKind|null; protectedUntil:number; lastMove:number; lastAttack:number; lastRob:number; lastWork:number };
export function makePlayer(id:string=randomUUID(),name='Guest'):Player{return {id,name,x:0,z:6,gender:'male',shirt:'#d4bb80',skin:'#714c36',money:5000,lives:9,health:100,inventory:[],ammo:0,guards:0,wanted:0,team:null,driving:null,protectedUntil:Date.now()+15000,lastMove:Date.now(),lastAttack:0,lastRob:0,lastWork:0};}
export class Room {
  players=new Map<string,Player>(); chat:{id:string;name:string;text:string;time:number}[]=[]; invitations=new Map<string,string>();
  player(id:string){const p=this.players.get(id);if(!p)throw Error('Player is not connected.');return p;}
  nearby(a:Player,b:Player,radius=4){return Math.hypot(a.x-b.x,a.z-b.z)<=radius;}
  publicPlayers(){return [...this.players.values()].map(({protectedUntil,lastMove,lastAttack,lastRob,lastWork,...p})=>p);}
  damage(p:Player,amount:number,now=Date.now()){if(!p.lives||p.protectedUntil>now)return false;p.health=Math.max(0,p.health-amount);if(p.health===0){p.lives--;p.health=p.lives?100:0;p.x=-6;p.z=-3;p.driving=null;p.protectedUntil=now+15000;p.money=Math.max(0,p.money-1200);return true;}return false;}
  move(id:string,x:unknown,z:unknown,driving:unknown,now=Date.now()){const p=this.player(id);if(!p.lives||typeof x!=='number'||typeof z!=='number'||!canMove(x,z))return false;const kind=typeof driving==='string'&&driving in vehicles?driving as VehicleKind:null;if(kind&&!p.inventory.includes(vehicles[kind].key))return false;const speed=kind?vehicles[kind].speed*1.4:5.2;const dt=Math.min(1,Math.max(0,(now-p.lastMove)/1000));if(Math.hypot(x-p.x,z-p.z)>speed*dt+.35)return false;p.x=x;p.z=z;p.driving=kind;p.lastMove=now;return true;}
  action(id:string,message:Record<string,unknown>,now=Date.now()){
    const p=this.player(id);const type=message.type;
    if(type==='chat'){if(typeof message.text!=='string'||!message.text.trim()||message.text.length>240)throw Error('Messages must be 1–240 characters.');this.chat.push({id:p.id,name:p.name,text:message.text.trim(),time:now});this.chat=this.chat.slice(-50);return;}
    if(!p.lives)throw Error('This campaign has ended.');
    if(type==='buy'){const item=shopItems.find(i=>i.id===message.item);const vehicle=typeof message.item==='string'&&message.item in vehicles?vehicles[message.item as VehicleKind]:null;const cost=item?.price??vehicle?.price;if(cost===undefined)throw Error('Unknown item.');if(p.money<cost)throw Error('Insufficient cash.');if(vehicle&&p.inventory.includes(vehicle.key))throw Error('Vehicle already owned.');if(item?.id==='guard'&&p.guards>=3)throw Error('Maximum three guards.');p.money-=cost;if(vehicle)p.inventory.push(vehicle.key);else if(item!.id==='food')p.health=Math.min(100,p.health+10);else if(item!.id==='water')p.health=Math.min(100,p.health+5);else if(item!.id==='ammo')p.ammo+=6;else if(item!.id==='guard')p.guards++;else p.inventory.push(item!.name);return;}
    if(type==='work'){if(now-p.lastWork<60000)throw Error('Your next shift is not ready.');p.lastWork=now;p.money+=3000;return;}
    if(type==='open-gift'){const index=p.inventory.indexOf('Mystery gift box');if(index<0)throw Error('No gift box.');p.inventory.splice(index,1);const reward=giftRewards[randomInt(giftRewards.length)];if(reward==='Cash')p.money+=2000;else if(reward==='Ammo pack')p.ammo+=6;else if(reward==='Bodyguard contract')p.guards=Math.min(3,p.guards+1);else if(reward==='Life token')p.lives=Math.min(9,p.lives+1);else p.inventory.push(reward);return reward;}
    const target=typeof message.target==='string'?this.player(message.target):null;if(!target||target.id===id)throw Error('Choose another connected player.');
    if(type==='invite'){this.invitations.set(target.id,p.id);return;}
    if(type==='accept-team'){if(this.invitations.get(id)!==target.id)throw Error('No matching invitation.');this.invitations.delete(id);p.team=target.team??target.id;target.team=p.team;return;}
    if(type==='gift'){if(!this.nearby(p,target,6))throw Error('Move closer to give a gift.');const amount=message.amount;if(typeof amount==='number'){if(!Number.isInteger(amount)||amount<1||amount>p.money)throw Error('Invalid gift amount.');p.money-=amount;target.money+=amount;}else if(typeof message.item==='string'){const i=p.inventory.indexOf(message.item);if(i<0)throw Error('You do not own this item.');p.inventory.splice(i,1);target.inventory.push(message.item);}else throw Error('Select cash or an item.');return;}
    if(p.team&&p.team===target.team)throw Error('You cannot attack or rob a teammate.');
    if(p.protectedUntil>now||target.protectedUntil>now||safeZone(p.x,p.z)||safeZone(target.x,target.z)||!target.lives)throw Error('This player is protected.');
    if(type==='attack'){if(!this.nearby(p,target,12))throw Error('Target is out of range.');if(!p.inventory.includes('Pistol')||p.ammo<1)throw Error('A pistol and ammunition are required.');if(now-p.lastAttack<900)throw Error('Weapon cooling down.');p.lastAttack=now;p.ammo--;const reduction=(target.inventory.includes('Protective vest')?.65:1)*Math.max(.25,1-target.guards*.25);const killed=this.damage(target,40*reduction,now);p.wanted=Math.min(5,p.wanted+(killed?2:1));if(killed)p.inventory.push('Life token');return killed?'A life was lost.':'Hit.';}
    if(type==='rob'){if(!this.nearby(p,target,3))throw Error('Move closer.');if(target.health>30)throw Error('Target must have 30 health or less.');if(now-p.lastRob<10000)throw Error('Robbery cooling down.');p.lastRob=now;const cash=Math.min(500,target.money);target.money-=cash;p.money+=cash;if(target.inventory.length)p.inventory.push(target.inventory.pop()!);p.wanted=Math.min(5,p.wanted+1);return;}
    throw Error('Unknown action.');
  }
  tick(now=Date.now()){for(const p of this.players.values()){if(!p.lives)continue;for(const t of trafficAt(now/1000)){if(Math.abs(p.x-t.x)<1.15&&Math.abs(p.z-t.z)<(t.kind==='bus'?2.5:1.8)){this.damage(p,p.driving?45:100,now);break;}}}}
}
