export type Point=[number,number];
export type Walkable=(x:number,z:number)=>boolean;
export function clearSegment(a:Point,b:Point,free:Walkable){const steps=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.22));for(let i=1;i<=steps;i++)if(!free(a[0]+(b[0]-a[0])*i/steps,a[1]+(b[1]-a[1])*i/steps))return false;return true;}
class Heap{items:{key:string;score:number}[]=[];push(item:{key:string;score:number}){let i=this.items.push(item)-1;while(i>0){const p=(i-1)>>1;if(this.items[p].score<=item.score)break;this.items[i]=this.items[p];i=p;}this.items[i]=item;}pop(){const root=this.items[0],last=this.items.pop();if(this.items.length&&last){let i=0;while(i*2+1<this.items.length){let child=i*2+1;if(child+1<this.items.length&&this.items[child+1].score<this.items[child].score)child++;if(this.items[child].score>=last.score)break;this.items[i]=this.items[child];i=child;}this.items[i]=last;}return root;}}
export function findRoute(from:Point,to:Point,free:Walkable,maxNodes=18000):Point[]|null{
 if(![...from,...to].every(Number.isFinite)||!free(...to))return null;if(clearSegment(from,to,free))return [[...to]];
 const candidates=Array.from({length:25},(_,i)=>[Math.round(from[0])+i%5-2,Math.round(from[1])+Math.floor(i/5)-2] as Point).filter(p=>free(...p)&&clearSegment(from,p,free)).sort((a,b)=>Math.hypot(a[0]-from[0],a[1]-from[1])-Math.hypot(b[0]-from[0],b[1]-from[1]));if(!candidates.length)return null;
 const start=candidates[0],key=(p:Point)=>p.join(','),frontier=new Heap(),cost=new Map<string,number>(),previous=new Map<string,string>(),closed=new Set<string>(),cache=new Map<string,boolean>();const heuristic=(p:Point)=>Math.hypot(p[0]-to[0],p[1]-to[1]);frontier.push({key:key(start),score:heuristic(start)});cost.set(key(start),0);const valid=(p:Point)=>{const k=key(p);if(!cache.has(k))cache.set(k,free(...p));return cache.get(k)!;};
 while(frontier.items.length&&closed.size<maxNodes){const node=frontier.pop();if(closed.has(node.key))continue;closed.add(node.key);const p=node.key.split(',').map(Number) as Point;if(heuristic(p)<1.6&&clearSegment(p,to,free)){const path:Point[]=[[...to],p];let k=node.key;while(previous.has(k)){k=previous.get(k)!;path.push(k.split(',').map(Number) as Point);}path.reverse();const result:Point[]=[];let anchor=from,i=0;while(i<path.length){let last=i;while(last+1<path.length&&clearSegment(anchor,path[last+1],free))last++;result.push(path[last]);anchor=path[last];i=last+1;}return result;}
 for(const [dx,dz] of [[0,1],[1,0],[0,-1],[-1,0],[1,1],[-1,1],[1,-1],[-1,-1]]){const n:Point=[p[0]+dx,p[1]+dz];if(!valid(n)||!clearSegment(p,n,free))continue;const nk=key(n),score=cost.get(node.key)!+Math.hypot(dx,dz);if(score>=(cost.get(nk)??Infinity))continue;cost.set(nk,score);previous.set(nk,node.key);frontier.push({key:nk,score:score+heuristic(n)});}}
 return null;
}
export type Body={id:string;x:number;z:number;radius:number};
export function avoidsBodies(from:Point,to:Point,bodies:Body[],radius=.3,ignore=''){return bodies.every(b=>{if(b.id===ignore)return true;const before=Math.hypot(from[0]-b.x,from[1]-b.z),after=Math.hypot(to[0]-b.x,to[1]-b.z);return after>=radius+b.radius||(before<radius+b.radius&&after>before+.00001);});}
export function cameraFraction(from:[number,number,number],to:[number,number,number],boxes:{x:number;z:number;w:number;d:number;h:number}[]){let hit=1;for(const b of boxes){let low=0,high=1;const mins=[b.x-b.w/2-.15,0,b.z-b.d/2-.15],maxs=[b.x+b.w/2+.15,b.h+.1,b.z+b.d/2+.15];let intersects=true;for(let i=0;i<3;i++){const delta=to[i]-from[i];if(Math.abs(delta)<.00001){if(from[i]<mins[i]||from[i]>maxs[i])intersects=false;continue;}const a=(mins[i]-from[i])/delta,c=(maxs[i]-from[i])/delta;low=Math.max(low,Math.min(a,c));high=Math.min(high,Math.max(a,c));if(low>high)intersects=false;}if(intersects&&high>0&&low>.02)hit=Math.min(hit,Math.max(.04,low-.035));}return hit;}
