import { districts, blockers, streetObstacles, riverClear, type DistrictId } from './city';

export const buildTypes = { house: { name: 'House', price: 9000 }, club: { name: 'Club', price: 16000 }, church: { name: 'Church', price: 12000 }, shop: { name: 'Shop', price: 7000 } };
export type BuildKind = keyof typeof buildTypes;
export const furnishings = { fridge:{name:'Refrigerator',price:6500},wardrobe:{name:'Wardrobe',price:2500},computer:{name:'Computer desk',price:7500},chair:{name:'Chair',price:450},lamp:{name:'Room lamp',price:750},fan:{name:'Fan',price:1200},ac:{name:'Air conditioner',price:6000},shelf:{name:'Storage shelves',price:1200},sofa: { name: 'Sofa', price: 900 }, bed: { name: 'Bed', price: 1200 }, tv: { name: 'Television', price: 1800 }, kitchen: { name: 'Kitchen', price: 1500 }, table: { name: 'Dining table', price: 700 }, plant: { name: 'Indoor plant', price: 250 } };
export type Furniture = keyof typeof furnishings;
export type Placement={x:number;z:number;rotation:number};
export type RoomWall={x:number;z:number;length:number;axis:string};
export type Property = { id: string; kind: BuildKind | 'land'; furniture: Furniture[]; level: number; placements?: Partial<Record<Furniture,Placement>>; decor?:Partial<Record<'paint'|'floor'|'door'|'window',string>>;walls?:RoomWall[] };
export type Parcel={id:string;district:DistrictId;name:string;x:number;z:number;price:number;built:boolean;size?:number;zone?:'village'|'town'|'city'|'highway'|'industrial';housing?:number};
export const parcels:Parcel[] = districts.flatMap((d, i) => [
  { id: `house-${d.id}`, district: d.id, name: `${d.name} ${['apartment','courtyard home','townhouse','penthouse','family house','villa'][i]}`, x: d.x-20, z: d.z-19, price: [0,16000,28000,65000,18000,55000][i], built: true },
  { id: `plot-${d.id}`, district: d.id, name: `${d.name} development plot`, x: d.x+20, z: d.z-19, price: [6000,5000,9000,18000,4500,15000][i], built: false },
]);
for(let z=-146;z<18;z+=16)for(let x=-136;x<140;x+=16){if([-100,0,100].some(r=>Math.abs(x-r)<15)||[-86,14,-60].some(r=>Math.abs(z-r)<12)||!riverClear(x,z)||[...blockers,...streetObstacles,...parcels.map(p=>({...p,w:8,d:8}))].some(b=>Math.abs(x-b.x)<b.w/2+9&&Math.abs(z-b.z)<b.d/2+9))continue;const d=[...districts].sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z))[0],zone=x< -110?'industrial':z< -125?'village':Math.abs(x-d.x)>30?'highway':d.id==='vi'||d.id==='ikeja'?'city':'town',price=zone==='city'?24000:zone==='highway'?12000:zone==='industrial'?8000:zone==='village'?4500:10000;parcels.push({id:`land-${x}-${z}`,district:d.id,name:`${d.name} ${zone} plot ${parcels.length}`,x,z,price,built:false,size:16,zone});}
// The original apartment entrance stays in place for existing saves.
parcels[0] = { ...parcels[0], x: -9, z: -4, price:12000 };
for(let z=-148;z<23;z+=8)for(let x=-140;x<141;x+=8){if([-100,0,100].some(r=>Math.abs(x-r)<11)||[-86,14,-60].some(r=>Math.abs(z-r)<9)||[...blockers,...streetObstacles,...parcels.map(p=>({...p,w:p.size??8,d:p.size??8}))].some(b=>Math.abs(x-b.x)<b.w/2+4.2&&Math.abs(z-b.z)<b.d/2+4.2))continue;const d=[...districts].sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z))[0],zone=x<-110?'industrial':z<-125?'village':d.id==='vi'?'city':'town';parcels.push({id:`infill-${x}-${z}`,district:d.id,name:`${d.name} ${zone} small plot ${parcels.length}`,x,z,price:zone==='city'?6000:zone==='village'?1500:3000,built:false,size:8,zone});}
const housingNames=['Shared room','Single-room apartment','Self-contained apartment','Mini flat','One-bedroom apartment','Two-bedroom apartment','Three-bedroom apartment','Duplex','Luxury villa','Mansion','Penthouse','Estate property'];const housingLots=parcels.filter(p=>!p.built).slice(0,12);housingLots.forEach((p,i)=>{p.built=true;p.housing=i+1;p.name=`${housingNames[i]} · ${districts.find(d=>d.id===p.district)!.name}`;p.price=5000+i*i*3500;});
export const starterProperty = (): Property => ({ id: 'house-yaba', kind: 'house', furniture: ['bed','sofa','tv','kitchen'], level: 1 });
export const entrance = (p: typeof parcels[number]): [number,number] => p.id==='house-yaba'?[-6,-3]:[p.x,p.z+(p.size??6)/2+1.5];
export const propertyDistrict = (id: string): DistrictId => parcels.find(p=>p.id===id)?.district??'yaba';
export function validProperties(value: unknown): value is Property[] {
  return Array.isArray(value) && value.length<=parcels.length && new Set(value.map(p=>p?.id)).size===value.length && value.every(p=>p && parcels.some(a=>a.id===p.id) && (p.kind==='land'||Object.hasOwn(buildTypes,p.kind)) && Number.isInteger(p.level)&&p.level>=1&&p.level<=12 && Array.isArray(p.furniture)&&p.furniture.every((f:unknown)=>typeof f==='string'&&Object.hasOwn(furnishings,f))&&new Set(p.furniture).size===p.furniture.length && (p.placements===undefined||p.placements&&typeof p.placements==='object'&&!Array.isArray(p.placements)&&Object.entries(p.placements).every(([key,raw])=>{const t=raw as Placement;return p.furniture.includes(key)&&t&&[t.x,t.z,t.rotation].every(Number.isFinite)&&Math.abs(t.x)<=3&&Math.abs(t.z)<=3;}))&&(p.decor===undefined||p.decor&&typeof p.decor==='object'&&Object.entries(p.decor).every(([key,value])=>['paint','floor','door','window'].includes(key)&&typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)))&&(p.walls===undefined||Array.isArray(p.walls)&&p.walls.length<=12&&p.walls.every((w:RoomWall)=>w&&[w.x,w.z,w.length].every(Number.isFinite)&&Math.abs(w.x)<=3&&Math.abs(w.z)<=3&&w.length>0&&w.length<=6&&['x','z'].includes(w.axis))));
}
