import { Component, lazy, Suspense, useEffect, useRef, useState, type ReactNode, type PointerEvent } from 'react';
import { ArrowUpRight, Backpack, BookOpen, ChevronRight, Compass, Droplets, Expand, Heart, Map, Users, Pause, Play, Settings, ShieldCheck, Sparkles, Sun, UserRound, Utensils, X, Zap, Save, RotateCcw, Footprints, CircleHelp } from 'lucide-react';
import { controls, locations, useGame } from './game';
import { districts, districtAt, type Place } from '../shared/city';
import { CharacterCreator, CityMap, ExpandedDialog, expandedModals, LoadingScreen, TravelHUD } from './Expansion';
const World = lazy(() => import('./World'));
const money = (n: number) => `₦${n.toLocaleString('en-NG')}`;
const objectives: Record<string, [string, string, string]> = { meet: ['A fresh start', 'Find Tunde on your street', 'An old friend might know where to find your next opportunity.'], offer: ['The midnight delivery', 'Hear out the offer', 'Tunde has a contact. Easy money rarely comes without a catch.'], delivery: ['The midnight delivery', 'Reach the meeting point', 'Head north. Your contact is waiting at the end of the street.'], complete: ['A future of your own', 'Your story is just beginning', 'Delivery complete. Work, rest, and explore the neighborhood.'], declined: ['A different path', 'Make an honest living', 'You chose peace of mind. The workshop always needs a hand.'] };
Object.assign(objectives,{trust:['The price of trust','Meet Nurse Sade in Ikorodu','Board a vehicle at a motor park and travel to Ikorodu.'],ledger:['What the river keeps','Find the riverfront ledger','Sade’s lead points to the depot at the north end of Ikorodu.'],evidence:['Survival costs money','Take the ledger to Ikeja','The EFCC field office can help. Or you could sell the evidence.'],contract:['Nine chances','Visit Island Logistics','Travel to Victoria Island. Your last choice will shape your legacy.'],finale:['A life of your own','Your legacy lives on','Explore, earn, and collect. Your five-chapter story is complete.']});
function openPlace(l:Place){const s=useGame.getState();if(s.ride||s.paused||!s.game.created)return;s.open(l.type==='delivery'?(s.game.stage==='delivery'?'delivery':'locked'):l.type==='terminal'?'transport':l.type==='shop'?'equipment':l.type);}
function WorldLabels() {
  const stage = useGame(s => s.game.stage);
  return <>{locations.map(l => <div className="projected-marker" id={`marker-${l.id}`} key={l.id}><button className={`world-label ${l.id === 'tunde' && stage === 'meet' || l.id === 'delivery' && stage === 'delivery' ? 'quest-label' : ''}`} onClick={() => { const s = useGame.getState(); if (s.paused || s.game.lives === 0) return; const p = controls.position; if (Math.hypot(p[0] - l.x, p[1] - l.z) > 3) s.notify(`Walk closer to ${l.name} to interact.`); else openPlace(l); }}><span>{l.type === 'home' ? '⌂' : l.type === 'terminal' ? '▣' : l.type==='hospital'?'✚':l.type==='police'||l.type==='efcc'?'⛨':l.type === 'shop' ? '▧' : '◇'}</span>{l.name}{l.id === 'tunde' && stage === 'meet' && <i>!</i>}</button></div>)}<div className="projected-marker" id="marker-player"><span className="player-tag">YOU <span>◆</span></span></div></>;
}
function interact() { const s = useGame.getState(); if (s.modal || s.paused || s.ride || !s.game.created || s.game.lives === 0) return; const l = [...locations].sort((a, b) => Math.hypot(a.x - controls.position[0], a.z - controls.position[1]) - Math.hypot(b.x - controls.position[0], b.z - controls.position[1]))[0]; if (Math.hypot(l.x - controls.position[0], l.z - controls.position[1]) > 3) s.notify('Move closer to a person or marked location.'); else openPlace(l); }
class WorldBoundary extends Component<{ children: ReactNode }, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; } render() { return this.state.failed ? <div className="loading"><Compass size={36} /><h2>3D rendering is unavailable</h2><p>Enable hardware acceleration or try a browser with WebGL support.</p><button onClick={() => location.reload()}>Try again</button></div> : this.props.children; } }
function MiniMap({ large = false }: { large?: boolean }) {
  const p = useGame(s => s.game.position);
  return <svg className={large ? 'large-map' : 'mini-map'} viewBox="0 0 180 150" role="img" aria-label="City map with six districts and your position"><rect width="180" height="150" rx="8" fill="#26382f"/><path d="M30 15V133M90 15V133M150 15V133M18 36H163M18 109H163" stroke="#718074" strokeWidth="7"/>{districts.map(d=><g key={d.id}><circle cx={90+d.x*.6} cy={109+d.z*.73} r="7" fill="#4e6051" stroke="#bdc49e"/><text x={90+d.x*.6} y={124+d.z*.73} textAnchor="middle" fill="#dce4ca" fontSize="6">{d.name}</text></g>)}<circle cx={90+p[0]*.6} cy={109+p[1]*.73} r="3" fill="#f6dba1"/><text x="162" y="16" fill="#e1d9bc" fontSize="8">N ↑</text></svg>;
}
function Joystick() {
  const [stick, setStick] = useState({ x: 0, y: 0 }); const active = useRef(false);
  const move = (e: PointerEvent<HTMLDivElement>) => { if (!active.current) return; const r = e.currentTarget.getBoundingClientRect(); let x = e.clientX - r.left - r.width / 2, y = e.clientY - r.top - r.height / 2; const d = Math.hypot(x, y); if (d > 31) { x *= 31 / d; y *= 31 / d; } controls.x = x / 31; controls.z = y / 31; setStick({ x, y }); };
  const release = () => { active.current = false; controls.x = 0; controls.z = 0; setStick({ x: 0, y: 0 }); };
  useEffect(() => { window.addEventListener('blur', release); return () => window.removeEventListener('blur', release); }, []);
  return <div className="joystick-group"><div className="joystick" role="group" aria-label="Touch movement joystick" onPointerDown={e => { active.current = true; e.currentTarget.setPointerCapture(e.pointerId); move(e); }} onPointerMove={move} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}><span className="direction north">⌃</span><span className="direction south">⌄</span><span className="direction west">‹</span><span className="direction east">›</span><div className="stick" style={{ transform: `translate(${stick.x}px, ${stick.y}px)` }}><Footprints size={22} /></div></div><span className="control-caption">MOVE <kbd>W A S D</kbd></span></div>;
}
function Dialog() {
  const modal = useGame(s => s.modal), g = useGame(s => s.game), open = useGame(s => s.open), action = useGame(s => s.action); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; ref.current?.focus(); return () => previous?.focus(); }, [modal]);
  if (!modal) return null;
  if(expandedModals.includes(modal))return <ExpandedDialog/>;
  let title = '', eyebrow = 'YOUR NEIGHBORHOOD', body: ReactNode = null;
  const choice = (text: string, sub: string, id: string, dangerous = false) => <button className={`choice ${dangerous ? 'danger-choice' : ''}`} onClick={() => action(id)}><span><strong>{text}</strong><small>{sub}</small></span><ChevronRight size={18} /></button>;
  if (modal === 'tunde') { title = 'An old friend. A new beginning.'; eyebrow = 'TUNDE · CHILDHOOD FRIEND'; body = <><div className="quote">“Look who finally made it back to Yaba! The city hasn’t changed, but you can. I know someone with a delivery job. Good pay. Strange hours.”</div><p>Your friendship: {g.relationships.tunde}/100</p>{g.stage === 'meet' || g.stage === 'offer' ? choice('Tell me about the job', 'Unlock The Midnight Delivery · Communication +1', 'talk') : <p>“Keep your eyes open out there. And come back in one piece.”</p>}</>; }
  if (modal === 'offer' || modal === 'clue') { eyebrow = 'CHAPTER 02 · THE MIDNIGHT DELIVERY'; title = modal === 'clue' ? 'Something doesn’t add up.' : 'Easy money. Difficult questions.'; body = <><div className="quote">{modal === 'clue' ? 'The contact insists on a back-alley handoff. Tunde says a public meeting would be safer. You now know how to avoid the trap.' : '“One sealed package. No questions. ₦1,000 now, ₦4,000 when it’s done. Meet the contact at the north end of the street.”'}</div><div className="risk-note"><ShieldCheck size={17} /> {g.echoes > 0 ? 'Life Echo: you remember the danger in the alley.' : 'Unknown contact. Investigate before committing.'}</div>{modal !== 'clue' && choice('Ask a few questions', 'Learn about the handoff · Awareness +1', 'investigate')}{choice('Accept the delivery', '₦1,000 advance · A risky opportunity', 'accept')}{choice('Walk away', 'Choose an honest path. Keep all your lives.', 'decline')}</>; }
  if (modal === 'shop') { title = 'A little fuel for the journey.'; eyebrow = 'AMARA’S PROVISIONS · OPEN'; body = <><div className="quote">“You can’t face Lagos on an empty stomach, my dear.”</div><div className="shop-balance">Available cash <strong>{money(g.money)}</strong></div>{choice('Fresh jollof rice', '₦1,500 · Fullness +40 · Health +5', 'eat')}{choice('Bottled water', '₦300 · Hydration +50', 'water')}</>; }
  if (modal === 'home') { title = 'Somewhere to come back to.'; eyebrow = 'YOUR APARTMENT · SAFE LOCATION'; body = <><p>Your small apartment isn’t much, but the door locks and the bed is yours. Rest restores your health and energy. Time passes, so eat and drink first.</p>{choice('Get some sleep', 'Rest for 6 hours · Restore energy · Reduce stress', 'sleep')}<button className="choice" onClick={() => void useGame.getState().save()}><span><strong>Save your progress</strong><small>Store your campaign on this device</small></span><Save size={19} /></button></>; }
  if (modal === 'work') { title = 'An honest day’s work.'; eyebrow = 'FEMI AUTO WORKS'; body = <><p>Help Femi clean parts and organize the workshop. Two hours, steady pay, no secrets. You need at least 25 energy.</p>{choice('Work a shift', 'Earn ₦3,000 · 2 hours · Costs energy · Fitness +1', 'work')}</>; }
  if (modal === 'delivery') { title = 'The last turn.'; eyebrow = 'THE HANDOFF · CHOOSE CAREFULLY'; const unlocked = g.skills.awareness > 1 || g.echoes > 0; body = <><div className="quote">Your contact steps out of the shadows. “Come around the back. We don’t want anyone watching.” The alley is dark. The main street is still busy.</div><div className="risk-note danger"><ShieldCheck size={17} /> Alley risk: {g.stats.energy < 30 ? '85%' : '55%'} chance of losing a life. Medical cost: ₦1,200.</div>{unlocked ? choice('Insist on meeting in public', 'Use your knowledge · Safe handoff · Earn ₦4,000', 'safe') : <button className="choice" onClick={() => open('delivery-clue')}><span><strong>Call Tunde before proceeding</strong><small>Ask for advice. The alley can wait.</small></span><ChevronRight size={18} /></button>}{choice('Follow into the alley', 'High risk · Potential ₦6,500 reward', 'risk', true)}<button className="choice" onClick={() => open(null)}><span><strong>Leave for now</strong><small>Keep the package and return when ready</small></span><ChevronRight size={18} /></button></>; }
  if (modal === 'delivery-clue') { title = 'Trust the people who know you.'; eyebrow = 'PHONE CALL · TUNDE'; body = <><div className="quote">“An alley? No. Keep it on the main street. If they want the package, they’ll come to you.”</div><button className="choice" onClick={() => { useGame.getState().update(g => ({ ...g, skills: { ...g.skills, awareness: g.skills.awareness + 1 } })); open('delivery'); }}><span><strong>Keep the handoff public</strong><small>Awareness +1 · Unlock a safe choice</small></span><ChevronRight size={18} /></button></>; }
  if (modal === 'locked') { title = 'Nothing here. Yet.'; body = <p>Your contact will appear after you accept Tunde’s delivery offer.</p>; }
  if (modal === 'death') { title = g.lives ? 'One life lost. A lesson kept.' : 'Every life has a story.'; eyebrow = g.lives ? `LIFE ECHO ${g.echoes} · ${g.lives} LIVES REMAIN` : 'CAMPAIGN OVER'; body = <><p>{g.lives ? `Cause: ${g.deathCause??'Dangerous handoff'}. You woke at your last safe checkpoint. Medical expenses cost up to ₦1,200. Your skills, relationships, and purchased equipment remain. Crossing traffic is dangerous: use the sidewalk and watch both lanes.` : 'Your nine chances have run out. Begin again with a fresh character and a new chance to make your way.'}</p>{g.lives > 0 && <button className="primary" onClick={() => open(null)}>Try again, a little wiser <ArrowUpRight size={17} /></button>}<button className="choice" onClick={() => open('restart')}><span><strong>Start a new campaign</strong><small>Reset this campaign</small></span><RotateCcw size={18} /></button></>; }
  if (modal === 'ending') { title = g.stage === 'declined' ? 'Peace of mind has its own value.' : 'You made it back.'; eyebrow = 'CHAPTER 02 · COMPLETE'; body = <><p>{g.stage === 'declined' ? 'You turned down the delivery. Tunde has another lead: Nurse Sade in Ikorodu needs someone she can trust.' : 'The package is delivered. Tunde mentions Nurse Sade in Ikorodu. She has questions about missing supplies—and a much bigger story.'}</p><div className="ending-stats"><span><strong>{g.lives}/9</strong>Lives remaining</span><span><strong>{money(g.money)}</strong>Your wallet</span></div><button className="primary" onClick={()=>useGame.getState().story('chapter3')}>Continue to The Price of Trust <ArrowUpRight size={18}/></button><button className="choice" onClick={()=>open(null)}>Explore first</button></>; }
  if (modal === 'inventory') { title = 'The things you carry.'; eyebrow = 'BACKPACK'; body = <><p>Ammo: {g.ammo??0} · Bodyguards: {g.guards??0}/3</p><div className="item-grid">{g.inventory.map((item,i) => <button className="item" key={`${item}-${i}`} onClick={()=>useGame.getState().useItem(item)}><Backpack size={24} /><strong>{item}</strong><small>{item==='Mystery gift box'?'Tap to open':item==='First-aid kit'?'Tap to heal':item.endsWith('key')&&item!=='Apartment key'?'Tap to drive':item === 'Sealed package' ? 'Mission item' : 'Equipment'}</small></button>)}</div><p className="muted">Tap vehicle keys to drive, gift boxes to open, or first-aid kits to heal.</p></>; }
  if (modal === 'journal') { title = 'Your life, one choice at a time.'; eyebrow = 'FIVE-CHAPTER CAMPAIGN'; body = <>{['A fresh start','The midnight delivery','The price of trust','Survival costs money','Nine chances'].map((name,i)=><div className="journal-entry" key={name}><span>0{i+1}</span><div><strong>{name}</strong><p>{i+1<g.chapter?'Completed':i+1===g.chapter?objectives[g.stage][2]:'Continue your story to unlock this chapter.'}</p></div></div>)}{['complete','declined'].includes(g.stage)&&<button className="primary" onClick={()=>useGame.getState().story('chapter3')}>Continue to chapter 3 <ArrowUpRight size={17}/></button>}<h3>Your growing skills</h3><div className="skill-row"><span>Awareness <b>{g.skills.awareness}</b></span><span>Fitness <b>{g.skills.fitness}</b></span><span>Communication <b>{g.skills.communication}</b></span></div><p>Life Echoes: {g.echoes} · Wanted: {g.wanted??0}/5</p></>; }
  if (modal === 'map') { title = 'The city is yours to explore.'; eyebrow = 'SIX DISTRICTS · LAGOS'; body = <><CityMap onSelect={()=>open('transport')}/><p>Motor parks sit at the south end of each neighborhood. Board there to see your trip from the driving camera.</p></>; }
  if (modal === 'help') { title = 'Nine lives. Make them count.'; eyebrow = 'HOW TO PLAY'; body = <><p>Explore your street, meet Tunde, and choose your path through The Midnight Delivery. Keep your health, fullness, hydration, and energy up.</p><div className="help-rows"><span>Move <kbd>W A S D / ↑ ↓ ← →</kbd></span><span>Run <kbd>SHIFT</kbd></span><span>Interact <kbd>E</kbd></span><span>Map / Backpack <kbd>M / I</kbd></span><span>Pause / Close <kbd>ESC</kbd></span></div><p>On touch screens, drag the joystick and use the action buttons. Portrait and landscape layouts adjust automatically. Nine deaths end your campaign. Save before you leave.</p></>; }
  if (modal === 'settings') { title = 'Make yourself comfortable.'; eyebrow = 'SETTINGS'; body = <><label className="setting">Graphics quality<select value={useGame.getState().quality} onChange={e => useGame.setState({ quality: e.target.value as 'low' | 'high' })}><option value="high">High · Shadows</option><option value="low">Low · Battery friendly</option></select></label><p>Portrait and landscape are both supported. Rotate your device at any time.</p><button className="choice" onClick={() => void useGame.getState().save()}><span><strong>Save campaign</strong><small>Local IndexedDB save · No account needed</small></span><Save size={18} /></button><button className="choice" onClick={() => open('restart')}><span><strong>New campaign</strong><small>Reset lives, money, skills, and story</small></span><RotateCcw size={18} /></button></>; }
  if (modal === 'restart') { title = 'Begin a new story?'; eyebrow = 'NEW CAMPAIGN'; body = <><p>Your current campaign and local save will be replaced. You will start again with nine lives and ₦5,000.</p><button className="primary" onClick={() => useGame.getState().reset()}>Start fresh <RotateCcw size={17} /></button><button className="choice" onClick={() => open('settings')}>Keep my campaign</button></>; }
  return <div className="modal-shade" onClick={() => g.lives && open(null)}><div ref={ref} className="dialog" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Tab') { const items = ref.current?.querySelectorAll<HTMLElement>('button, select, [tabindex="0"]'); if (!items?.length) return; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && (document.activeElement === last || document.activeElement === ref.current)) { e.preventDefault(); first.focus(); } } }}><div className="dialog-top"><span className="eyebrow">{eyebrow}</span>{g.lives > 0 && <button className="icon-button" aria-label="Close dialog" onClick={() => open(null)}><X size={20} /></button>}</div><h2>{title}</h2>{body}</div></div>;
}
export default function App() {
  const g = useGame(s => s.game), paused = useGame(s => s.paused), modal = useGame(s => s.modal), ready = useGame(s => s.ready), toast = useGame(s => s.toast), saved = useGame(s => s.saved); const [running, setRunning] = useState(false);const [booting,setBooting]=useState(true);const district=districtAt(...g.position);
  useEffect(()=>{const began=Date.now();const finish=()=>setTimeout(()=>setBooting(false),Math.max(0,1600-(Date.now()-began)));window.addEventListener('9lives-world-ready',finish,{once:true});const fallback=setTimeout(()=>setBooting(false),8000);return()=>{window.removeEventListener('9lives-world-ready',finish);clearTimeout(fallback);};},[]);
  useEffect(() => { void useGame.getState().load(); const tick = setInterval(() => useGame.getState().tick(), 3000); const autosave = setInterval(() => { if (useGame.getState().ready && !useGame.getState().saved) void useGame.getState().save(); }, 60000);
    const down = (e: KeyboardEvent) => { if (e.target instanceof HTMLElement&&e.target.matches('select,input,textarea') || e.ctrlKey || e.metaKey || e.altKey) return; const s = useGame.getState();if(!s.game.created)return; const k = e.key.toLowerCase(); if (['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)) e.preventDefault(); controls.keys.add(k); if (e.repeat) return; if (k === 'escape') { if (s.modal && s.game.lives > 0) s.open(null); else if (!s.modal) useGame.setState({ paused: !s.paused }); } if (s.modal || !s.ready || s.ride) return; if (k === 'e') interact(); if (k === 'm') s.open('city'); if (k === 'i') s.open('inventory'); if (k === 'h') s.open('help'); };
    const up = (e: KeyboardEvent) => controls.keys.delete(e.key.toLowerCase()); const blur = () => { controls.keys.clear(); controls.x = 0; controls.z = 0; controls.running = false; setRunning(false); }; const visibility = () => { if (document.hidden) { blur(); if (useGame.getState().ready) void useGame.getState().save(); } };
    window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('blur', blur); document.addEventListener('visibilitychange', visibility);
    return () => { clearInterval(tick); clearInterval(autosave); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('blur', blur); document.removeEventListener('visibilitychange', visibility); };
  }, []);
  const obj = objectives[g.stage]; const time = `${Math.floor(g.minutes / 60).toString().padStart(2, '0')}:${(g.minutes % 60).toString().padStart(2, '0')}`;
  const toggleRun = () => { controls.running = !running; setRunning(!running); };
  return <main className="app"><header className="topbar"><a className="brand" href="./" aria-label="9LIVES home"><span className="brand-symbol">9<span>✦</span></span><span>9LIVES<small>A LIFE WORTH LIVING</small></span></a><div className="chapter-heading"><span className="tiny-dot" /> LAGOS IS YOURS <span className="build-label">EXPANDED WORLD</span></div><nav aria-label="Game tools"><button aria-label="City map" onClick={()=>useGame.getState().open('city')}><Map size={18}/><span>City</span></button><button onClick={() => useGame.getState().open('journal')}><BookOpen size={17} /><span>Journal</span></button><button onClick={() => useGame.getState().open('inventory')}><Backpack size={17} /><span>Backpack</span></button><button aria-label="Multiplayer coming soon" onClick={()=>useGame.getState().open('multiplayer')}><Users size={18}/><span>Coming soon</span></button><button aria-label="Customize character" onClick={()=>useGame.getState().open('profile')}><UserRound size={18}/></button><button aria-label="How to play" onClick={() => useGame.getState().open('help')}><CircleHelp size={19} /></button><button aria-label="Settings" onClick={() => useGame.getState().open('settings')}><Settings size={19} /></button></nav></header>
    <section className="viewport" aria-label="Playable 3D neighborhood"><WorldBoundary><Suspense fallback={<LoadingScreen compact/>}>{ready && <World />}</Suspense></WorldBoundary><div className="scene-vignette" /><WorldLabels /><TravelHUD/>
      <div className="left-hud"><section className="life-panel panel"><div className="panel-heading"><span className="eyebrow">YOUR NINE CHANCES</span><span className="life-count">{g.lives}<small>/ 9</small></span></div><div className="hearts">{Array.from({ length: 9 }, (_, i) => <Heart key={i} size={19} fill={i < g.lives ? 'currentColor' : 'none'} className={i < g.lives ? '' : 'lost-heart'} />)}</div><div className="wallet"><span>Cash on hand</span><strong>{money(g.money)}</strong></div></section>
      <section className="stats-panel panel"><div className="panel-heading"><span className="eyebrow">KEEP YOURSELF GOING</span><span className="status-live"><span />STABLE</span></div>{([{ key: 'health', name: 'Health', icon: Heart, color: '#a8ba95' }, { key: 'energy', name: 'Energy', icon: Zap, color: '#e2be78' }, { key: 'hunger', name: 'Fullness', icon: Utensils, color: '#cfa77d' }, { key: 'hydration', name: 'Hydration', icon: Droplets, color: '#8bafb0' }, { key: 'stress', name: 'Stress', icon: Sparkles, color: '#b49ba8' }] as const).map(({ key, name, icon: Icon, color }) => <div className="stat" key={key}><div className="stat-label"><Icon size={14} style={{ color }} /><span>{name}</span><strong>{Math.round(g.stats[key])}<small>%</small></strong></div><div className="stat-track"><div style={{ width: `${g.stats[key]}%`, background: color }} /></div></div>)}</section>
      <section className="quest-panel panel"><div className="quest-eyebrow"><span className="quest-diamond">◇</span> CHAPTER {g.chapter.toString().padStart(2, '0')}</div><h1>{obj[0]}</h1><div className="objective"><span className="objective-dot" /><strong>{obj[1]}</strong></div><p>{obj[2]}</p><button className="text-button" onClick={() => useGame.getState().open('journal')}>Open journal <ArrowUpRight size={14} /></button></section></div>
      <div className="right-hud"><div className="day-clock"><Sun size={19} /><span>DAY {g.day}<strong>{time}</strong></span></div><button className="map-panel panel" onClick={() => useGame.getState().open('city')} aria-label="Open city map"><div className="map-title"><span>{district.name.toUpperCase()}</span><Expand size={13} /></div><MiniMap /><div className="map-bottom"><span className="tiny-dot" />6 connected districts</div></button><div className="scene-tools"><button className="round-button" aria-label="Toggle fullscreen" onClick={() => { const p = document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen?.(); void p?.catch(() => useGame.getState().notify('Fullscreen is unavailable. Rotate your device for landscape.')); }}><Expand size={17} /></button><button className="round-button" aria-label={paused ? 'Resume' : 'Pause'} onClick={() => useGame.setState({ paused: !paused })}>{paused ? <Play size={17} /> : <Pause size={17} />}</button></div></div>
      <div className="location-pill"><span className="tiny-dot" /><span>{district.name}, Lagos</span><small>{g.character?.name??'Guest'} · WANTED {g.wanted??0}/5</small></div>
      <div className="bottom-controls"><Joystick /><div className="interaction-hint"><span className="hint-icon"><Compass size={20} /></span><div><strong>Your next chapter is around the corner.</strong><small>Explore the street. Talk to the people who know you.</small></div></div><div className="action-controls"><button className={`run-button ${running ? 'active' : ''}`} aria-pressed={running} onClick={toggleRun}><Footprints size={20} /><span>Run</span><kbd>SHIFT</kbd></button><button className="interact-button" onClick={interact}><span className="interact-icon">↗</span><span>Interact</span><kbd>E</kbd></button></div></div>
      {paused && !modal && <div className="pause-overlay"><span className="eyebrow">TAKE A BREATHER</span><h2>The city can wait.</h2><button className="primary" onClick={() => useGame.setState({ paused: false })}><Play size={17} /> Resume your story</button><button className="text-button" onClick={() => void useGame.getState().save()}><Save size={16} /> Save progress</button></div>}
      {g.lives === 0 && !modal && <div className="pause-overlay"><h2>Your campaign has ended.</h2><button className="primary" onClick={() => useGame.getState().open('death')}>View your story</button></div>}
      {toast && <div className="toast" role="status"><ShieldCheck size={17} />{toast}</div>}
    </section><footer className="footer"><span><span className="tiny-dot" /> EVERY CHOICE LEAVES A MARK.</span><button onClick={() => void useGame.getState().save()}><ShieldCheck size={13} /> {saved ? 'Progress saved locally' : 'Save progress'} <span className="footer-separator">/</span> {g.lives} lives to make it count</button><span className="footer-version">9LIVES · v0.2</span></footer><Dialog />{ready&&!g.created&&!booting&&<div className="onboarding-shade"><div className="onboarding-card"><CharacterCreator onDone={()=>useGame.getState().notify('Welcome to Lagos. Find Tunde, or open the city map and explore.')}/></div></div>}{booting&&<div className="boot-screen"><LoadingScreen/></div>}</main>;
}
