import {useThree} from '@react-three/fiber';
import {useEffect} from 'react';
import {Plane,Raycaster,Vector2,Vector3} from 'three';
import {controls,useGame} from './game';
import {navigateTo,stopNavigation} from './navigation';
export const cameraControl = { yaw: .665, pitch: .72, distance: 34, insideYaw: 0, insidePitch: 0,sensitivity:1 };
export function CameraGestures() {
  const canvas=useThree(s=>s.gl.domElement),camera=useThree(s=>s.camera),scene=useThree(s=>s.scene);
  useEffect(()=>{
    type Pointer={x:number;y:number;startX:number;startY:number;mode:'move'|'camera'|'tap';moved:boolean;active:boolean;timer?:ReturnType<typeof setTimeout>};
    const points=new Map<number,Pointer>();let previousDistance=0;const ray=new Raycaster(),point=new Vector3(),plane=new Plane(new Vector3(0,1,0),0);
    const joystick=(p:Pointer,visible:boolean)=>window.dispatchEvent(new CustomEvent('9lives-joystick',{detail:{visible,x:p.startX,y:p.startY,dx:controls.x*34,dy:controls.z*34}}));
    const active=()=>{const s=useGame.getState();return s.ready&&s.game.created&&s.game.lives>0&&!s.modal&&!s.paused&&!s.game.captivity;};
    const activate=(p:Pointer)=>{if(!active())return;p.active=true;p.moved=true;stopNavigation();joystick(p,true);};
    const tap=(x:number,y:number)=>{if(!active())return;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new Vector2((x-rect.left)/rect.width*2-1,1-(y-rect.top)/rect.height*2),camera);const hits=ray.intersectObjects(scene.children,true);for(const hit of hits){let o=hit.object,visible=true,interactive=false;for(let n:typeof o|null=o;n;n=n.parent){visible&&=n.visible;interactive||=!!n.userData.interactive;}if(!visible)continue;if(interactive)return;break;}if(ray.ray.intersectPlane(plane,point))navigateTo([point.x,point.z]);};
    const down=(e:PointerEvent)=>{if(!active())return;if(e.pointerType==='mouse'&&e.button!==0&&e.button!==2)return;const r=canvas.getBoundingClientRect(),movement=e.pointerType!=='mouse'&&e.clientX-r.left<r.width*controls.touchZone&&e.clientY-r.top>r.height*.4&&!useGame.getState().ride;const p:Pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,mode:movement?'move':e.pointerType==='mouse'&&e.button===0?'tap':'camera',moved:false,active:false};if(p.mode==='move'&&[...points.values()].some(p=>p.mode==='move'))return;canvas.setPointerCapture(e.pointerId);points.set(e.pointerId,p);previousDistance=0;if(p.mode==='move')p.timer=setTimeout(()=>activate(p),180);if([...points.values()].filter(p=>p.mode==='camera').length>1)[...points.values()].forEach(p=>{if(p.mode==='camera')p.moved=true;});};
    const move=(e:PointerEvent)=>{const p=points.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;const total=Math.hypot(p.x-p.startX,p.y-p.startY);if(p.mode==='move'){if(!p.active&&total>9){clearTimeout(p.timer);activate(p);}if(p.active){let x=p.x-p.startX,z=p.y-p.startY,n=Math.hypot(x,z);if(n>34){x*=34/n;z*=34/n;}controls.x=x/34;controls.z=z/34;joystick(p,true);}return;}if(p.mode==='tap'){if(total>8)p.moved=true;return;}const cameras=[...points.values()].filter(p=>p.mode==='camera');if(cameras.length===2){const [a,b]=cameras,distance=Math.hypot(a.x-b.x,a.y-b.y);if(previousDistance&&distance>0)cameraControl.distance=Math.max(9,Math.min(65,cameraControl.distance*previousDistance/distance));previousDistance=distance;return;}if(total<6&&!p.moved)return;p.moved=true;const sensitivity=cameraControl.sensitivity,inside=useGame.getState().ride&&useGame.getState().passengerView;if(inside){cameraControl.insideYaw-=dx*.006*sensitivity;cameraControl.insidePitch=Math.max(-.65,Math.min(.65,cameraControl.insidePitch+dy*.004*sensitivity));}else{cameraControl.yaw-=dx*.006*sensitivity;cameraControl.pitch=Math.max(.25,Math.min(1.25,cameraControl.pitch+dy*.004*sensitivity));}};
    const release=(e:PointerEvent,cancel=false)=>{const p=points.get(e.pointerId);if(!p)return;clearTimeout(p.timer);if(p.mode==='move'){controls.x=controls.z=0;joystick(p,false);}if(!cancel&&!p.moved&&!p.active)tap(p.x,p.y);points.delete(e.pointerId);previousDistance=0;};const up=(e:PointerEvent)=>release(e),cancel=(e:PointerEvent)=>release(e,true);
    const reset=()=>{for(const p of points.values()){clearTimeout(p.timer);if(p.mode==='move')joystick(p,false);}points.clear();controls.x=controls.z=0;previousDistance=0;};const unsubscribe=useGame.subscribe((s,old)=>{if(s.modal!==old.modal||s.paused!==old.paused)reset();});
    const wheel=(e:WheelEvent)=>{e.preventDefault();cameraControl.distance=Math.max(9,Math.min(65,cameraControl.distance+e.deltaY*.025));};
    const menu=(e:Event)=>e.preventDefault();canvas.style.touchAction='none';canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',cancel);canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('contextmenu',menu);window.addEventListener('blur',reset);
    return()=>{unsubscribe();reset();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('lostpointercapture',cancel);canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('contextmenu',menu);window.removeEventListener('blur',reset);};
  },[canvas,camera,scene]);return null;
}
