import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Component,Suspense,useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Box3,Group,Vector3,MathUtils} from 'three';
import {RiggedPerson} from './GameModels';
import type {Character} from './game';
class PreviewBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function Turntable({character,rotation,onReady}:{character:Character;rotation:{yaw:number;dragging:boolean};onReady:()=>void}){const ref=useRef<Group>(null),camera=useThree(s=>s.camera),aspect=useThree(s=>s.size.width/Math.max(1,s.size.height)),bounds=useMemo(()=>new Box3(),[]),size=useMemo(()=>new Vector3(),[]),frames=useRef(0),height=useRef(2.4);
 useEffect(()=>{frames.current=0;height.current=2.4;onReady();},[character.model,character.height,character.build,onReady]);
 useFrame((_,dt)=>{if(!ref.current)return;if(!rotation.dragging)rotation.yaw+=dt*.18;ref.current.rotation.y=rotation.yaw;if(frames.current++<24){bounds.setFromObject(ref.current);bounds.getSize(size);height.current=Math.max(height.current,size.y);}const h=height.current,fov=MathUtils.degToRad(35),distance=h/2/Math.tan(fov/2)*1.18*Math.max(1,.7/aspect);camera.position.set(0,h*.51,distance);camera.lookAt(0,h*.48,0);});
 return <group ref={ref}><RiggedPerson character={character} preview/></group>;
}
function Fallback({character:c}:{character:Character}){return <svg viewBox="0 0 120 200" role="img" aria-label="Character appearance fallback"><ellipse cx="60" cy="189" rx="32" ry="6" fill="#14221a"/><path d="M40 118H57V180H38ZM64 118H81V180H65Z" fill={c.pants??'#33465b'}/><path d="M38 174H58V187H33ZM65 174H83L90 187H65Z" fill={c.shoes??'#eee7d4'}/><rect x="34" y="67" width="52" height="64" rx="8" fill={c.shirt}/><rect x="24" y="71" width="12" height="64" rx="6" fill={c.skin}/><rect x="84" y="71" width="12" height="64" rx="6" fill={c.skin}/><ellipse cx="60" cy="40" rx="24" ry="27" fill={c.skin}/><path d="M36 32Q32 9 60 11Q88 9 84 32L77 23H43Z" fill={c.hair}/><circle cx="51" cy="40" r="2" fill="#17221b"/><circle cx="69" cy="40" r="2" fill="#17221b"/></svg>;}
export default function CharacterPreview({character}:{character:Character}){const [ready,setReady]=useState(false),rotation=useRef({yaw:0,dragging:false}),last=useRef(0),onReady=useCallback(()=>setReady(true),[]);useEffect(()=>setReady(false),[character.model]);const fallback=<div className="preview-placeholder"><Fallback character={character}/></div>;
 return <div className="model-preview" aria-label="3D character preview; drag to turn" onPointerDown={e=>{rotation.current.dragging=true;last.current=e.clientX;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(rotation.current.dragging){rotation.current.yaw+=(e.clientX-last.current)*.012;last.current=e.clientX;}}} onPointerUp={()=>rotation.current.dragging=false} onPointerCancel={()=>rotation.current.dragging=false} onLostPointerCapture={()=>rotation.current.dragging=false}>{!ready&&fallback}<PreviewBoundary key={character.model} fallback={fallback}><Canvas camera={{position:[0,1.2,5],fov:35,near:.05,far:30}} dpr={[1,1.5]} gl={{antialias:true}}><ambientLight intensity={2}/><directionalLight position={[3,5,4]} intensity={3}/><Suspense fallback={null}><Turntable character={character} rotation={rotation.current} onReady={onReady}/></Suspense><mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[1.1,32]}/><meshStandardMaterial color="#354637"/></mesh></Canvas></PreviewBoundary><span className="preview-status">{ready?'Drag to turn':'Loading 3D appearance…'}</span></div>;
}
