import {useEffect,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import {Group} from 'three';
import {useGame,controls} from './game';
import {districts} from '../shared/city';
import {Person} from './SceneParts';
import {worldFree} from './spatial';
import {crowdBodies,stationaryBodies,steerCrowd,publishPlayerBody} from './crowd';
export function Crowds(){const refs=useRef<(Group|null)[]>([]),initialized=useRef(new Set<number>());useEffect(()=>()=>crowdBodies.clear(),[]);useFrame(({clock},dt)=>{const s=useGame.getState(),hour=s.game.minutes/60,free=worldFree(s.game,s.driving),fixed=stationaryBodies();refs.current.forEach((g,i)=>{if(!g)return;const id='crowd-'+i,d=districts[Math.floor(i/4)];g.visible=!s.game.interior&&hour>=6&&hour<23&&Math.hypot(d.x-controls.position[0],d.z-controls.position[1])<65;if(!g.visible){crowdBodies.delete(id);return;}const bodies=[...fixed,...crowdBodies.values(),publishPlayerBody()];if(!initialized.current.has(i)){for(let n=0;n<24;n++){const p:[number,number]=[d.x+(i%2?1:-1)*(4.6+Math.floor(i%4/2)*.8),d.z-9+i%4*4+n*.8];if(free(...p)&&bodies.every(b=>Math.hypot(p[0]-b.x,p[1]-b.z)>.9)){g.position.set(p[0],0,p[1]);initialized.current.add(i);break;}}}if(!initialized.current.has(i)){g.visible=false;crowdBodies.delete(id);return;}if(!s.modal&&!s.paused){const x=d.x+(i%2?1:-1)*(4.6+Math.floor(i%4/2)*.8),z=d.z+Math.sin(clock.elapsedTime*.035+i)*9,p=steerCrowd([g.position.x,g.position.z],[x,z],free,bodies,id,dt),dx=p[0]-g.position.x,dz=p[1]-g.position.z;g.position.set(p[0],0,p[1]);if(Math.hypot(dx,dz)>.001)g.rotation.y=Math.atan2(dx,dz);}crowdBodies.set(id,{id,x:g.position.x,z:g.position.z,radius:.36});});});return <>{districts.flatMap((d,j)=>Array.from({length:4},(_,i)=><group key={d.id+i} position={[d.x+(i%2?4.6:-4.6),0,d.z+i*3-6]} ref={g=>{refs.current[j*4+i]=g;}}><Person npc walking color={['#af7751','#748ca1','#a8aa77','#975f83'][i]}/></group>))}</>;}
