import {useEffect,useMemo,useRef} from 'react';
import {useFrame} from '@react-three/fiber';
import {Group} from 'three';
import {useGame,controls,defaultCharacter} from './game';
import {districtAt} from '../shared/city';
import {Person,Sign} from './SceneParts';
import {worldFree} from './spatial';
import {crowdBodies,stationaryBodies,steerCrowd,publishPlayerBody} from './crowd';
import {boardCitizen,citizens,createCitizens,npcTraffic,planCitizen,unboardCitizen} from './citizens';
import {enterpriseData,enterpriseOf} from './enterprise';
import {trafficClock} from './trafficState';
export function Crowds(){const seed=useGame(s=>s.game.seed),population=useMemo(()=>createCitizens(useGame.getState().game),[seed]),refs=useRef<(Group|null)[]>([]),elapsed=useRef(0),initialized=useRef(new Set<string>());
 useEffect(()=>{citizens.clear();population.forEach(c=>citizens.set(c.id,c));initialized.current.clear();npcTraffic.stops.clear();return()=>{citizens.clear();crowdBodies.clear();npcTraffic.stops.clear();};},[population]);
 useFrame((_,dt)=>{const s=useGame.getState(),g=s.game,e=enterpriseOf(g),free=worldFree(g,s.driving),fixed=stationaryBodies();if(!s.paused&&!s.modal&&!document.hidden)elapsed.current+=Math.min(dt,.05);population.forEach((c,i)=>{const group=refs.current[i];if(!group)return;const dead=e.npcHealth[c.id]===0;if(c.ride){const vehicle=trafficClock.cars.find(t=>t.id===c.ride!.vehicle&&!e.stolen.includes('traffic-'+t.id));if(vehicle){c.position=[vehicle.x,vehicle.z];const stop=npcTraffic.stops.get(vehicle.id);if(stop&&stop.time>0&&districtAt(vehicle.x,vehicle.z).id===c.ride.destination){const kind=vehicle.kind,receipt=`fare-${c.id}-${g.day}-${c.ride.from}-${c.ride.destination}`;if(unboardCitizen(c,[vehicle.x,vehicle.z],g)&&e.fleet[kind])s.enterpriseAction({action:'fleet-trip',vehicle:kind,receipt});}}else unboardCitizen(c,c.position,g);group.visible=false;crowdBodies.delete(c.id);return;}
 group.visible=!g.interior&&!dead&&Math.hypot(c.position[0]-controls.position[0],c.position[1]-controls.position[1])<60;if(!group.visible){crowdBodies.delete(c.id);return;}
 const bodies=[...fixed,...crowdBodies.values(),publishPlayerBody()];if(!initialized.current.has(c.id)){let found=false;for(let n=0;n<30;n++){const p:[number,number]=[c.position[0]+Math.floor(n/10)*.8,c.position[1]+n%10*.8];if(free(...p)&&bodies.every(b=>Math.hypot(p[0]-b.x,p[1]-b.z)>.9)){c.position=p;found=true;initialized.current.add(c.id);break;}}if(!found){group.visible=false;return;}}
 c.walked=false;if(!s.modal&&!s.paused&&!s.ride&&g.created&&!document.hidden){if(elapsed.current>=c.nextPlan&&!e.jail)planCitizen(c,g,elapsed.current);while(c.route.length&&Math.hypot(c.position[0]-c.route[0][0],c.position[1]-c.route[0][1])<.22)c.route.shift();if(c.route.length){const next=steerCrowd(c.position,c.route[0],free,bodies,c.id,dt),dx=next[0]-c.position[0],dz=next[1]-c.position[1];c.walked=Math.hypot(dx,dz)>.0001;c.blocked=c.walked?0:c.blocked+Math.min(dt,.05);c.position=next;if(c.walked)group.rotation.y=Math.atan2(dx,dz);if(c.blocked>2){c.nextPlan=0;c.blocked=0;}}
 if(c.activity.startsWith('shopping:')&&Math.hypot(c.position[0]-c.target[0],c.position[1]-c.target[1])<1.2){const id=c.activity.slice(9),b=e.businesses[id],key=`${c.id}|visit-${id}-${g.day}-${Math.floor(g.minutes/60)}`;if(b&&c.lastVisit!==key){c.lastVisit=key;const goods=Object.keys(enterpriseData.businesses[b.kind].goods).filter(kind=>(b.stock[kind]??0)>0),kind=goods[i%goods.length];s.enterpriseAction({action:'customer',id,kind,receipt:key});c.activity='browsing';c.nextPlan=elapsed.current+12;}}
 if(c.activity==='commuting'){const car=trafficClock.cars.find(v=>!e.stolen.includes('traffic-'+v.id)&&npcTraffic.stops.get(v.id)?.time&&Math.hypot(c.position[0]-v.x,c.position[1]-v.z)<6);if(car)boardCitizen(c,car.id,car.kind,g);}
 if(c.role==='thief'&&Math.hypot(c.position[0]-controls.position[0],c.position[1]-controls.position[1])<1.1&&Math.floor(g.minutes/60)>=17){const receipt=`pickpocket-${c.id}-${g.day}`;if(!e.receipts.includes(receipt))s.enterpriseAction({action:'npc-theft',id:c.id,receipt});}
 }
 if(c.activity==='sleeping'&&Math.hypot(c.position[0]-c.home[0],c.position[1]-c.home[1])<1.2)group.visible=false;group.position.set(c.position[0],0,c.position[1]);group.userData.walking=c.walked;crowdBodies.set(c.id,{id:c.id,x:c.position[0],z:c.position[1],radius:.36});});});
 return <>{population.map((c,i)=><group key={c.id} ref={g=>{refs.current[i]=g;}} userData={{interactive:true,citizen:c.id,walking:false}} position={[c.position[0],0,c.position[1]]} onClick={event=>{event.stopPropagation();if(Math.hypot(c.position[0]-controls.position[0],c.position[1]-controls.position[1])>4)return useGame.getState().notify(`Approach ${c.name} to talk.`);useGame.setState({selectedPlace:c.id});useGame.getState().open('npc');}}><Person npc walking character={{...defaultCharacter,...c.character,name:c.name}}/><Sign text={c.name} position={[0,2.2,0]} width={1.1}/></group>)}</>;
}
