import {useEffect,useRef,useState} from 'react';
import {useGame} from './game';
import {enterpriseData as data,enterpriseOf,newPlot,random,weather,validPlacement,type BlockKind,type EnterpriseCommand} from './enterprise';
import {parcels} from '../shared/property';
import {vehicles,type VehicleKind} from '../shared/city';
import {citizens,citizenGreeting} from './citizens';
import {inspectedVehicle,takeVehicle} from './vehicleInteractions';
import './enterprise.css';
const money=(v:number)=>`₦${Math.floor(v).toLocaleString()}`;
export const buildingGhost={id:'',kind:'wall' as BlockKind,x:0,z:0,y:0,rotation:0,visible:false};
export function EnterpriseUI(){const g=useGame(s=>s.game),modal=useGame(s=>s.modal),selected=useGame(s=>s.selectedPlace),open=useGame(s=>s.open),act=useGame(s=>s.enterpriseAction),e=enterpriseOf(g),[tab,setTab]=useState('build'),[plotId,setPlotId]=useState(''),[kind,setKind]=useState<BlockKind>('wall'),[business,setBusiness]=useState('provisions'),[crop,setCrop]=useState('maize'),[good,setGood]=useState('water'),[breed,setBreed]=useState(data.cattle[0]),[animal,setAnimal]=useState('broiler'),[role,setRole]=useState('cashier'),[amount,setAmount]=useState(10),[x,setX]=useState(0),[z,setZ]=useState(0),[y,setY]=useState(0),[rotation,setRotation]=useState(0),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(modal==='enterprise'){const owned=g.properties?.some(p=>p.id===selected);setPlotId(owned?selected:g.properties?.[0]?.id??'');if(selected==='jail'||e.jail)setTab('finance');else if(selected==='chase'||e.chase)setTab('chase');else if(selected==='school')setTab('career');else if(selected==='ade')setTab('career');}const before=document.activeElement as HTMLElement;ref.current?.focus();return()=>before?.focus();},[modal,selected]);
 useEffect(()=>{Object.assign(buildingGhost,{id:plotId,kind,x,z,y,rotation,visible:modal==='enterprise'&&tab==='build'});return()=>{buildingGhost.visible=false;};},[plotId,kind,x,z,y,rotation,modal,tab]);
 useEffect(()=>{if(modal!=='enterprise'||!e.chase)return;const timer=setInterval(()=>{if(!document.hidden&&!useGame.getState().paused)useGame.getState().enterpriseAction({action:'chase-step'});},1100);return()=>clearInterval(timer);},[modal,!!e.chase]);
 const currentBusiness=e.businesses[plotId];useEffect(()=>{if(currentBusiness)setGood(Object.keys(data.businesses[currentBusiness.kind].goods)[0]);},[plotId,currentBusiness?.kind]);
 if(!['enterprise','npc','vehicle-interaction'].includes(modal??''))return null;
 const p=e.plots[plotId]??newPlot(),parcel=parcels.find(p=>p.id===plotId),b=e.businesses[plotId],w=weather(g),command=(action:string,extra:Partial<EnterpriseCommand>={})=>act({action,id:plotId,amount,...extra}),button=(label:string,action:string,extra:Partial<EnterpriseCommand>={})=><button key={label} className="choice" onClick={()=>command(action,extra)}>{label}</button>,selector=(label:string,value:string,values:Record<string,{name:string}>|string[],change:(v:string)=>void)=><label>{label}<select value={value} onChange={event=>change(event.target.value)}>{Array.isArray(values)?values.map(v=><option key={v}>{v}</option>):Object.entries(values).map(([id,v])=><option key={id} value={id}>{v.name}</option>)}</select></label>;
 const preview={id:0,kind,x,z,y,rotation},valid=validPlacement(g,plotId,preview),size=parcel?.size??6,tiles=Array.from({length:size*size},(_,i)=>({x:i%size-Math.floor(size/2),z:Math.floor(i/size)-Math.floor(size/2)}));
 return <div className="modal-shade" onClick={()=>open(null)}><div className="dialog life-dialog enterprise-dialog" role="dialog" aria-modal="true" aria-label="Land and living city" tabIndex={-1} ref={ref} onClick={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==='Escape')open(null);if(event.key!=='Tab')return;const items=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!items?.length)return;const a=items[0],b=items[items.length-1];if(event.shiftKey&&(document.activeElement===a||document.activeElement===ref.current)){event.preventDefault();b.focus();}else if(!event.shiftKey&&document.activeElement===b){event.preventDefault();a.focus();}}}><div className="dialog-top"><span className="eyebrow">9LIVES · LIVING LAGOS</span><button aria-label="Close" onClick={()=>open(null)}>×</button></div>
 {modal==='vehicle-interaction'?<><h2>{inspectedVehicle?.moving?'Stop & interact':'Parked vehicle'}</h2><p>{inspectedVehicle&&vehicles[inspectedVehicle.kind].name}. Traffic is paused while this menu is open. Theft can fail: witnesses, security and awareness affect the attempt.</p><button className="choice" onClick={()=>takeVehicle('theft')}>Attempt vehicle theft</button><button className="choice" onClick={()=>takeVehicle('rob-vehicle')}>Rob NPC fare cash · dirty cash</button><button className="primary" onClick={()=>open(null)}>Leave safely</button></>:modal==='npc'?<><h2>{citizens.get(selected)?.name??'Neighbour'}</h2><p>{citizens.get(selected)?citizenGreeting(g,citizens.get(selected)!):'This neighbour has moved away.'}</p><button className="choice" onClick={()=>{open(null);useGame.getState().shoot(selected);}}>Aim equipped pistol at this NPC · safe zones protected</button><p>Activity: {citizens.get(selected)?.activity.split(':')[0]} · Role: {citizens.get(selected)?.role}</p>{button('Offer a shared outing · ₦500','social',{kind:citizens.get(selected)?.name})}<button className="choice" onClick={()=>{open(null);useGame.getState().notify('Neighbours choose work, shops and transport according to their needs and time of day.');}}>Ask about the neighbourhood</button></>:<><h2>Build a life that works.</h2><p className="season-note">{w.date} · {w.season} season · {w.flood?'Flood alert':w.storm?'Thunderstorm':w.rain?'Rain':w.harmattan?'Harmattan':'Clear'} · {w.blackout?'Power outage':'Power on'} · Cash {money(g.money)}</p><div className="enterprise-tabs">{['build','business','farm','livestock','finance','career','social','chase'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {['build','business','farm','livestock'].includes(tab)&&<label>Owned property<select value={plotId} onChange={event=>setPlotId(event.target.value)}>{g.properties?.map(p=><option key={p.id} value={p.id}>{parcels.find(a=>a.id===p.id)?.name}</option>)}</select></label>}
 {tab==='build'&&<><p>{size} × {size} plot · {p.blocks.length}/512 blocks · {p.registered?'Registered deed':'Unregistered deed'} · {['Mud','Block','Storey'][p.tier-1]} tier</p>{selector('Material',kind,data.blocks,v=>setKind(v as BlockKind))}<div className="build-coordinates">{[['X',x,setX],['Z',z,setZ],['Floor',y,setY],['Rotation',rotation,setRotation]].map(([label,n,set])=><label key={label as string}>{label as string}<input type="number" step="1" min={label==='Floor'||label==='Rotation'?0:-size/2} max={label==='Floor'?2:label==='Rotation'?3:size/2-1} value={n as number} onChange={event=>(set as (v:number)=>void)(Math.round(Number(event.target.value)))}/></label>)}</div><div className="build-grid" style={{gridTemplateColumns:`repeat(${size},1fr)`}} aria-label="Plot grid with placement preview">{tiles.map(t=>{const blocks=p.blocks.filter(b=>b.y===y&&b.x===t.x&&b.z===t.z),ghost=t.x===x&&t.z===z;return <button key={t.x+','+t.z} title={`Tile ${t.x}, ${t.z}${blocks.length?': '+blocks[0].kind:''}`} aria-label={`Tile ${t.x}, ${t.z}`} className={ghost?(valid?'ghost-valid':'ghost-invalid'):''} style={{background:blocks.length?data.blocks[blocks[0].kind].color:undefined}} onClick={()=>{setX(t.x);setZ(t.z);}}/>;})}</div><p>Gold/green preview: valid. Red: blocked. Keep the north entrance and centre escape corridor open.</p><button className="primary" disabled={!valid} onClick={()=>command('place',{kind,x,z,y,rotation})}>Place {data.blocks[kind].name} · {money(data.blocks[kind].cost)}</button>{button('Undo last edit','undo')}{button('Upgrade building tier','tier')}{button('Register deed at Lands Bureau · ₦1,000','register')}<details><summary>Placed blocks · demolish for 40% refund</summary>{p.blocks.map(block=><button className="choice" key={block.id} onClick={()=>command('demolish',{amount:block.id})}>{block.kind} · {block.x}, {block.z}, floor {block.y} · remove</button>)}</details><details><summary>Merge owned adjacent plots</summary>{g.properties?.filter(a=>a.id!==plotId).map(a=>button(parcels.find(p=>p.id===a.id)?.name??a.id,'merge',{kind:a.id}))}</details><button className="choice" onClick={()=>open('property-list')}>Buy more land / homes</button></>}
 {tab==='business'&&<>{selector('Business model',business,data.businesses,setBusiness)}{button('Configure this business','configure-business',{kind:business})}{b&&<><p>{data.businesses[b.kind].name} · {b.open?'Open':'Closed'} · Visitors {b.customers} · Revenue {money(b.earned)} · Reputation {Math.round(b.reputation)}</p>{selector('Product',good,Object.keys(data.businesses[b.kind].goods),setGood)}<label>Quantity / price<input type="number" min="1" step="1" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label>{button('Buy wholesale stock','restock',{kind:good})}{button('Set selling price','price',{kind:good})}{button(b.open?'Close business':'Open for NPC customers','toggle-business')}{Object.entries(b.stock).map(([id,n])=><p key={id}>{id}: {n} units · {money(b.prices[id]??0)}</p>)}{['flyers','radio','influencer'].map(kind=>button('Advertise: '+kind,'advertise',{kind}))}<p>Customers walk to the entrance, choose products and compare prices with rivals. Hours, stock and electricity matter.</p></>}{selector('Staff role',role,Object.keys(data.staff),setRole)}{button('Hire NPC staff · ₦1,000','hire',{kind:role})}<p>Weekly staff wages: {money(Object.entries(p.staff).reduce((n,[r,count])=>n+(count??0)*data.staff[r as keyof typeof data.staff]*7,0))}</p>{button('Generator fuel · seven outage-days','fuel-generator')}{button('Insurance · ₦2,000','insurance')}{(Object.keys(vehicles) as VehicleKind[]).map(vehicle=>button('Assign '+vehicles[vehicle].name+' to passenger service','fleet',{vehicle}))}</>}
 {tab==='farm'&&<>{button('Wait one supplied game day · ₦500','advance-days',{amount:1})}{button('Wait one supplied week · ₦3,500','advance-days',{amount:7})}{selector('Nigerian crop',crop,data.crops,setCrop)}<p>Germination {data.crops[crop as keyof typeof data.crops].germination} days · Harvest {data.crops[crop as keyof typeof data.crops].days} days. These are game-day growth models; cultivar and real growing conditions vary.</p>{button('Plant an empty crop bed','plant',{kind:crop})}{button('Water crops · ₦100','water')}{button('Fertilize soil · ₦300','fertilize')}{button('Treat pests · ₦300','pesticide')}{button('Harvest mature beds','harvest')}{button('Process cassava / palm / cocoa','process')}{['market','wholesaler','export'].map(kind=>button('Sell through '+kind,'sell-produce',{kind}))}<p>Soil {p.soil} · Borehole prevents dry-season dehydration. Wrong-season harvest gives no yield without a greenhouse.</p>{p.crops.map(c=><p key={c.id}>{data.crops[c.kind].name}: {c.age}/{data.crops[c.kind].days} days · Water {c.water} · Health {c.health} · Soil {c.soil}</p>)}{p.goods.map((a,i)=><p key={i}>{a.kind}: {a.quantity} · Quality {a.quality} · Harvest day {a.day}</p>)}</>}
 {tab==='livestock'&&<>{selector('Bird type',animal,data.birds,setAnimal)}<label>Birds / feed quantity<input type="number" min="1" max="5000" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label>{button('Buy chicks · ₦200 each','buy-birds',{kind:animal})}<p>{p.birds.count} {p.birds.kind} · Age {p.birds.age} days · Health {p.birds.health} · Feed {Math.floor(p.birds.feed)} kg</p>{button('Vaccinate flock · ₦1,000','vaccinate')}{button('Buy feed · ₦50/kg','feed')}{button('Sell mature birds','sell-animals',{kind:'birds'})}{selector('Cattle breed',breed,data.cattle,setBreed)}{button('Buy cattle · ₦12,000 each','buy-cattle',{kind:breed,amount:Math.min(20,amount)})}<p>{p.cattle.count} {p.cattle.breed} · Age {p.cattle.age} · Health {p.cattle.health}</p>{button('Veterinary care · ₦1,500','vet')}{button('Sell cattle','sell-animals',{kind:'cattle'})}{button('Hire herder','hire',{kind:'herder'})}<p>Build poultry houses/cowsheds first. Layers lay after maturity; manure enriches soil. Cattle need feed, water and security.</p></>}
 {tab==='finance'&&<><p>Dirty cash {money(e.dirty)} · Audit {e.audit} · Suspicion {Math.round(e.suspicion)}/100 · Tax {money(e.tax)} · Investments {money(e.investment)} · Ajo {money(e.cooperative)}</p><label>Amount<input type="number" min="1" step="1" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label>{button('Hide cash inside current house','stash')}{button('Withdraw hidden cash','unstash')}<p>Current home safe: {money(e.vaults[g.interior??'']?.money??0)}. Each house has separate hidden storage.</p>{g.interior&&<details><summary>Store / retrieve items</summary>{g.inventory.map((kind,i)=><div key={kind+i}>{button('Hide '+kind,'stash-item',{kind})}</div>)}{(e.vaults[g.interior]?.items??[]).map((kind,i)=><div key={kind+i}>{button('Retrieve '+kind,'retrieve-item',{kind})}</div>)}</details>}{button('Buy simulated investment','invest')}{button('Sell investment','cash-investment')}{button('Contribute to weekly ajo','ajo')}{button('Pay fictional business tax','tax')}{button('Collect insurance claim '+money(e.claims),'claim')}{button('Hire lawyer · ₦5,000','lawyer')}{button('Independent books audit · ₦2,500','clean-books')}<label>Front business<select value={plotId} onChange={event=>setPlotId(event.target.value)}>{Object.keys(e.businesses).map(id=><option key={id}>{id}</option>)}</select></label>{button('Inflate fictional revenue · raises audit risk','launder')}<p>Dirty cash is separate from your normal wallet. All values are fictional game currency.</p>{e.jail&&<div className="landlord-card"><h3>Detained</h3><p>Release hearing on game day {e.jail.until}. You have a free progression path.</p>{button('Pay bail '+money(e.jail.bail),'bail')}{button('Serve time and attend a hearing','hearing')}</div>}</>}
 {tab==='career'&&<>{selector('Career',business,['delivery','repair','shop','office','transport'],setBusiness)}{button('Apply for this career','career-apply',{kind:business})}{button('Attend interview','interview')}{button('Complete a work shift at a workplace','shift')}<p>{e.career.kind} · {e.career.employed?'Employed':'Not hired'} · Level {e.career.level} · Shifts {e.career.shifts}</p>{['mechanics','agriculture','commerce','computing'].map(kind=>button('Course + assessment: '+kind+' · ₦4,000','education',{kind}))}<p>Certificates: {e.education.join(', ')||'None'}</p>{['ade','clinic','witness','community'].map(id=>button(`${id}: mission step ${(e.quests[id]??0)+1}/3`,'sidequest',{id}))}</>}
 {tab==='social'&&<><p>Partner {e.social.partner||'None'} · Trust {e.social.trust} · {e.social.married?'Married':'Friendship'} · Family milestones {e.social.family}</p>{button('Spend time with Amara · ₦500','social',{kind:'Amara'})}{button('Support a family request · ₦1,000','family-help')}{selector('NPC greeting language',e.locale,['en','pcm','yo','ig','ha'],kind=>command('locale',{kind}))}<p>Your relationships grow through daily meetings and community missions.</p></>}
 {tab==='chase'&&<>{e.chase?<><p>Pursuit {e.chase.step}/20 · Health {e.chase.health} · Shield {e.chase.shield} · Score {e.chase.score}</p><p>Next hazard: lane {Math.floor(random(g.seed,e.chase.step+101)*3)+1}. Pickup: lane {Math.floor(random(g.seed,e.chase.step+211)*3)+1}.</p><div className="chase-track">{[0,1,2].map(lane=><button key={lane} className={e.chase?.lane===lane?'selected':''} onClick={()=>command('chase-lane',{amount:lane})}>{lane===e.chase?.lane?'YOU':'Lane '+(lane+1)}</button>)}</div>{button('Surrender safely','surrender')}<p>Switch lanes before the next hazard. Pickups and rewards occur only in this arcade event.</p></>:<p>No active pursuit. A failed vehicle theft can trigger an escape sequence.</p>}</>}
 {e.events.length>0&&<details><summary>City notifications</summary>{e.events.map((event,i)=><p key={i}>{event}</p>)}</details>}
 </>}
 </div></div>;
}
