import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh,validSave,useGame,controls} from './game';
import {enterpriseAction as act,enterpriseDay,enterpriseOf,migrateEnterprise,newPlot,validEnterprise,validPlacement,weather} from './enterprise';
import {simulate,effectiveProperty} from './simulation';
import {parcels,entrance} from '../shared/property';
import {boardCitizen,createCitizens,unboardCitizen,npcTraffic,citizens,planCitizen} from './citizens';
import {catalogAction} from './catalog';
import {worldFree,validRoomLayout} from './spatial';
const fixture=()=>{const g=fresh(),parcel=parcels.find(p=>!p.built&&p.size===16)!;g.properties!.push({id:parcel.id,kind:'land',level:1,furniture:[]});g.enterprise!.plots[parcel.id]={...newPlot(),registered:true};g.created=true;return {g,id:parcel.id,parcel};};
const step=(g:ReturnType<typeof fresh>,action:string,id:string,extra:Record<string,unknown>={})=>act(g,{action,id,...extra}).game;
test('grid edits charge once, reject overlaps and blocked entrances, undo and refund exactly',()=>{let {g,id}=fixture();const previous=structuredClone(g),money=g.money;g=step(g,'place',id,{kind:'wall',x:-3,z:-3,y:0,rotation:0});assert.equal(g.money,money-500);assert.equal(g.enterprise!.plots[id].blocks.length,1);assert.deepEqual(previous,fixture().g);assert.equal(step(g,'place',id,{kind:'wall',x:-3,z:-3,y:0,rotation:0}).money,g.money);assert.equal(validPlacement(g,id,{id:99,kind:'wall',x:0,z:7,y:0,rotation:0}),false);g=step(g,'demolish',id,{amount:1});assert.equal(g.money,money-300);g=step(g,'undo',id);assert.equal(g.money,money-500);assert.equal(g.enterprise!.plots[id].blocks.length,1);assert.ok(validSave(g));});
test('deed registration requires the Lands Bureau and refuses duplicate registration',()=>{let {g,id}=fixture();g.enterprise!.plots[id].registered=false;assert.equal(step(g,'register',id).money,g.money);g.position=[-15,18];g=step(g,'register',id);assert.equal(g.enterprise!.plots[id].registered,true);assert.equal(g.money,999000);assert.ok(g.inventory.includes('Registered deed: '+id));assert.equal(step(g,'register',id).money,g.money);});
test('customers consume stock and cash budgets once; high prices and blackout block sales',()=>{let {g,id}=fixture();g.minutes=12*60;g.seed=Array.from({length:100},(_,i)=>i).find(seed=>!weather({...g,seed}).blackout)!;g=step(g,'configure-business',id,{kind:'farm'});g=step(g,'restock',id,{kind:'produce',amount:4});g=step(g,'toggle-business',id);g.enterprise!.npcFunds['buyer']=5000;const before=g.money;g=step(g,'customer',id,{kind:'produce',receipt:'buyer|sale-1'});assert.equal(g.money,before+700);assert.equal(g.enterprise!.npcFunds.buyer,4300);assert.equal(g.enterprise!.businesses[id].stock.produce,3);assert.equal(step(g,'customer',id,{kind:'produce',receipt:'buyer|sale-1'}).money,g.money);g=step(g,'price',id,{kind:'produce',amount:5000});assert.equal(step(g,'customer',id,{kind:'produce',receipt:'buyer|sale-2'}).money,g.money);assert.ok(validSave(g));});
test('crop maturity, season, quality, spoilage and processing affect harvest revenue',()=>{let {g,id}=fixture();g=step(g,'place',id,{kind:'bed',x:-3,z:-3,y:0,rotation:0});g=step(g,'plant',id,{kind:'cassava'});const p=g.enterprise!.plots[id];p.crops[0].age=300;p.crops[0].health=100;p.crops[0].soil=100;g.enterprise!.startDate='2026-05-01';g=step(g,'harvest',id);assert.equal(g.enterprise!.plots[id].crops.length,0);assert.equal(g.enterprise!.plots[id].goods[0].quantity,10);g=step(g,'place',id,{kind:'warehouse',x:3,z:-3,y:0,rotation:0});g=step(g,'process',id);assert.equal(g.enterprise!.plots[id].goods[0].kind,'garri');const money=g.money;g=step(g,'sell-produce',id,{kind:'wholesaler'});assert.ok(g.money>money+20000);assert.equal(g.enterprise!.plots[id].goods.length,0);g.enterprise!.plots[id].goods=[{kind:'tomato',quantity:5,day:1,quality:80}];g=enterpriseDay({...g,day:4});assert.equal(g.enterprise!.plots[id].goods.length,0);});
test('livestock needs housing, feed and vaccination; staff quit after two unpaid wage cycles',()=>{let {g,id}=fixture();assert.equal(step(g,'buy-birds',id,{kind:'broiler',amount:50}).money,g.money);g=step(g,'place',id,{kind:'poultry',x:3,z:-3,y:0,rotation:0});g=step(g,'buy-birds',id,{kind:'layer',amount:50});g=step(g,'feed',id,{amount:100});g=step(g,'vaccinate',id);g.enterprise!.plots[id].birds.age=147;g=enterpriseDay({...g,day:2});assert.ok(g.enterprise!.plots[id].goods.some(a=>a.kind==='eggs'&&a.quantity>0));g=step(g,'hire',id,{kind:'cashier'});g.money=0;g=enterpriseDay({...g,day:15});assert.equal(Object.keys(g.enterprise!.plots[id].staff).length,0);assert.ok(g.money>=0);});
test('home safes conserve money and items and remain separate between houses',()=>{let g=fresh();g.interior='house-yaba';g.inventory.push('Mystery gift box');g=step(g,'stash','',{amount:5000});assert.equal(g.money,995000);g=step(g,'stash-item','',{kind:'Mystery gift box'});assert.equal(g.inventory.includes('Mystery gift box'),false);g=step(g,'retrieve-item','',{kind:'Mystery gift box'});g=step(g,'unstash','',{amount:5000});assert.equal(g.money,1000000);assert.equal(g.enterprise!.vaults['house-yaba'].money,0);assert.equal(step(g,'unstash','',{amount:1}).money,g.money);assert.ok(validSave(g));});
test('theft has both success and alarm outcomes and receipts prevent duplicate rewards',()=>{const successes:boolean[]=[];for(let seed=0;seed<35;seed++){let g=fresh();g.seed=seed;g.position=[4,12];const result=act(g,{action:'theft',id:'traffic-1',vehicle:'car',position:[2.3,12],witnesses:0,security:1,receipt:'theft-1'});g=result.game;successes.push(g.enterprise!.stolen.includes('traffic-1'));assert.equal(g.lives,9);if(g.enterprise!.chase)assert.equal(g.enterprise!.chase.health,3);const again=act(g,{action:'theft',id:'traffic-1',vehicle:'car',position:[2.3,12],receipt:'theft-1'});assert.deepEqual(again.game,g);assert.ok(validSave(g));}assert.ok(successes.some(Boolean)&&successes.some(a=>!a));});
test('citizens have varied identities and schedules, board by capacity, and unboard on safe separated spots',()=>{const g=fresh(),all=createCitizens(g);assert.ok(new Set(all.map(c=>c.name)).size>8);assert.ok(new Set(all.map(c=>c.character.model)).size>4);const c=all[0];citizens.clear();citizens.set(c.id,c);c.position=[-4,12];npcTraffic.stops.set(1,{time:5,cooldown:10,passengers:[]});assert.equal(boardCitizen(c,1,'bus',g),true);assert.equal(boardCitizen(c,1,'bus',g),false);assert.equal(unboardCitizen(c,[-2.3,-88],g),true);assert.equal(c.ride,undefined);assert.equal(boardCitizen(c,1,'bus',g),false);assert.ok(worldFree(g)(...c.position));planCitizen(c,{...g,minutes:1*60},20);assert.equal(c.activity,'sleeping');citizens.clear();npcTraffic.stops.clear();});
test('fleet trips have idempotent fare payments and money laundering triggers staged audit and a free hearing',()=>{let {g,id}=fixture();g.inventory.push('Bus key');g=step(g,'hire',id,{kind:'driver'});g=step(g,'fleet',id,{vehicle:'bus'});const before=g.money;g=step(g,'fleet-trip',id,{vehicle:'bus',receipt:'trip-a'});assert.ok(g.money>before);assert.equal(step(g,'fleet-trip',id,{vehicle:'bus',receipt:'trip-a'}).money,g.money);g.enterprise!.suspicion=90;g=enterpriseDay({...g,day:2});assert.equal(g.enterprise!.audit,'invitation');g=enterpriseDay({...g,day:3});assert.equal(g.enterprise!.audit,'frozen');g=enterpriseDay({...g,day:4});assert.equal(g.enterprise!.audit,'raid');assert.ok(g.enterprise!.jail);g.money=0;g=step(g,'hearing','');assert.equal(g.enterprise!.jail,undefined);assert.equal(g.lives,9);});
test('chase preview deterministically permits escape; rewards cannot be repeated after completion',()=>{let g=fresh();g.enterprise!.chase={lane:1,step:0,health:3,score:0,shield:0,multiplier:1};for(let i=0;i<20;i++){const before=structuredClone(g);for(let lane=0;lane<3;lane++){const candidate=step(step(before,'chase-lane','',{amount:lane}),'chase-step','');if(!candidate.enterprise!.jail&&(candidate.enterprise!.chase?.health??3)>=3){g=candidate;break;}}}assert.equal(g.enterprise!.chase,undefined);assert.ok(g.inventory.includes('Mystery gift box'));assert.ok(g.money<=1002500);assert.equal(step(g,'chase-step','').money,g.money);});
test('catalogue purchases have gameplay effects and room layout rejects trapped occupants',()=>{let g=catalogAction(fresh(),'bread').game;const hunger=g.stats.hunger;g=catalogAction(g,'Bread',true).game;assert.ok(g.stats.hunger>hunger);assert.equal(g.inventory.includes('Bread'),false);g=catalogAction(g,'shirt').game;g=catalogAction(g,'Ankara shirt',true).game;assert.equal(g.character!.shirt,'#ba7853');assert.equal(validRoomLayout({id:'house-yaba',kind:'house',level:1,furniture:['bed'],placements:{bed:{x:0,z:0,rotation:0}}}),false);assert.ok(validSave(g));});
test('malformed nested enterprise saves fail safely and old campaigns remain valid',()=>{const g=fresh();assert.ok(validEnterprise(g.enterprise));for(const corrupt of [null,{...g.enterprise,dirty:-1},{...g.enterprise,plots:{bad:newPlot()}},{...g.enterprise,npcFunds:{a:NaN}},{...g.enterprise,vaults:{a:{money:Infinity,items:[]}}}])assert.equal(validSave({...g,enterprise:corrupt}),false);const {enterprise,...old}=g;assert.equal(validSave(old),true);assert.ok(parcels.length>50);});

test('parking moves the driver out of the saved vehicle collider without moving the vehicle',()=>{const g=fresh();g.inventory.push('Car key');useGame.setState({game:g,driving:'car',modal:null});controls.position=[0,6];useGame.getState().park();const state=useGame.getState();assert.equal(state.driving,null);assert.deepEqual(state.game.sim!.garage.car!.parked,[0,6]);assert.ok(worldFree(state.game)(...controls.position));assert.notDeepEqual(controls.position,[0,6]);});

test('resale returns hidden belongings and removes construction, enterprise income and deeds',()=>{let {g,id}=fixture();g=step(g,'place',id,{kind:'shop',x:3,z:-3,y:0,rotation:0});assert.equal(effectiveProperty(g,id)?.kind,'shop');g=step(g,'configure-business',id,{kind:'phone'});g.enterprise!.vaults[id]={money:1500,items:['Bread']};g.inventory.push('Registered deed: '+id);const before=g.money;g=simulate(g,'sell-property',id).game;assert.ok(g.money>before+1500);assert.ok(g.inventory.includes('Bread'));assert.equal(g.inventory.includes('Registered deed: '+id),false);assert.equal(g.enterprise!.businesses[id],undefined);assert.equal(g.enterprise!.plots[id],undefined);assert.equal(g.enterprise!.vaults[id],undefined);assert.equal(effectiveProperty(g,id),undefined);assert.ok(validSave(g));});

test('legacy businesses migrate to visit-based stock and existing homes retain registration',()=>{const {enterprise,...old}=fresh();old.sim!.businesses['house-yaba']={stock:9,staff:2,open:true,earned:3000};const g=migrateEnterprise(old);assert.equal(g.enterprise!.businesses['house-yaba'].stock.water,9);assert.equal(g.enterprise!.businesses['house-yaba'].earned,3000);assert.equal(g.enterprise!.plots['house-yaba'].staff.cashier,2);assert.equal(g.enterprise!.plots['house-yaba'].registered,true);assert.equal(g.money,old.money);assert.ok(validSave(g));});

test('hired citizens walk to their assigned business and tenants return to the leased house',()=>{const {g,id,parcel}=fixture(),c=createCitizens(g)[0];g.enterprise!.plots[id].staff.cashier=1;g.sim!.tenants[id]={rent:1000,dueDay:8};planCitizen(c,{...g,minutes:12*60},1);assert.equal(c.activity,'working as cashier');assert.ok(Math.hypot(c.target[0]-entrance(parcel)[0],c.target[1]-entrance(parcel)[1])<2);planCitizen(c,{...g,minutes:23*60},2);assert.deepEqual(c.home,entrance(parcel));assert.equal(c.activity,'sleeping');});
