import {useFrame} from '@react-three/fiber';
import {useMemo,useRef} from 'react';
import {Group,Mesh} from 'three';
import {useGame,controls} from './game';
import {enterpriseData as data,enterpriseOf,weather,blockBounds} from './enterprise';
import {parcels} from '../shared/property';
import {Box,Person,Sign} from './SceneParts';
import {buildingGhost} from './EnterpriseUI';
import {inspectVehicle} from './vehicleInteractions';
import {districts} from '../shared/city';
export function ExpandedWorld(){const g=useGame(s=>s.game),e=enterpriseOf(g),ghost=useRef<Group>(null),water=useRef<Mesh>(null),trees=useMemo(()=>Array.from({length:45},(_,i)=>({x:40+i%9*2.3,z:-68-Math.floor(i/9)*3,h:2+i%3})),[]);useFrame(({clock})=>{const preview=buildingGhost,p=parcels.find(p=>p.id===preview.id);if(ghost.current){ghost.current.visible=preview.visible&&!!p;if(p){const spec=data.blocks[preview.kind];ghost.current.scale.set(spec.w,spec.h/1.6,spec.d);ghost.current.position.set(p.x+preview.x,preview.y*2.5+spec.h/2,p.z+preview.z);ghost.current.rotation.y=preview.rotation*Math.PI/2;}}if(water.current)water.current.position.y=.01+Math.sin(clock.elapsedTime*.7)*.015;});
 if(g.interior)return null;
 return <><mesh ref={water} position={[0,.01,-60]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[280,10]}/><meshStandardMaterial color="#438b97" roughness={.15} metalness={.45} transparent opacity={.95}/></mesh>{[-100,0,100].map(x=><group key={x} position={[x,0,-60]}><Box p={[0,.03,0]} s={[10,.16,10]} color="#738176"/>{[-5,5].flatMap(side=>[-4,-2,0,2,4].map(z=><Box key={side+','+z} p={[side,.7,z]} s={[.12,1.4,.12]} color="#b1ad98"/>))}{[-5,5].map(side=><Box key={side} p={[side,1.35,0]} s={[.15,.15,10]} color="#c7c4ad"/>)}<Sign text="LAGOON BRIDGE" position={[3,2,4]} width={3}/></group>)}{trees.filter(t=>Math.hypot(t.x-g.position[0],t.z-g.position[1])<65).map((t,i)=><group key={i} position={[t.x,0,t.z]}><Box p={[0,t.h/2,0]} s={[.3,t.h,.3]} color="#70543e"/><mesh position={[0,t.h,0]}><icosahedronGeometry args={[1.8,1]}/><meshStandardMaterial color={i%2?'#376646':'#5d7944'}/></mesh></group>)}
 {Object.entries(e.plots).filter(([id])=>{const p=parcels.find(p=>p.id===id);return p&&Math.hypot(p.x-g.position[0],p.z-g.position[1])<72;}).map(([id,p])=>{const parcel=parcels.find(a=>a.id===id)!;return <group key={id} position={[parcel.x,0,parcel.z]}>{p.blocks.map(b=>{const spec=data.blocks[b.kind];return <group key={b.id} position={[b.x,b.y*2.5,b.z]} rotation={[0,b.rotation*Math.PI/2,0]}><Box p={[0,spec.h/2,0]} s={[spec.w,spec.h,spec.d]} color={spec.color}/>{b.kind==='lamp'&&<pointLight position={[0,2.5,0]} intensity={2} distance={6} color="#f5db97"/>}{b.kind==='shop'&&<Sign text={e.businesses[id]?data.businesses[e.businesses[id].kind].name:'YOUR SHOP'} position={[0,2,spec.d/2+.05]} width={3}/>}</group>;})}{p.crops.map(c=>{const bed=p.blocks.find(a=>a.id===c.bed);if(!bed)return null;const height=.2+Math.min(1,c.age/data.crops[c.kind].days)*1.2;return <group key={c.id} position={[bed.x,0,bed.z]}>{[-.5,.5].flatMap(x=>[-.5,.5].map(z=><Box key={x+','+z} p={[x,height/2,z]} s={[.15,height,.15]} color={c.health>40?'#7b994d':'#9d895f'}/>))}</group>;})}{Array.from({length:Math.min(8,p.birds.count)},(_,i)=><group key={'bird'+i} position={[-2+i%4*.5,0,2+Math.floor(i/4)*.5]}><Box p={[0,.2,0]} s={[.3,.35,.4]} color="#e4ddba"/><Box p={[0,.4,.15]} s={[.16,.2,.18]} color="#caac6e"/></group>)}{Array.from({length:Math.min(4,p.cattle.count)},(_,i)=><group key={'cow'+i} position={[3,0,-2+i*1.3]}><Box p={[0,.8,0]} s={[.7,.75,1.3]} color="#b9b0a2"/>{[-.25,.25].flatMap(x=>[-.45,.45].map(z=><Box key={x+','+z} p={[x,.35,z]} s={[.12,.7,.12]} color="#6e665b"/>))}<Box p={[0,1.1,.8]} s={[.5,.5,.45]} color="#a18c75"/></group>)}{Object.values(p.staff).some(n=>n&&n>0)&&<group position={[0,0,(parcel.size??6)/2+1]}><Person npc color="#708f7a"/><Sign text="STAFF" position={[0,2.1,0]} width={1.5}/></group>}</group>;})}
 {districts.map(d=>['car','bike','keke'].map((kind,i)=>{const id=`public-${d.id}-${kind}`,x=d.x+14+i*3,z=d.z+18;if(e.stolen.includes(id))return null;return <group key={id} position={[x,0,z]} userData={{interactive:true}} onClick={event=>{event.stopPropagation();inspectVehicle(id,kind as 'car'|'bike'|'keke',[x,z]);}}><Box p={[0,.6,0]} s={[kind==='car'?1.7:.8,.8,kind==='car'?3.4:2]} color={['#a27859','#729388','#c1a34f'][i]}/><Sign text="PARKED" position={[0,1.8,0]} width={1.5}/></group>;}))}
 {weather(g).flood&&<mesh rotation={[-Math.PI/2,0,0]} position={[controls.position[0],.06,controls.position[1]]}><circleGeometry args={[12,24]}/><meshStandardMaterial color="#779ea1" transparent opacity={.2} roughness={.12}/></mesh>}
 <group ref={ghost} visible={false}><mesh><boxGeometry args={[1,1.6,1]}/><meshBasicMaterial color="#d4d78a" transparent opacity={.4} wireframe/></mesh></group></>;
}
