import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, BusFront, CarFront, Gift, MapPin, Shield, Users, X, Bike, Cross, Radio, Sparkles } from 'lucide-react';
import { districts, districtAt, locations, shopItems, vehicles, type DistrictId, type VehicleKind } from '../shared/city';
import { defaultCharacter, useGame, type Character } from './game';
const cash=(n:number)=>`₦${n.toLocaleString()}`;
export const expandedModals = ['city','transport','hospital','police','efcc','garage','community','security','story','finale','multiplayer','profile','equipment','account'];
export const iconFor = (kind:VehicleKind) => kind==='bus'?<BusFront size={24}/>:kind==='bike'?<Bike size={24}/>:<CarFront size={24}/>;
export function LoadingScreen({compact=false}:{compact?:boolean}) { return <div className={`animated-loader ${compact?'compact':''}`}><div className="loader-logo">9<span>✦</span></div><span className="eyebrow">NINE LIVES. ONE CITY.</span><h2>Your next life is loading.</h2><div className="loader-city"><span className="tower t1"/><span className="tower t2"/><span className="tower t3"/><span className="tower t4"/><span className="tower t5"/><div className="loader-vehicle"><BusFront size={37}/></div><div className="loader-road"/></div><div className="loader-progress"><span/></div><p>Building the city · Preparing your story</p><small>Stay off the road. Lagos traffic doesn’t wait.</small></div>; }
function CharacterPortrait({character:c}:{character:Character}) { return <svg viewBox="0 0 170 230" className="character-portrait" aria-label={`${c.gender} character preview`}><ellipse cx="85" cy="211" rx="45" ry="9" fill="#09160d" opacity=".4"/><path d="M61 146H82V202H60ZM89 146H109L111 202H90Z" fill="#455c4b"/><path d="M60 198H83V211H55ZM89 198H112L119 211H89Z" fill="#e2dfc9"/><rect x="43" y="94" width="16" height="67" rx="8" fill={c.skin}/><rect x="111" y="94" width="16" height="67" rx="8" fill={c.skin}/><path d={c.gender==='female'?'M57 87Q85 80 113 87L107 118L115 150H55L63 118Z':'M57 87Q85 80 113 87V149H57Z'} fill={c.shirt}/><rect x="75" y="70" width="20" height="22" fill={c.skin}/>{c.hairstyle==='braids'&&<path d="M56 46H112V93H99V66H68V93H55Z" fill={c.hair}/>}<ellipse cx="85" cy="53" rx="29" ry="32" fill={c.skin}/><path d="M57 46Q54 15 85 18Q114 15 114 46L101 30Q83 39 67 30Z" fill={c.hair}/>{c.hairstyle==='afro'&&<ellipse cx="85" cy="25" rx="37" ry="24" fill={c.hair}/>}<circle cx="75" cy="53" r="2" fill="#18271b"/><circle cx="96" cy="53" r="2" fill="#18271b"/><path d="M78 67Q85 72 92 67" stroke="#302c23" strokeWidth="2" fill="none"/></svg>; }
export function CharacterCreator({onDone,edit=false}:{onDone:()=>void;edit?:boolean}) {
  const [c,setC]=useState<Character>(useGame.getState().game.character??defaultCharacter);const [error,setError]=useState('');
  const finish=(e:FormEvent)=>{e.preventDefault();if(!c.name.trim())return setError('Give your character a name.');useGame.getState().update(g=>({...g,character:{...c,name:c.name.trim()},created:true}));void useGame.getState().save();onDone();};
  return <form className="creator" onSubmit={finish}><div className="creator-preview"><div className="preview-orbit"/><CharacterPortrait character={c}/><span className="eyebrow">{c.name || 'YOUR NEXT CHAPTER'}</span><small>Every life starts with you.</small></div><div className="creator-fields"><span className="eyebrow">{edit?'YOUR CHARACTER':'WELCOME TO 9LIVES'}</span><h2>{edit?'Make it your own.':'Who will you become?'}</h2><p>Six neighborhoods. Nine chances. A life shaped by your choices.</p><label>Your name<input value={c.name} maxLength={24} required onChange={e=>setC({...c,name:e.target.value})}/></label><div className="gender-options"><button type="button" className={c.gender==='male'?'selected':''} onClick={()=>setC({...c,gender:'male'})}>Male</button><button type="button" className={c.gender==='female'?'selected':''} onClick={()=>setC({...c,gender:'female'})}>Female</button></div><div className="customization-row"><label>Skin tone<input type="color" value={c.skin} onChange={e=>setC({...c,skin:e.target.value})}/></label><label>Clothing<input type="color" value={c.shirt} onChange={e=>setC({...c,shirt:e.target.value})}/></label><label>Hair<input type="color" value={c.hair} onChange={e=>setC({...c,hair:e.target.value})}/></label></div><label>Hairstyle<select value={c.hairstyle} onChange={e=>setC({...c,hairstyle:e.target.value as Character['hairstyle']})}><option value="short">Short</option><option value="afro">Afro</option><option value="braids">Braids</option></select></label><details className="optional-email"><summary>Add an email (optional)</summary><label>Email<input type="email" value={c.email} maxLength={254} onChange={e=>setC({...c,email:e.target.value})} placeholder="You can leave this empty"/></label><small>Saved with this device’s profile. Online accounts are coming soon.</small></details>{error&&<p role="alert">{error}</p>}<button className="primary" type="submit">{edit?'Save appearance':'Play as guest'} <ArrowRight size={17}/></button><small className="guest-note">No account or email required. Your progress saves on this device.</small></div></form>;
}
export function CityMap({onSelect}:{onSelect?:(d:DistrictId)=>void}) { const g=useGame(s=>s.game), current=districtAt(...g.position);return <><svg className="city-map" viewBox="0 0 320 230" role="img" aria-label="Map of six connected Lagos districts"><rect width="320" height="230" rx="10" fill="#21382b"/><path d="M50 36V190M160 36V190M270 36V190M36 69H285M36 174H285" stroke="#667d63" strokeWidth="11"/><path d="M50 36V190M160 36V190M270 36V190M36 69H285M36 174H285" stroke="#b9c4a1" strokeWidth="1" strokeDasharray="4 7"/>{districts.map(d=>{const x=160+d.x*1.1,y=174+d.z*1.05;return <g key={d.id} role="button" tabIndex={0} aria-label={`Select ${d.name}`} onClick={()=>onSelect?.(d.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect?.(d.id);}} className="map-district"><circle cx={x} cy={y} r="17" fill={d.id===current.id?'#d7bd81':'#314b37'} stroke="#b8c69f"/><text x={x} y={y+4} textAnchor="middle" fill={d.id===current.id?'#263b28':'#d3dfbf'} fontSize="11">{d.id===current.id?'◆':'⌂'}</text><text x={x} y={y+30} textAnchor="middle" fill="#eee8ce" fontSize="9">{d.name}</text></g>;})}<circle cx={160+g.position[0]*1.1} cy={174+g.position[1]*1.05} r="3.5" fill="#f9dda1"/><text x="293" y="21" fill="#e5e8cb" fontSize="9">N ↑</text></svg><div className="district-list">{districts.map(d=><button key={d.id} onClick={()=>onSelect?.(d.id)}><MapPin size={15}/><span><strong>{d.name}</strong><small>{d.description}</small></span>{current.id===d.id&&<b>YOU</b>}</button>)}</div></>; }
export function TravelHUD(){const ride=useGame(s=>s.ride),driving=useGame(s=>s.driving);if(!ride&&!driving)return null;return <div className="travel-hud panel">{iconFor(ride?.kind??driving!)}<div><strong>{ride?`On the way to ${districts.find(d=>d.id===ride.destination)!.name}`:`Driving your ${vehicles[driving!].name}`}</strong><small>{ride?'Passenger driving view · Sit back and watch the city':'WASD / joystick to steer · Avoid traffic and pedestrians'}</small>{ride&&<div className="trip-track"><span style={{width:`${ride.progress*100}%`}}/></div>}</div>{ride&&<button onClick={()=>useGame.setState({passengerView:!useGame.getState().passengerView})}>Inside / outside</button>}{!ride&&<button onClick={()=>{useGame.setState({driving:null});useGame.getState().notify('Vehicle parked.');}}>Exit</button>}</div>;}
export function ExpandedDialog(){
  const modal=useGame(s=>s.modal)!,g=useGame(s=>s.game),open=useGame(s=>s.open),buy=useGame(s=>s.buy),story=useGame(s=>s.story);const [destination,setDestination]=useState<DistrictId>('ikorodu');const [kind,setKind]=useState<VehicleKind>('bus');const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.focus();return()=>previous?.focus();},[modal]);
  useEffect(()=>{const current=districtAt(...g.position);if(destination===current.id)setDestination(districts.find(d=>d.id!==current.id)!.id);},[g.position,destination]);
  let title='',subtitle='LAGOS, A CITY OF POSSIBILITIES',body:React.ReactNode=null;
  const option=(label:string,detail:string,onClick:()=>void)=><button className="choice" onClick={onClick}><span><strong>{label}</strong><small>{detail}</small></span><ArrowRight size={17}/></button>;
  if(modal==='city'){title='A bigger world awaits.';subtitle='SIX CONNECTED DISTRICTS';body=<><CityMap onSelect={d=>{setDestination(d);open('transport');}}/><p>Tap a district to plan a trip. Walk to a motor park to board a car, bus, okada, or keke. You can also walk or drive between neighborhoods.</p></>;}
  if(modal==='transport'){title='Where are we going?';subtitle='MOTOR PARK · BOARD & TRAVEL';const current=districtAt(...g.position);body=<><label className="setting">Destination<select value={destination} onChange={e=>setDestination(e.target.value as DistrictId)}>{districts.filter(d=>d.id!==current.id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="vehicle-options">{(Object.keys(vehicles) as VehicleKind[]).map(k=><button key={k} className={kind===k?'selected':''} onClick={()=>setKind(k)}>{iconFor(k)}<strong>{vehicles[k].name}</strong><small>{cash(vehicles[k].fare)}</small></button>)}</div><div className="risk-note"><BusFront size={18}/>Trips show a moving driving view. The fare is charged once when you board.</div><button className="primary" onClick={()=>useGame.getState().board(kind,destination)}>Board {vehicles[kind].name} · {cash(vehicles[kind].fare)} <ArrowRight size={17}/></button><p className="muted">You must be within 5 meters of a motor park. Nearest park: {current.name}, at the south end of its local street.</p></>;}
  if(modal==='hospital'){title='There’s still time to recover.';subtitle='HOSPITAL · SAFE ZONE';body=<><p>Treatment restores your health and establishes a safe respawn checkpoint. You can also help the hospital earn an honest wage.</p>{option('Get treated','₦1,800 · Restore health · Set checkpoint',()=>story('treat'))}{option('Help with a hospital shift','Earn ₦1,800 · 1 hour · Costs energy',()=>story('volunteer'))}</>;}
  if(modal==='police'){title='Actions have consequences.';subtitle='POLICE STATION · SAFE ZONE';body=<><p>Wanted level: {g.wanted??0}/5. Reporting evidence through the EFCC can clear your record. Assault and robbery in the future shared city will raise your wanted level.</p>{option('Settle your fine',`${cash((g.wanted??0)*1000)} · Clear wanted status`,()=>story('fine'))}{option('Find the EFCC office','Ikeja · Opposite side of the street',()=>{open(null);useGame.getState().notify('The EFCC office is on the east side of Ikeja’s local street.');})}</>;}
  if(modal==='efcc'){title='The truth needs a witness.';subtitle='FICTIONAL EFCC FIELD OFFICE';body=g.stage==='evidence'?<><div className="quote">“That ledger could expose the entire network. Help us make the case—or decide what your silence is worth.”</div>{option('Submit the evidence','₦5,000 witness payment · Clear wanted level · Community ending',()=>story('report'))}{option('Sell the ledger to the contact','₦8,000 · Wanted +3 · Different ending',()=>story('sell'))}</>:<p>The investigators need the evidence ledger. Follow Nurse Sade’s lead in Ikorodu after completing the Midnight Delivery.</p>;}
  if(modal==='garage'){title='Your own way through the city.';subtitle='MAINLAND MOTORS';body=<><p>Buy a vehicle, then use its key in your backpack to drive. WASD or the joystick steers; Shift increases speed.</p>{(Object.keys(vehicles) as VehicleKind[]).map(k=>option(vehicles[k].name,`${cash(vehicles[k].price)} · ${g.inventory.includes(vehicles[k].key)?'Already owned':'Permanent vehicle key'}`,()=>buy(k)))}</>;}
  if(modal==='security'){title='You don’t have to walk alone.';subtitle='LEKKI SECURITY';body=<><p>Hire up to three bodyguards. They follow you and reduce street ambush damage by 25% each. They cannot stop a traffic collision. Active guards: {g.guards??0}/3.</p>{option('Hire a bodyguard','₦3,000 · Permanent companion',()=>buy('guard'))}</>;}
  if(modal==='community'){title='A city is made of its people.';subtitle='MAINLAND COMMUNITY CENTER';body=<><p>There’s a welcome box with your name on it. Boxes can contain cash, equipment, a vehicle key, a bodyguard, or a life token. Open one from your backpack.</p>{option('Collect your welcome gift',(g.flags??[]).includes('community-gift')?'Already collected':'One free box per campaign',()=>story('community'))}{option('Buy a mystery gift box','₦800 · Random reward',()=>buy('gift'))}{option('Work together','Shared missions, gifting, and chat · Coming soon',()=>open('multiplayer'))}</>;}
  if(modal==='equipment'){title='Be ready for what comes next.';subtitle='SUPPLIES & EQUIPMENT';body=<><div className="shop-balance">Cash on hand <strong>{cash(g.money)}</strong></div>{shopItems.map(i=>option(i.name,`${cash(i.price)}${i.id==='gun'?' · PvP coming soon':i.id==='guard'?' · Follows & protects you':''}`,()=>buy(i.id)))}</>;}
  if(modal==='story'){const near=locations.filter(l=>l.type==='story').sort((a,b)=>Math.hypot(a.x-g.position[0],a.z-g.position[1])-Math.hypot(b.x-g.position[0],b.z-g.position[1]))[0];if(near.id==='amara-contact'){title='The price of trust.';subtitle='CHAPTER 03 · NURSE SADE';body=g.stage==='trust'?<><div className="quote">“People are disappearing from the records, not the streets. There’s a ledger at the riverfront depot. Bring it to light. We need someone we can trust.”</div>{option('Help Sade','Find the ledger at the Ikorodu riverfront depot',()=>story('sade'))}</>:<p>{g.stage==='ledger'?'The ledger is at the riverfront depot, north of the motor park.':'Complete your first delivery, then continue the story from your journal.'}</p>;}else if(near.id==='river'){title='What the river keeps.';subtitle='IKORODU · RIVERFRONT DEPOT';body=g.stage==='ledger'?<><p>A battered ledger sits in a locked crate. Sade’s key opens it. Names, payments, and missing supplies. This is the proof she was hoping for.</p>{option('Follow the stranger into the depot','Kidnapping trap · ₦3,000 ransom · 3-minute deadline or rescue',()=>story('kidnap'))}{option('Take the evidence ledger','Chapter 04 · Travel to the EFCC office in Ikeja',()=>story('ledger'))}</>:<p>You need Nurse Sade’s lead before you can open the crate.</p>;}else {title='Nine chances. One final choice.';subtitle='CHAPTER 05 · ISLAND LOGISTICS';body=g.stage==='contract'?<><p>{(g.flags??[]).includes('reported')?'Your help on the investigation opened a door. A legitimate logistics company offers you a fresh start.':'A lucrative contract arrives from an anonymous sponsor. Your choice in Ikeja follows you here.'}</p>{option('Take the final contract',(g.flags??[]).includes('reported')?'Earn ₦10,000 · Community ending':'Earn ₦6,000 · Wealth ending',()=>story('final'))}</>:<p>Finish the Ikorodu and Ikeja investigation to unlock this final opportunity.</p>;}}
  if(modal==='finale'){title=(g.flags??[]).includes('community-ending')?'A life bigger than yourself.':'A fortune with a shadow.';subtitle='FIVE CHAPTERS · YOUR LEGACY';body=<><div className="ending-stats"><span><strong>{g.lives}/9</strong>Lives protected</span><span><strong>{cash(g.money)}</strong>Your future</span></div><p>{(g.flags??[]).includes('community-ending')?'You chose your community, told the truth, and earned a legitimate future. Tunde and Sade will remember what you did.':'You chose the money. The city respects your success, but the people who trusted you will remember the price.'}</p><p>Keep exploring all six districts, own vehicles, work, and collect gifts. A new campaign lets you explore the other ending.</p><button className="primary" onClick={()=>{open(null);void useGame.getState().save();}}>Keep living <ArrowRight size={17}/></button></>;}
  if(modal==='multiplayer'){title='The city will be better together.';subtitle='SHARED CITY · COMING SOON';body=<><div className="coming-soon-banner"><Users size={32}/><strong>Multiplayer is not active yet</strong><span>Solo campaign is available now.</span></div><div className="future-features">{[[Users,'Real players & teams'],[Radio,'Live district chat'],[Shield,'Combat, robbery & bodyguards'],[Gift,'Player gifts & shared rewards']].map(([Icon,label])=><div key={label as string}>{typeof Icon!=='string'&&<Icon size={19}/>}<span>{label as string}</span><small>Coming soon</small></div>)}</div><p>Lethal attacks will transfer a life to the attacker. Exhausting all lives starts a one-hour break before a fresh campaign. No online server is contacted. Optional accounts and email-free guest access are prepared for the future multiplayer launch.</p></>;}
  if(modal==='account'){title='Keep your name in the city.';subtitle='OPTIONAL ACCOUNT · COMING SOON';body=<><p>Guest play will always be available. An optional username and password account can keep your identity when the shared city launches. Email is optional.</p><form className="account-preview" onSubmit={e=>e.preventDefault()}><label>Username<input autoComplete="username" minLength={3} maxLength={24} placeholder="Your player name"/></label><label>Password<input type="password" autoComplete="new-password" minLength={10} placeholder="At least 10 characters"/></label><label>Email (optional)<input type="email" autoComplete="email" placeholder="Leave blank to skip"/></label><button className="primary" disabled>Account sign-up coming soon</button></form><button className="choice" onClick={()=>open(null)}>Continue with my guest character</button></>;}
  if(modal==='profile'){title='';subtitle='YOUR GUEST PROFILE';body=<><CharacterCreator edit onDone={()=>open(null)}/><button className="choice" onClick={()=>open('account')}><span><strong>Optional online account</strong><small>Username + password · Email optional · Coming soon</small></span><ArrowRight size={17}/></button></>;}
  return <div className="modal-shade" onClick={()=>open(null)}><div className={`dialog expanded-dialog ${modal==='profile'?'profile-dialog':''}`} ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title||'Character customization'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('button,input,select,summary,[tabindex="0"]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}}}><div className="dialog-top"><span className="eyebrow">{subtitle}</span><button className="icon-button" aria-label="Close" onClick={()=>open(null)}><X size={20}/></button></div>{title&&<h2>{title}</h2>}{body}</div></div>;
}
