import {Component,Suspense,useEffect,useMemo,useRef,type ReactNode} from 'react';
import {useFrame,useLoader} from '@react-three/fiber';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {clone} from 'three/examples/jsm/utils/SkeletonUtils.js';
import {AnimationMixer,Box3,Mesh,MeshStandardMaterial,Vector3,type AnimationAction} from 'three';
import {controls,defaultCharacter,useGame,type Character} from './game';
class AssetBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
export function Asset({url,size,position=[0,0,0],rotation=0,fallback=null}:{url:string;size:[number,number,number];position?:[number,number,number];rotation?:number;fallback?:ReactNode}){return <AssetBoundary fallback={fallback}><Suspense fallback={fallback}><StaticAsset url={url} size={size} position={position} rotation={rotation}/></Suspense></AssetBoundary>;}
function StaticAsset({url,size,position,rotation}:{url:string;size:[number,number,number];position:[number,number,number];rotation:number}){const gltf=useLoader(GLTFLoader,url),scene=useMemo(()=>{const o=clone(gltf.scene),box=new Box3().setFromObject(o),v=box.getSize(new Vector3());o.scale.set(size[0]/Math.max(v.x,.01),size[1]/Math.max(v.y,.01),size[2]/Math.max(v.z,.01));const b=new Box3().setFromObject(o),c=b.getCenter(new Vector3());o.position.set(-c.x,-b.min.y,-c.z);o.traverse(n=>{if(n instanceof Mesh){n.castShadow=true;n.receiveShadow=true;}});return o;},[gltf,size[0],size[1],size[2]]);return <group position={position} rotation={[0,rotation,0]}><primitive object={scene} dispose={null}/></group>;}
export function RiggedPerson({character,walking=false,seated=false,npc=false,preview=false}:{character?:Character;walking?:boolean;seated?:boolean;npc?:boolean;preview?:boolean}){
 const c=character??defaultCharacter,url='/assets/models/'+(c.model&&/^character-[a-h]$/.test(c.model)?c.model:c.gender==='female'?'character-b':'character-a')+'.glb',gltf=useLoader(GLTFLoader,url);
 const object=useMemo(()=>{const o=clone(gltf.scene);o.traverse(n=>{if(n instanceof Mesh){const source=Array.isArray(n.material)?n.material[0]:n.material;const material=new MeshStandardMaterial({map:source.map,roughness:.7,color:n.name.includes('torso')?c.shirt:n.name.includes('leg')?c.pants??'#33465b':n.name.includes('head')?c.skin:'#ffffff'});n.material=material;n.castShadow=true;n.receiveShadow=true;}});const sample=new AnimationMixer(o),idle=gltf.animations.find(a=>a.name==='idle');if(idle){sample.clipAction(idle).play();sample.update(0);}const b=new Box3().setFromObject(o),size=b.getSize(new Vector3());const scale=1.9/Math.max(.1,size.y);o.scale.setScalar(scale);o.position.y=-b.min.y*scale;sample.stopAllAction();sample.uncacheRoot(o);return o;},[gltf,c.skin,c.shirt,c.pants]);
 const mixer=useMemo(()=>new AnimationMixer(object),[object]),actions=useMemo(()=>Object.fromEntries(gltf.animations.map(a=>[a.name,mixer.clipAction(a)])),[gltf,mixer]),current=useRef<AnimationAction|null>(null);
 useEffect(()=>()=>{mixer.stopAllAction();mixer.uncacheRoot(object);object.traverse(n=>{if(n instanceof Mesh&&!Array.isArray(n.material))n.material.dispose();});},[mixer,object]);
 useFrame((_,dt)=>{const g=useGame.getState(),moving=walking&&!g.paused&&!g.modal&&(controls.moving||Math.abs(controls.x)+Math.abs(controls.z)>.05||['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].some(k=>controls.keys.has(k)));const name=preview?'idle':seated?'sit':moving?controls.running?'sprint':'walk':npc&&walking?'walk':g.game.pose==='dance'?'emote-yes':g.game.pose==='eat'?'interact-right':'idle';const action=actions[name]??actions.idle;if(action&&action!==current.current){current.current?.fadeOut(.15);action.reset().fadeIn(.15).play();current.current=action;}if(preview||!g.paused)mixer.update(Math.min(dt,.1));});
 return <group scale={[(c.build??1),(c.height??1),1]}><primitive object={object} dispose={null}/><mesh position={[0,c.hairstyle==='afro'?1.84:1.79,0]} scale={c.hairstyle==='afro'?[1,1,1]:[1,.4,1]}><sphereGeometry args={[c.hairstyle==='afro'?.3:.23,12,8]}/><meshStandardMaterial color={c.hair}/></mesh>{c.hairstyle==='braids'&&[-.2,.2].map(x=><mesh key={x} position={[x,1.6,-.1]}><cylinderGeometry args={[.065,.055,.4,8]}/><meshStandardMaterial color={c.hair}/></mesh>)}{[-.14,.14].map(x=><mesh key={x} position={[x,.12,.08]}><boxGeometry args={[.23,.16,.38]}/><meshStandardMaterial color={c.shoes??'#eee7d4'}/></mesh>)}{c.accessory==='glasses'&&<mesh position={[0,1.63,.21]}><boxGeometry args={[.34,.065,.04]}/><meshStandardMaterial color="#1e2b35"/></mesh>}{c.accessory==='cap'&&<mesh position={[0,1.89,0]}><cylinderGeometry args={[.2,.23,.12,20]}/><meshStandardMaterial color={c.shirt}/></mesh>}</group>;
}
export function AnimatedPerson(props:{character?:Character;walking?:boolean;seated?:boolean;npc?:boolean;fallback:ReactNode}){return <AssetBoundary fallback={props.fallback}><Suspense fallback={props.fallback}><RiggedPerson {...props}/></Suspense></AssetBoundary>;}
