import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fresh, advance, loseLife, canMove, validSave, useGame } from './game';
import { districts, locations, trafficAt, vehicles, type VehicleKind } from '../shared/city';
test('simulation advances days and clamps all survival stats', () => { const g = fixture(); g.minutes = 1430; const next = advance(g, 30, { hunger: 300, energy: -300 }); assert.equal(next.day, 2); assert.equal(next.minutes, 20); assert.equal(next.stats.hunger, 100); assert.equal(next.stats.energy, 0); });
test('death retains skills and relationships, removes package and adds an echo', () => { const g = fixture(); g.inventory.push('Sealed package'); const next = loseLife(g); assert.equal(next.lives, 8); assert.equal(next.echoes, 1); assert.equal(next.money, 3800); assert.deepEqual(next.skills, g.skills); assert.deepEqual(next.relationships, g.relationships); assert.ok(!next.inventory.includes('Sealed package')); assert.ok(canMove(...next.position)); });
test('ninth death ends campaign and lives never become negative', () => { let g = fixture(); for (let i = 0; i < 12; i++) g = loseLife(g); assert.equal(g.lives, 0); });
test('buildings and district edges block movement', () => { assert.equal(canMove(-9, -4), false); assert.equal(canMove(150, 0), false); assert.equal(canMove(0, 6), true); });
test('malformed and incompatible saves are rejected', () => { assert.ok(validSave(fixture())); assert.ok(!validSave({ version: 1, lives: 9 })); assert.ok(!validSave({ ...fixture(), position: [100, 100] })); assert.ok(!validSave({ ...fixture(), stats: { ...fixture().stats, health: NaN } })); });
test('mission safe route pays once and removes package', () => { useGame.setState({ game: fixture(), toast: '' }); useGame.getState().action('talk'); useGame.getState().action('investigate'); useGame.getState().action('accept'); assert.equal(useGame.getState().game.money, 6000); assert.ok(useGame.getState().game.inventory.includes('Sealed package')); useGame.getState().action('safe'); const g = useGame.getState().game; assert.equal(g.money, 10000); assert.equal(g.stage, 'complete'); assert.equal(g.lives, 9); assert.ok(!g.inventory.includes('Sealed package')); useGame.getState().action('safe'); useGame.getState().action('accept'); assert.equal(useGame.getState().game.money, 10000); });
test('seeded risky handoff creates an echo which unlocks safe retry', () => { useGame.setState({ game: { ...fixture(), seed: 1, stage: 'offer' }, modal: 'offer' }); useGame.getState().action('accept'); useGame.getState().action('safe'); assert.equal(useGame.getState().game.stage, 'delivery'); useGame.getState().action('risk'); assert.equal(useGame.getState().game.lives, 8); assert.equal(useGame.getState().game.echoes, 1); assert.equal(useGame.getState().modal, 'death'); useGame.getState().action('accept'); useGame.getState().action('safe'); assert.equal(useGame.getState().game.stage, 'complete'); assert.equal(useGame.getState().game.lives, 8); });
test('missing named skill or relationship fields invalidate a save', () => { assert.equal(validSave({ ...fixture(), skills: { a: 1, b: 1, c: 1 } }), false); assert.equal(validSave({ ...fixture(), relationships: { a: 1, b: 1, c: 1 } }), false); });
test('all six districts have accessible terminals, hospitals and agencies are on the map',()=>{assert.equal(districts.length,6);for(const d of districts){const park=locations.find(l=>l.id===`terminal-${d.id}`)!;assert.ok(canMove(park.x,park.z));}assert.ok(locations.some(l=>l.type==='hospital'));assert.ok(locations.some(l=>l.type==='police'));assert.ok(locations.some(l=>l.type==='efcc'));});
test('all transport types charge once and arrive at Ikorodu; remote boarding is refused',()=>{for(const kind of Object.keys(vehicles) as VehicleKind[]){useGame.setState({game:{...fixture(),position:[-4,12]},ride:null});useGame.getState().board(kind,'ikorodu');assert.equal(useGame.getState().game.money,5000-vehicles[kind].fare);useGame.getState().board(kind,'ikorodu');assert.equal(useGame.getState().game.money,5000-vehicles[kind].fare);useGame.getState().arrive();assert.deepEqual(useGame.getState().game.position,[-4,-88]);assert.equal(useGame.getState().ride,null);}useGame.setState({game:fixture(),ride:null});useGame.getState().board('bus','ikorodu');assert.equal(useGame.getState().ride,null);});
test('purchases deduct cash, vehicle keys mount vehicles, gift boxes are consumed',()=>{useGame.setState({game:{...fixture(),money:30000},ride:null,driving:null});useGame.getState().buy('bike');assert.equal(useGame.getState().game.money,21000);useGame.getState().useItem('Bike key');assert.equal(useGame.getState().driving,'bike');useGame.getState().buy('gift');useGame.getState().useItem('Mystery gift box');const after=useGame.getState().game;assert.ok(after.money>=20200);assert.ok(!after.inventory.includes('Mystery gift box')||after.inventory.filter(i=>i==='Mystery gift box').length===1);assert.ok(validSave(after));});
test('traffic collisions consume a life while guards reduce ambush damage',()=>{useGame.setState({game:{...fixture(),guards:3},ride:null,driving:null});useGame.getState().damage(80,'Street ambush');assert.equal(useGame.getState().game.stats.health,80);useGame.getState().damage(100,'Traffic collision');assert.equal(useGame.getState().game.lives,8);assert.equal(useGame.getState().game.deathCause,'Traffic collision');const traffic=trafficAt(1234);assert.equal(traffic.length,18);assert.ok(traffic.every(t=>Number.isFinite(t.x)&&Number.isFinite(t.z)));});
test('five-chapter community branch rewards once and persists its ending',()=>{useGame.setState({game:{...fixture(),stage:'complete',chapter:3},ride:null,driving:null});for(const c of ['chapter3','sade','ledger','report','final'])useGame.getState().story(c);const g=useGame.getState().game;assert.equal(g.stage,'finale');assert.equal(g.chapter,5);assert.equal(g.money,20000);assert.ok(g.flags?.includes('community-ending'));useGame.getState().story('final');assert.equal(useGame.getState().game.money,20000);assert.ok(validSave(g));});

function fixture(){return {...fresh(),money:5000};}
