import {useFrame} from '@react-three/fiber';
import {useEffect,useRef} from 'react';
import {vehicleSize,type VehicleKind} from '../shared/city';
import {Group,Vector3} from 'three';
import {parcels,starterProperty,type Furniture} from '../shared/property';
import {controls,useGame} from './game';
import {Box,Sign,Person} from './SceneParts';
import {Asset} from './GameModels';
import {effectiveProperty} from './simulation';
import {cameraControl} from './camera';
export function PropertyWorld() {
  const properties=useGame(s=>s.game.properties)??[starterProperty()];
  return <>{parcels.filter(p=>p.id!=='house-yaba').map(p=>{const owned=properties.find(a=>a.id===p.id),kind=owned?.kind??(p.built?'house':'land');return <group key={p.id} position={[p.x,0,p.z]}>{kind==='land'?<><Box p={[0,.03,0]} s={[6,.08,6]} color="#9a8b62"/>{[-3,3].flatMap(x=>[-3,3].map(z=><Box key={`${x}-${z}`} p={[x,.4,z]} s={[.15,.8,.15]} color="#ede1b4"/>))}</>:<><Asset url={'/assets/models/'+(kind==='house'?'home-building-type-'+['a','c','e','g'][Math.abs(Math.round(p.x))%4]:'city-building-'+(kind==='club'?'d':kind==='church'?'f':'b'))+'.glb'} size={[6,3.8+(owned?.level??1)*.4,6]} fallback={<Box p={[0,2,0]} s={[6,4,6]} color="#b9ab8d"/>}/><Sign text={kind.toUpperCase()} position={[0,3.1,3.15]}/>{kind==='church'&&<><Box p={[0,4.8,0]} s={[.2,1.4,.2]} color="#eee4bb"/><Box p={[0,5,0]} s={[.8,.2,.2]} color="#eee4bb"/></>}</>}<Sign text={owned?'YOUR PROPERTY':'FOR SALE'} position={[0,1,4]} width={2.4}/></group>;})}</>;
}
export function propertyObstacles() {
  const state=useGame.getState(),properties=state.game.properties??[starterProperty()];const parked=Object.entries(state.game.sim?.garage??{}).filter(([k])=>k!==state.driving).map(([k,v])=>({x:v!.parked[0],z:v!.parked[1],w:vehicleSize(k as VehicleKind)[0]*2,d:vehicleSize(k as VehicleKind)[1]*2}));return [...parked,...parcels.filter(p=>p.id!=='house-yaba'&&(p.built||properties.some(a=>a.id===p.id&&a.kind!=='land'))).map(p=>({x:p.x,z:p.z,w:6.4,d:6.4}))];
}
export function Interior() {
  const g=useGame(s=>s.game),home=effectiveProperty(g,g.interior??'');const size=7+(home?.level??1);const x=g.position[0],z=g.position[1];
  const avatar=useRef<Group>(null),local=useRef<[number,number]>([0,0]),cam=useRef(new Vector3());
  useEffect(()=>{if(g.pose==='stand')local.current=[0,0];},[g.pose]);
  useFrame(({camera},dt)=>{if(!home)return;const radius=Math.min(18,cameraControl.distance*.4);cam.current.set(x+Math.sin(cameraControl.yaw)*radius,radius*Math.sin(cameraControl.pitch)+3,z+Math.cos(cameraControl.yaw)*radius);camera.position.lerp(cam.current,1-Math.exp(-dt*5));camera.lookAt(x,1,z);
    const s=useGame.getState();if(!avatar.current||s.paused||s.modal||g.pose&&g.pose!=='stand')return;
    const keys=controls.keys,sx=controls.x+(keys.has('d')?1:0)-(keys.has('a')?1:0),sz=controls.z+(keys.has('s')?1:0)-(keys.has('w')?1:0),speed=Math.min(dt,.05)*2;
    const dx=(sx*Math.cos(cameraControl.yaw)+sz*Math.sin(cameraControl.yaw))*speed,dz=(sz*Math.cos(cameraControl.yaw)-sx*Math.sin(cameraControl.yaw))*speed;
    const obstacles=[...(home.furniture.includes('sofa')?[{x:-2,z:0,w:2.4,d:1}]:[]),...(home.furniture.includes('bed')?[{x:2,z:-2,w:2.1,d:3}]:[]),...(home.furniture.includes('tv')?[{x:-2,z:2.7,w:2.6,d:.6}]:[]),...(home.furniture.includes('table')?[{x:1,z:2,w:1.6,d:1.4}]:[])];
    for(const [f,o] of [['sofa',obstacles.find(o=>o.x===-2&&o.z===0)],['bed',obstacles.find(o=>o.x===2&&o.z===-2)],['tv',obstacles.find(o=>o.x===-2&&o.z===2.7)],['table',obstacles.find(o=>o.x===1&&o.z===2)]] as const){const t=home.placements?.[f];if(t&&o){o.x=t.x;o.z=t.z;const w=o.w,d=o.d;o.w=Math.abs(Math.cos(t.rotation))*w+Math.abs(Math.sin(t.rotation))*d;o.d=Math.abs(Math.sin(t.rotation))*w+Math.abs(Math.cos(t.rotation))*d;}}
    obstacles.push(...(home.walls??[]).map(w=>({x:w.x,z:w.z,w:w.axis==='x'?w.length:.12,d:w.axis==='z'?w.length:.12})));
    const free=(a:number,b:number)=>Math.abs(a)<size/2-.5&&Math.abs(b)<size/2-.5&&!obstacles.some(o=>Math.abs(a-o.x)<o.w/2+.25&&Math.abs(b-o.z)<o.d/2+.25);
    if(free(local.current[0]+dx,local.current[1]))local.current[0]+=dx;if(free(local.current[0],local.current[1]+dz))local.current[1]+=dz;avatar.current.position.set(local.current[0],0,local.current[1]);if(Math.abs(dx)+Math.abs(dz)>.001)avatar.current.rotation.y=Math.atan2(dx,dz);
  });
  if(!home)return null;
  const transform=(f:Furniture,x:number,z:number)=>({position:[home.placements?.[f]?.x??x,0,home.placements?.[f]?.z??z] as [number,number,number],rotation:[0,home.placements?.[f]?.rotation??0,0] as [number,number,number]});
  const model=(name:string,size:[number,number,number])=><Asset url={'/assets/models/furniture/'+name+'.glb'} size={size}/>;
  const has=(f:Furniture)=>home.furniture.includes(f),act=(a:'sit'|'sleep'|'tv')=>useGame.getState().homeAction(a);
  return <group position={[x,0,z]}><Box p={[0,-.05,0]} s={[size,.1,size]} color="#ab8c65"/><Box p={[0,1.5,-size/2]} s={[size,3,.15]} color="#e2d9b9"/><Box p={[-size/2,1.5,0]} s={[.15,3,size]} color="#afbeaa"/><Sign text={home.kind==='house'?'HOME, SWEET HOME':home.kind.toUpperCase()} position={[0,2.3,-size/2+.1]} width={3}/>{has('sofa')&&<group {...transform('sofa',-2,0)} onClick={()=>act('sit')}><Box p={[0,.35,0]} s={[2.4,.55,1]} color="#718e78"/><Box p={[0,.85,-.4]} s={[2.4,.6,.2]} color="#597761"/>{[-1.1,1.1].map(x=><Box key={x} p={[x,.65,0]} s={[.2,.6,1]} color="#597761"/>)}</group>}{has('bed')&&<group {...transform('bed',2,-2)} onClick={()=>act('sleep')}>{model('bedDouble',[2.1,1,3])}</group>}{has('tv')&&<group {...transform('tv',-2,2.7)} onClick={()=>act('tv')}><Box p={[0,.4,0]} s={[2.6,.8,.6]} color="#645340"/><Box p={[0,1.2,0]} s={[2,.9,.1]} color="#202c2c"/><Box p={[0,1.2,-.07]} s={[1.8,.72,.02]} color={g.tv?'#7eb3c4':'#182522'}/>{g.tv&&<Sign text="LAGOS TONIGHT" position={[0,1.2,.07]} width={1.7}/>}</group>}{has('kitchen')&&<group {...transform('kitchen',-size/2+1,-size/2+1)}>{model('kitchenStove',[1,1.1,1])}<group position={[1.2,0,0]}>{model('kitchenFridge',[.8,2,1])}</group></group>}{has('table')&&<group {...transform('table',1,2)}><Box p={[0,.8,0]} s={[1.6,.13,1.4]} color="#886647"/><Box p={[0,.4,0]} s={[.3,.8,.3]} color="#886647"/></group>}{has('plant')&&<group {...transform('plant',size/2-1,size/2-1)}><Box p={[0,.25,0]} s={[.6,.5,.6]} color="#b98060"/><mesh position={[0,.9,0]}><icosahedronGeometry args={[.6,0]}/><meshStandardMaterial color="#5f8b55"/></mesh></group>}{(home.walls??[]).map((w,i)=><Box key={i} p={[w.x,1,w.z]} s={[w.axis==='x'?w.length:.12,2,w.axis==='z'?w.length:.12]} color="#d9c8aa"/>)}<group position={[size/2-1,0,-size/2+1]} onClick={()=>useGame.getState().simAction('bath')}>{model('shower',[1,2,1])}</group>{home.kind!=='house'&&<><Box p={[0,.5,-3]} s={[4,1,.8]} color={home.kind==='club'?'#59375e':'#886a42'}/><Sign text={home.kind==='club'?'DJ · OPEN SONGS':home.kind==='church'?'WELCOME · COMMUNITY':'CHECKOUT · STOCK & STAFF'} position={[0,2,-3]} width={4}/><group position={[2,0,1]}><Person npc color="#aa7952"/></group>{home.kind==='club'&&<><pointLight position={[0,2,0]} color="#da53ff" intensity={15}/><mesh position={[0,2.8,0]}><sphereGeometry args={[.35,16,16]}/><meshStandardMaterial color="#d5dce8" metalness={.9} roughness={.15}/></mesh></>}</>}<group ref={avatar} position={g.pose==='sleep'?[home.placements?.bed?.x??2,.95,home.placements?.bed?.z??-2]:g.pose==='sit'?[home.placements?.sofa?.x??-2,-.2,home.placements?.sofa?.z??0]:[0,0,0]} rotation={g.pose==='sleep'?[Math.PI/2,0,0]:[0,Math.PI,0]}><Person character={g.character} seated={g.pose==='sit'} walking={g.pose==='stand'}/></group></group>;
}
