import {useEffect,useRef,useState} from 'react';
import {useGame} from './game';
import {simOf,rentPrice,salePrice} from './simulation';
import {parcels,starterProperty,entrance} from '../shared/property';
import {districts,vehicles,type VehicleKind} from '../shared/city';
import {PeerPanel} from './PeerUI';
import {ClubPlayer} from './Music';
import './life.css';
export const lifeModals=['life','bank','jobs','wellbeing','phone','vehicle-care','club-music','peer','room-editor'];
const cash=(n:number)=>`₦${Math.floor(n).toLocaleString()}`;
export function PropertyExtras({id}:{id:string}){
 const g=useGame(s=>s.game),action=useGame(s=>s.simAction),open=useGame(s=>s.open),sim=simOf(g),owned=g.properties?.find(p=>p.id===id),lease=sim.leases.find(l=>l.id===id),parcel=parcels.find(p=>p.id===id);
 return <div className="property-extras">{!owned&&parcel?.built&&!lease&&<button className="choice" onClick={()=>action('rent',id)}>Rent home · {cash(rentPrice(id))}/week + two weeks deposit</button>}{lease&&<><p>Rent due day {lease.dueDay} · Arrears {cash(lease.arrears)} · Notices {lease.warnings}/3</p><button className="primary" onClick={()=>useGame.getState().propertyAction(id,'enter')}>Enter rented home</button><button className="choice" onClick={()=>action('pay-rent',id)}>Pay rent / arrears</button><button className="choice" onClick={()=>action('negotiate-rent',id)}>Speak to landlord · negotiate arrears</button><button className="choice" onClick={()=>action('leave-rental',id)}>End lease · recover remaining deposit</button></>}
 {owned&&owned.kind!=='land'&&<button className="primary" onClick={()=>useGame.getState().propertyAction(id,'enter')}>Enter {owned.kind}</button>}
 {owned&&<><button className="choice" onClick={()=>{if(window.confirm(`Sell this property for ${cash(salePrice(g,id))}, including furniture and improvements?`)){action('sell-property',id);open('property-list');}}}>Sell property · {cash(salePrice(g,id))}</button>{owned.kind==='house'&&<button className="choice" onClick={()=>action(sim.tenants[id]?'end-tenancy':'find-tenant',id)}>{sim.tenants[id]?'End tenancy':'Rent to a tenant · weekly income'}</button>}{owned.kind!=='land'&&<><button className="choice" onClick={()=>{useGame.setState({selectedPlace:id});open('room-editor');}}>Room builder & furniture placement</button>{owned.kind!=='house'&&<><p>Stock {sim.businesses[id]?.stock??0} · Staff {sim.businesses[id]?.staff??0} · Profit {cash(sim.businesses[id]?.earned??0)}</p>{['open-business','restock','hire-staff','close-business'].map(a=><button key={a} className="choice" onClick={()=>action(a,id)}>{a.replaceAll('-',' ')}{a==='restock'?' · ₦3,000':a==='hire-staff'?' · ₦2,000':''}</button>)}</>}</>}</>}
 </div>;
}
export function LifeHUD(){const g=useGame(s=>s.game),s=simOf(g);return <><button className="life-launch" onClick={()=>useGame.getState().open('life')}>Life & jobs</button>{s.job&&<div className="job-hud panel"><strong>{s.job.kind.toUpperCase()} · {cash(s.job.reward)}</strong><span>{s.job.kind==='delivery'||s.job.kind==='taxi'?s.job.stage===0?'Collect at a motor park':`Destination: ${districts.find(d=>d.id===s.job!.destination)?.name}`:s.job.kind==='repair'?['Loosen','Clean','Tighten'][s.job.stage]:['Water','Food','Medicine'][s.job.stage]}</span><button onClick={()=>useGame.getState().open('jobs')}>Task</button></div>}{g.interior&&<div className="home-activities">{['cook','bath','clean','exercise'].map(a=><button key={a} onClick={()=>useGame.getState().simAction(a)}>{a}</button>)}<button onClick={()=>useGame.getState().open('wellbeing')}>Storage & health</button>{g.properties?.find(p=>p.id===g.interior)?.kind==='club'&&<><button onClick={()=>useGame.getState().open('club-music')}>DJ booth · songs</button><button onClick={()=>useGame.getState().update(g=>({...g,pose:g.pose==='dance'?'stand':'dance'}))}>Dance</button></>}</div>}</>;}
export function LifeDialog(){
 const modal=useGame(s=>s.modal),g=useGame(s=>s.game),action=useGame(s=>s.simAction),open=useGame(s=>s.open),sim=simOf(g);const [amount,setAmount]=useState(10000),[selected,setSelected]=useState('bed'),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement;ref.current?.focus();return()=>before?.focus();},[modal]);if(!modal||!lifeModals.includes(modal))return null;
 const id=useGame.getState().selectedPlace==='home'?'house-yaba':useGame.getState().selectedPlace,p=g.properties?.find(p=>p.id===id);
 return <div className="modal-shade" onClick={()=>open(null)}><div ref={ref} tabIndex={-1} className="dialog life-dialog" role="dialog" aria-modal="true" aria-label="Life simulation" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key!=='Tab')return;const buttons=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea');if(!buttons?.length)return;const a=buttons[0],b=buttons[buttons.length-1];if(e.shiftKey&&(document.activeElement===a||document.activeElement===ref.current)){e.preventDefault();b.focus();}else if(!e.shiftKey&&(document.activeElement===b||document.activeElement===ref.current)){e.preventDefault();a.focus();}}}><div className="dialog-top"><span className="eyebrow">BUILD A LIFE · LAGOS</span><button onClick={()=>open(null)} aria-label="Close">✕</button></div>
 {modal==='life'&&<><h2>Your city. Your choices.</h2><div className="life-menu">{[['jobs','Careers & playable jobs'],['bank','Bank, loans & bills'],['property-list','Buy, sell & rent properties'],['wellbeing','Health, hygiene & storage'],['phone','Phone & landlord messages'],['vehicle-care','Fuel, repairs & parking'],['peer','Multiplayer · Coming soon'],['club-music','Music & club playlist'],['room-editor','Rooms & furniture'],['profile','Character studio']].map(([m,label])=><button key={m} className="choice" onClick={()=>open(m)}>{label}</button>)}</div><p>Business skill {sim.progress.business} · Survival skill {sim.progress.survival} · Reputation {sim.progress.reputation}/100</p></>}
 {modal==='bank'&&<><h2>Make your money work.</h2><div className="balance-grid"><span>Cash<strong>{cash(g.money)}</strong></span><span>Savings<strong>{cash(sim.bank)}</strong></span><span>Debt<strong>{cash(sim.debt)}</strong></span><span>Bills<strong>{cash(sim.bills)}</strong></span></div><label>Amount<input type="number" min="1" max="1000000" step="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{['deposit','withdraw','loan','repay'].map(a=><button className="choice" key={a} onClick={()=>action(a,'',amount)}>{a}</button>)}<p>Loans: maximum ₦100,000, 10% initial interest, due in seven game days. Overdue loans accrue 2% weekly.</p><button className="choice" onClick={()=>action('pay-bills')}>Pay household bills · {cash(sim.bills)}</button></>}
 {modal==='jobs'&&<><h2>Earn it through play.</h2>{!sim.job?['delivery','taxi','repair','shop'].map(a=><button key={a} className="choice" onClick={()=>action('start-job',a)}>{a==='delivery'?'Courier · collect and deliver between districts':a==='taxi'?'Taxi driver · own a car and transport a passenger':a==='repair'?'Mechanic · complete the repair sequence':'Shopkeeper · serve a customer order'}</button>):<><p>{sim.job.kind} · Step {sim.job.stage+1} · Reward {cash(sim.job.reward)}</p>{sim.job.kind==='repair'||sim.job.kind==='shop'?<div className="task-buttons">{(sim.job.kind==='repair'?['loosen','clean','tighten']:['water','food','medicine']).map(a=><button key={a} onClick={()=>action('job-step',a)}>{a}</button>)}</div>:<><p>{sim.job.stage===0?'Move to your current district motor park to collect.':`Drive or travel to ${districts.find(d=>d.id===sim.job!.destination)?.name} motor park to finish.`}</p><button className="primary" onClick={()=>action('job-step')}>{sim.job.stage===0?'Collect passenger / package':'Complete delivery'}</button></>}<button className="choice" onClick={()=>action('cancel-job')}>Cancel job</button></>}<h3>Community side missions</h3>{[['clinic','Hospital assistance'],['witness','Give a police witness statement'],['community','Help your community']].map(([id,label])=><button className="choice" key={id} onClick={()=>action('sidequest',id)}>{label} · visit location · ₦2,000</button>)}</>}
 {modal==='wellbeing'&&<><h2>Look after yourself.</h2><p>Stamina {Math.round(sim.stamina)} · Hygiene {sim.hygiene} · Home cleanliness {sim.cleanliness} · Injury {sim.injury} · Illness {sim.illness}</p><button className="choice" onClick={()=>action('treat-injury')}>Treat injuries and illness · ₦3,000</button><h3>Bodyguards</h3>{['protect','follow','stay'].map(a=><button key={a} className="choice" onClick={()=>action('guard-mode',a)}>{a}{sim.guardMode===a?' · selected':''}</button>)}<h3>Home storage</h3>{g.inventory.filter(i=>!i.endsWith('key')&&i!=='Phone').map((i,n)=><button key={i+n} className="choice" onClick={()=>action('store',i)}>Store {i}</button>)}{sim.stored.map((i,n)=><button key={i+n} className="choice" onClick={()=>action('retrieve',i)}>Retrieve {i}</button>)}</>}
 {modal==='phone'&&<><h2>Your phone.</h2>{sim.leases.map(l=><div className="landlord-card" key={l.id}><strong>Landlord · {parcels.find(p=>p.id===l.id)?.name}</strong><p>Due day {l.dueDay} · Arrears {cash(l.arrears)} · Notices {l.warnings}/3</p><button onClick={()=>action('pay-rent',l.id)}>Pay rent</button><button onClick={()=>action('negotiate-rent',l.id)}>Negotiate</button></div>)}{sim.messages.map((m,i)=><p className="phone-message" key={i}>{m}</p>)}</>}
 {modal==='vehicle-care'&&<><h2>Your garage.</h2>{(Object.keys(vehicles) as VehicleKind[]).filter(k=>g.inventory.includes(vehicles[k].key)).map(k=><div className="landlord-card" key={k}><strong>{vehicles[k].name}</strong><p>Fuel {Math.round(sim.garage[k]?.fuel??100)}% · Condition {Math.round(sim.garage[k]?.condition??100)}% · Parked {sim.garage[k]?.parked.join(', ')??'Ready to take out'}</p><button onClick={()=>action('fuel',k)}>Fuel · ₦2,000</button><button onClick={()=>action('repair-car',k)}>Repair · ₦4,000</button><button onClick={()=>useGame.getState().useItem(vehicles[k].key)}>Take out / park</button></div>)}<button className="choice" onClick={()=>open('garage')}>Buy a vehicle</button></>}
 {modal==='room-editor'&&<><h2>Make room for your life.</h2><label>Property<select value={id} onChange={e=>useGame.setState({selectedPlace:e.target.value})}>{(g.properties??[starterProperty()]).filter(p=>p.kind!=='land').map(p=><option key={p.id} value={p.id}>{parcels.find(a=>a.id===p.id)?.name}</option>)}</select></label>{p&&<><label>Furniture<select value={selected} onChange={e=>setSelected(e.target.value)}>{p.furniture.map(f=><option key={f} value={f}>{f}</option>)}</select></label>{['x','z','rotation'].map(axis=><label key={axis}>{axis}<input type="range" min={axis==='rotation'?0:-3} max={axis==='rotation'?6.28:3} step="0.1" value={p.placements?.[selected as keyof typeof p.placements]?.[axis as 'x']??0} onChange={e=>{const current=p.placements?.[selected as keyof typeof p.placements]??{x:0,z:0,rotation:0};useGame.getState().placeFurniture(id,selected as 'bed',axis==='x'?Number(e.target.value):current.x,axis==='z'?Number(e.target.value):current.z,axis==='rotation'?Number(e.target.value):current.rotation);}}/></label>)}<button className="choice" onClick={()=>action('add-wall',id)}>Build a room divider · ₦500</button><button className="choice" onClick={()=>action('remove-wall',id)}>Remove last divider</button><button className="primary" onClick={()=>{useGame.getState().propertyAction(id,'enter');open(null);}}>View inside</button></>}{(p?.walls??[]).map((wall,i)=><div className="landlord-card" key={i}><strong>Room wall {i+1}</strong>{(['x','z','length'] as const).map(axis=><label key={axis}>{axis}<input type="range" min={axis==='length'?.5:-3} max={axis==='length'?4:3} step=".1" value={wall[axis]} onChange={e=>{const value=Number(e.target.value);useGame.getState().update(g=>({...g,properties:g.properties?.map(prop=>prop.id===id?{...prop,walls:prop.walls?.map((w,n)=>n===i?{...w,[axis]:value}:w)}:prop)}));}}/></label>)}<button onClick={()=>useGame.getState().update(g=>({...g,properties:g.properties?.map(prop=>prop.id===id?{...prop,walls:prop.walls?.map((w,n)=>n===i?{...w,axis:w.axis==='x'?'z':'x'}:w)}:prop)}))}>Rotate wall</button></div>)}<p>Furniture positions and room dividers save with the property.</p></>}
 {modal==='club-music'&&<><h2>The Lagos listening room.</h2><ClubPlayer/></>}{modal==='peer'&&<PeerPanel/>}
 </div></div>;
}
