import { useEffect, useRef, useState } from 'react';
import { buildTypes, entrance, furnishings, parcels, starterProperty, type BuildKind, type Furniture } from '../shared/property';
import { useGame } from './game';
import {PropertyExtras} from './LifeUI';
import { Music } from './Music';
import './living.css';

import {cameraControl} from './camera';
export function LivingHUD() {
  const dialog=useRef<HTMLDivElement>(null);const g=useGame(s=>s.game),modal=useGame(s=>s.modal);const [stats,setStats]=useState(false),[now,setNow]=useState(Date.now());
  useEffect(()=>{if(g.lives)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[g.lives]);
  useEffect(()=>{const before=document.activeElement as HTMLElement;dialog.current?.focus();return()=>before?.focus();},[modal]);
  const id=useGame(s=>s.selectedPlace);const propertyId=id==='home'?'house-yaba':id==='lekki-home'?'house-lekki':id;
  const parcel=parcels.find(p=>p.id===propertyId),owned=(g.properties??[starterProperty()]).find(p=>p.id===propertyId);
  const action=useGame(s=>s.propertyAction),open=useGame(s=>s.open);
  const close=()=>open(null);
  const menu=modal==='property'||modal==='home'||modal==='furnish';
  return <><div className="living-tools"><button onClick={()=>{setStats(!stats);document.querySelector('.left-hud')?.classList.toggle('show-stats',!stats);}} aria-pressed={stats}>Stats</button><button onClick={()=>open('property-list')}>Properties</button><Music/><button aria-label="Zoom in" onClick={()=>cameraControl.distance=Math.max(9,cameraControl.distance-5)}>＋</button><button aria-label="Zoom out" onClick={()=>cameraControl.distance=Math.min(65,cameraControl.distance+5)}>−</button></div>
    {g.interior&&<div className="home-hud panel"><strong>{parcels.find(p=>p.id===g.interior)?.name}</strong><div>{(['sit','sleep','tv','stand'] as const).map(a=><button key={a} onClick={()=>useGame.getState().homeAction(a)}>{a==='tv'?(g.tv?'TV off':'Watch TV'):a}</button>)}<button onClick={()=>{useGame.setState({selectedPlace:g.interior!});open('furnish');}}>Furnish</button><button onClick={()=>action(g.interior!,'exit')}>Exit home</button></div><small>Tap furniture to use it. Drag to look around · pinch to zoom.</small></div>}
    {g.captivity&&<div className="ransom-hud"><strong>Kidnapped · {g.captivity.remaining*3}s remaining</strong><button onClick={()=>open('captivity')}>Ransom / rescue</button></div>}
    {!g.lives&&<div className="cooldown-hud"><strong>Take a one-hour break</strong><span>{Math.ceil(Math.max(0,(g.breakUntil??now+3600000)-now)/60000)} minutes until a fresh start</span><button disabled={(g.breakUntil??Infinity)>now} onClick={()=>useGame.getState().reset()}>Start afresh</button></div>}
    {(menu||modal==='property-list'||modal==='captivity')&&<div className="modal-shade" onClick={close}><div ref={dialog} tabIndex={-1} onKeyDown={e=>{if(e.key!=='Tab')return;const list=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===dialog.current)){e.preventDefault();first.focus();}}} className="dialog property-dialog" role="dialog" aria-modal="true" aria-label="Property and home" onClick={e=>e.stopPropagation()}><div className="dialog-top"><span className="eyebrow">YOUR LIFE IN LAGOS</span><button onClick={close} aria-label="Close">✕</button></div>
      {modal==='captivity'?<><h2>The depot was a trap.</h2><p>The kidnappers demand ₦3,000. You have {g.captivity?.remaining??0} turns left. If no ransom or rescue arrives, you lose a life. The timer pauses when you pause the game or leave this tab.</p><button className="choice" onClick={()=>useGame.getState().story('ransom')}>Pay ₦3,000 ransom</button><button className="choice" onClick={()=>useGame.getState().story('rescue')}>Call Sade and the police · Trust −20</button></>:modal==='property-list'?<><h2>Make a place your own.</h2><p>Walk to the marked entrance to enter a house. Land can become a house, club, church or shop.</p>{parcels.map(p=><button className="choice" key={p.id} onClick={()=>{useGame.setState({selectedPlace:p.id});open('property');}}><span><strong>{p.name}</strong><small>{(g.properties??[starterProperty()]).some(a=>a.id===p.id)?'Owned':`₦${p.price.toLocaleString()}`} · Entrance {entrance(p).join(', ')}</small></span></button>)}</>:<><h2>{parcel?.name??'Your home'}</h2><p>Cash ₦{g.money.toLocaleString()} · {owned?`${owned.kind} · Level ${owned.level}`:'For sale'}</p>{!owned&&parcel&&<button className="primary" onClick={()=>action(propertyId,'buy')}>Buy {parcel.built?'house':'land'} · ₦{parcel.price.toLocaleString()}</button>}{owned?.kind==='land'&&Object.entries(buildTypes).map(([kind,b])=><button className="choice" key={kind} onClick={()=>action(propertyId,kind as BuildKind)}>Build {b.name} · ₦{b.price.toLocaleString()}</button>)}{owned?.kind==='house'&&<><button className="primary" onClick={()=>action(propertyId,'enter')}>Enter home</button><button className="choice" onClick={()=>{useGame.setState({selectedPlace:propertyId});open('enterprise');}}>Grid builder / hidden storage</button><h3>Furniture · installed in your rooms</h3>{Object.entries(furnishings).map(([kind,f])=><button className="choice" key={kind} disabled={owned.furniture.includes(kind as Furniture)} onClick={()=>action(propertyId,kind as Furniture)}>{f.name} · {owned.furniture.includes(kind as Furniture)?'Installed':`₦${f.price.toLocaleString()}`}</button>)}</>}{owned&&owned.kind!=='land'&&<button className="choice" disabled={owned.level>=12} onClick={()=>action(propertyId,'upgrade')}>Expand property · ₦5,000 · 12 housing tiers</button>}<PropertyExtras id={propertyId}/><small>Your property, furniture and upgrades save on this device.</small></>}
    </div></div>}</>;
}
