import {controls,useGame,locations} from './game';
import {findRoute,type Point} from '../shared/navigation';
import {worldFree,roomFree} from './spatial';
import {effectiveProperty} from './simulation';
import {dynamicBodies} from './crowd';
import {trafficClock} from './trafficState';
import {vehicleSize} from '../shared/city';
export function stopNavigation(){controls.route=[];controls.destination=null;controls.arrive=null;controls.moving=false;}
export function navigateTo(target:Point,onArrival:(()=>void)|null=null){const s=useGame.getState();if(!s.game.created||!s.game.lives||s.paused||s.modal||s.ride||s.driving||s.game.captivity)return false;const home=s.game.interior?effectiveProperty(s.game,s.game.interior):undefined,base=home?roomFree(home):worldFree(s.game),bodies=dynamicBodies(),cars=trafficClock.cars;
 const free=home?base:(x:number,z:number)=>base(x,z)&&bodies.every(b=>Math.hypot(x-b.x,z-b.z)>b.radius+.33)&&cars.every(t=>Math.abs(x-t.x)>vehicleSize(t.kind)[0]+.35||Math.abs(z-t.z)>vehicleSize(t.kind)[1]+.8);
 const origin:Point=home?[...controls.indoor]:[...controls.position],destination:Point=home?[target[0]-s.game.position[0],target[1]-s.game.position[1]]:[...target];const path=findRoute(origin,destination,free);if(!path){s.notify('That point is blocked. Choose an open floor or street.');return false;}controls.route=home?path.map(p=>[p[0]+s.game.position[0],p[1]+s.game.position[1]]):path;controls.destination=[...target];controls.routeSpace=s.game.interior??'world';controls.arrive=onArrival;return true;}
export function approachPlace(id:string){const place=locations.find(l=>l.id===id);if(!place)return false;const s=useGame.getState();if(s.game.interior)return s.notify('Exit this building to visit another location.');const open=()=>{const state=useGame.getState();state.open(null);useGame.setState({selectedPlace:id});state.open(place.type==='terminal'?'transport':place.type==='property'?'property':place.type==='hawker'||place.type==='shop'?'equipment':place.type==='delivery'?(state.game.stage==='delivery'?'delivery':'locked'):place.type);};if(Math.hypot(controls.position[0]-place.x,controls.position[1]-place.z)<=2.8){open();return true;}const free=worldFree(s.game),points=Array.from({length:12},(_,i)=>[place.x+Math.cos(i*Math.PI/6)*1.65,place.z+Math.sin(i*Math.PI/6)*1.65] as Point).filter(p=>free(...p)).sort((a,b)=>Math.hypot(a[0]-controls.position[0],a[1]-controls.position[1])-Math.hypot(b[0]-controls.position[0],b[1]-controls.position[1]));for(const p of points)if(navigateTo(p,open))return true;s.notify('No clear route. Move toward the entrance from the street.');return false;}
