import {create} from 'zustand';
import {Room,makePlayer,type Player} from '../server/room';
import {controls,useGame,fresh} from './game';
import {trafficAt} from '../shared/city';
export type PublicPlayer=Omit<Player,'lastMove'|'lastAttack'|'lastRob'|'lastWork'|'protectedUntil'>;
type Snapshot={type:'world';time:number;players:PublicPlayer[];chat:Room['chat'];acks:Record<string,number>};
export const usePeers=create<{mode:'off'|'host'|'guest';id:string;status:string;offer:string;answer:string;players:PublicPlayer[];chat:Room['chat'];time:number}>(()=>({mode:'off',id:'',status:'Not connected',offer:'',answer:'',players:[],chat:[],time:0}));
let room:Room|null=null,interval:ReturnType<typeof setInterval>|undefined,guest:RTCDataChannel|null=null;
const connections=new Map<string,{pc:RTCPeerConnection;channel:RTCDataChannel|null}>();
let received=false;
let pending:string|null=null,applying=false,revision=0,awaiting=0;const revisions=new Map<string,number>();
const economy=(g:ReturnType<typeof useGame.getState>['game'])=>({money:g.money,lives:g.lives,health:g.stats.health,inventory:g.inventory,ammo:g.ammo??0,guards:g.guards??0,wanted:g.wanted??0,breakUntil:g.breakUntil??0});
function acceptEconomy(id:string,value:unknown){if(!room||!value||typeof value!=='object')return;const v=value as ReturnType<typeof economy>;if(![v.money,v.lives,v.health,v.ammo,v.guards,v.wanted,v.breakUntil].every(Number.isFinite)||v.money<0||v.money>1e10||!Number.isInteger(v.lives)||v.lives<0||v.lives>9||v.health<0||v.health>100||!Array.isArray(v.inventory)||v.inventory.length>200||!v.inventory.every(x=>typeof x==='string'&&x.length<80)||v.ammo<0||v.ammo>10000||v.guards<0||v.guards>3||v.wanted<0||v.wanted>5)return;Object.assign(room.player(id),v);}
// Local simulation is trusted in private friends sessions. Shared combat is processed by the host.
useGame.subscribe((next,prev)=>{if(applying||usePeers.getState().mode==='off'||next.game===prev.game)return;const value=economy(next.game);if(JSON.stringify(value)===JSON.stringify(economy(prev.game)))return;if(room){acceptEconomy(usePeers.getState().id,value);}else if(guest?.readyState==='open'){awaiting=++revision;guest.send(JSON.stringify({type:'profile',value,revision}));}});
const encode=(s:RTCSessionDescriptionInit)=>btoa(JSON.stringify(s));
const decode=(code:string,type:'offer'|'answer')=>{if(code.length>100000)throw Error('Pairing code is too long.');const data=JSON.parse(atob(code.trim())) as RTCSessionDescriptionInit;if(data.type!==type||typeof data.sdp!=='string'||data.sdp.length>75000)throw Error('Invalid pairing code.');return data;};
const rtc=()=>new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});
function ice(pc:RTCPeerConnection){return new Promise<void>((resolve,reject)=>{if(pc.iceGatheringState==='complete')return resolve();const timer=setTimeout(()=>{pc.removeEventListener('icegatheringstatechange',changed);if(pc.localDescription)resolve();else reject(Error('Could not prepare the connection.'));},10000);function changed(){if(pc.iceGatheringState==='complete'){clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',changed);resolve();}}pc.addEventListener('icegatheringstatechange',changed);});}
function profile(id:string){const g=useGame.getState().game,p=makePlayer(id,g.character?.name??'Guest');p.x=g.position[0];p.z=g.position[1];p.gender=g.character?.gender??'male';p.shirt=g.character?.shirt??p.shirt;p.skin=g.character?.skin??p.skin;p.money=g.money;p.lives=g.lives;p.health=g.stats.health;p.inventory=[...g.inventory];p.ammo=g.ammo??0;p.guards=g.guards??0;p.wanted=g.wanted??0;p.breakUntil=g.breakUntil??0;return p;}
function publish(){if(!room)return;const snapshot:Snapshot={type:'world',time:Date.now(),players:room.publicPlayers(),chat:room.chat,acks:Object.fromEntries(revisions)};apply(snapshot);const text=JSON.stringify(snapshot);for(const {channel} of connections.values())if(channel?.readyState==='open'&&channel.bufferedAmount<65536)channel.send(text);}
function apply(snapshot:Snapshot){if(!Array.isArray(snapshot.players)||snapshot.players.length>8)return;usePeers.setState({players:snapshot.players,chat:snapshot.chat.slice(-50),time:snapshot.time});const p=snapshot.players.find(p=>p.id===usePeers.getState().id);if(!p||((snapshot.acks?.[p.id]??0)<awaiting))return;awaiting=0;const first=!received;received=true;const old=useGame.getState().game,restarted=old.lives===0&&p.lives>0,g=restarted?{...fresh(),created:true,character:old.character}:old;const died=p.lives<old.lives;applying=true;useGame.setState({game:{...g,money:p.money,lives:p.lives,stats:{...g.stats,health:p.health},inventory:p.inventory,ammo:p.ammo,guards:p.guards,wanted:p.wanted,breakUntil:p.breakUntil||undefined,...((died||first||restarted)?{position:[p.x,p.z] as [number,number],deathCause:'Shared-city combat or traffic',interior:undefined}:{})},...(died?{modal:'death',driving:null}:restarted?{modal:null,driving:null}:{}),saved:false});applying=false;}
function startLoop(){if(interval)clearInterval(interval);interval=setInterval(()=>{const s=useGame.getState();if(!s.ready)return;const msg={type:'move',x:controls.position[0],z:controls.position[1],driving:s.driving??s.ride?.kind??null,passenger:!!s.ride};if(room){room.move(usePeers.getState().id,msg.x,msg.z,msg.driving,Date.now(),msg.passenger);room.tick();publish();}else if(guest?.readyState==='open'&&guest.bufferedAmount<65536)guest.send(JSON.stringify(msg));},100);}
export function peerAction(message:Record<string,unknown>){try{if(room){const result=room.action(usePeers.getState().id,message);if(result)useGame.getState().notify(String(result));publish();}else if(guest?.readyState==='open')guest.send(JSON.stringify(message));else useGame.getState().notify('Connect to a friend first.');}catch(e){useGame.getState().notify((e as Error).message);}}
export function disconnectPeers(){if(interval)clearInterval(interval);interval=undefined;for(const c of connections.values())c.pc.close();connections.clear();guest?.close();guest=null;room=null;pending=null;received=false;revision=0;awaiting=0;revisions.clear();usePeers.setState({mode:'off',id:'',status:'Not connected',offer:'',answer:'',players:[],chat:[],time:0});}
export async function hostInvite(){
 if(usePeers.getState().mode==='guest')disconnectPeers();
 if(!room){room=new Room();const id=crypto.randomUUID();room.players.set(id,profile(id));usePeers.setState({mode:'host',id,status:'Hosting · share the invitation'});startLoop();}
 if(room.players.size>=8)throw Error('This room is full (eight players).');
 if(pending){connections.get(pending)?.pc.close();connections.delete(pending);}
 const id=crypto.randomUUID(),pc=rtc(),channel=pc.createDataChannel('9lives',{ordered:true});pending=id;connections.set(id,{pc,channel});
 let joined=false,lastWindow=0,count=0;
 channel.onopen=()=>{usePeers.setState({status:'Direct connection established'});};
 channel.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>8192)return;const now=Date.now();if(now-lastWindow>1000){lastWindow=now;count=0;}if(++count>40)return;const m=JSON.parse(e.data);if(m.type==='hello'&&!joined){const p=makePlayer(id,typeof m.name==='string'?m.name.slice(0,24):'Guest');room?.players.set(id,p);acceptEconomy(id,m.profile);if(m.character&&['male','female'].includes(m.character.gender)&&[m.character.skin,m.character.shirt].every(v=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v))){p.gender=m.character.gender;p.skin=m.character.skin;p.shirt=m.character.shirt;}if(Array.isArray(m.position)&&m.position.length===2&&m.position.every(Number.isFinite)){p.x=m.position[0];p.z=m.position[1];}joined=true;channel.send(JSON.stringify({type:'welcome',id}));publish();return;}if(!joined||!room)return;if(m.type==='profile'){acceptEconomy(id,m.value);if(Number.isInteger(m.revision))revisions.set(id,m.revision);publish();}else if(m.type==='move')room.move(id,m.x,m.z,m.driving,Date.now(),m.passenger===true);else {const result=room.action(id,m);channel.send(JSON.stringify({type:'result',result}));publish();}}catch(e){channel.send(JSON.stringify({type:'error',error:(e as Error).message}));}};
 channel.onclose=()=>{room?.players.delete(id);connections.delete(id);publish();};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed')usePeers.setState({status:'Connection failed. Try another network; restrictive NAT may require a TURN relay.'});};
 await pc.setLocalDescription(await pc.createOffer());await ice(pc);usePeers.setState({offer:encode(pc.localDescription!.toJSON()),answer:''});
}
export async function joinInvite(code:string){disconnectPeers();const pc=rtc();connections.set('host',{pc,channel:null});usePeers.setState({mode:'guest',status:'Preparing reply code'});pc.ondatachannel=e=>{guest=e.channel;connections.get('host')!.channel=guest;guest.onopen=()=>{guest!.send(JSON.stringify({type:'hello',name:useGame.getState().game.character?.name??'Guest',profile:economy(useGame.getState().game),character:useGame.getState().game.character,position:controls.position}));usePeers.setState({status:'Connected directly to host'});startLoop();};guest.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>100000)return;const m=JSON.parse(e.data);if(m.type==='welcome')usePeers.setState({id:m.id});if(m.type==='world')apply(m);if(m.type==='error')useGame.getState().notify(m.error);if(m.type==='result'&&m.result)useGame.getState().notify(String(m.result));}catch{/* Ignore malformed network data. */}};guest.onclose=()=>{usePeers.setState({mode:'off',id:'',status:'Host disconnected. Re-pair to continue.',players:[],chat:[]});if(interval)clearInterval(interval);};};await pc.setRemoteDescription(decode(code,'offer'));await pc.setLocalDescription(await pc.createAnswer());await ice(pc);usePeers.setState({answer:encode(pc.localDescription!.toJSON()),status:'Send this reply code to the host'});}
export async function acceptReply(code:string){if(!pending)throw Error('Create an invitation first.');const pc=connections.get(pending)?.pc;if(!pc)throw Error('Invitation expired. Create a new one.');await pc.setRemoteDescription(decode(code,'answer'));pending=null;usePeers.setState({status:'Connecting directly…',offer:''});}
export const peerTraffic=()=>trafficAt(usePeers.getState().time/1000);
