import {useEffect,useState} from 'react';
import {create} from 'zustand';
import {get,set} from 'idb-keyval';
type Track={id:string;title:string;artist:string;url?:string};
const defaults:Track[]=[{id:'carefree',title:'Carefree',artist:'Kevin MacLeod',url:'/assets/music/carefree.mp3'},{id:'beauty-flow',title:'Beauty Flow',artist:'Kevin MacLeod',url:'/assets/music/beauty-flow.mp3'}];
export const useMusic=create<{tracks:Track[];selected:string;playing:boolean;volume:number;error:string}>(()=>({tracks:defaults,selected:defaults[0].id,playing:false,volume:.35,error:''}));
let audio:HTMLAudioElement|null=null,objectUrl:string|null=null,loading=0;
function element(){if(!audio){audio=new Audio();audio.preload='none';audio.loop=true;audio.addEventListener('error',()=>{useMusic.setState({playing:false,error:'This recording could not be loaded. Choose another track.'});});}return audio;}
async function source(id:string){const sequence=++loading,t=useMusic.getState().tracks.find(t=>t.id===id);if(!t)return;const a=element();a.pause();if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}if(t.url)a.src=t.url;else {const blob=await get<Blob>('9lives-song-'+id);if(sequence!==loading)return;if(!blob)throw Error('This saved audio file is unavailable.');objectUrl=URL.createObjectURL(blob);a.src=objectUrl;}a.volume=useMusic.getState().volume;useMusic.setState({selected:id,playing:false,error:''});}
export async function playMusic(){try{const a=element();if(!a.src)await source(useMusic.getState().selected);await a.play();useMusic.setState({playing:true,error:''});}catch{useMusic.setState({playing:false,error:'Tap Play again to allow audio on this browser.'});}}
function pauseMusic(){audio?.pause();useMusic.setState({playing:false});}
export function Music(){const s=useMusic();useEffect(()=>{void get<Track[]>('9lives-playlist').then(tracks=>{if(Array.isArray(tracks))useMusic.setState({tracks:[...defaults,...tracks.filter(t=>typeof t.id==='string'&&typeof t.title==='string'&&!t.url).slice(0,20)]});}).catch(()=>{});const visibility=()=>{if(document.hidden)pauseMusic();};document.addEventListener('visibilitychange',visibility);return()=>{document.removeEventListener('visibilitychange',visibility);audio?.pause();};},[]);return <button aria-pressed={s.playing} title={s.tracks.find(t=>t.id===s.selected)?.title} onClick={()=>s.playing?pauseMusic():void playMusic()}>{s.playing?'♫ Music on':'♫ Music off'}</button>;}
export function ClubPlayer(){const s=useMusic(),[busy,setBusy]=useState(false);return <div className="music-player"><p>Real recorded music in your club, home or vehicle. The included recording is licensed for use with credit.</p><label>Track<select value={s.selected} onChange={e=>void source(e.target.value).catch(error=>useMusic.setState({error:String(error)}))}>{s.tracks.map(t=><option key={t.id} value={t.id}>{t.title} — {t.artist}</option>)}</select></label><div className="task-buttons"><button onClick={()=>void playMusic()}>Play recording</button><button onClick={pauseMusic}>Pause</button></div><label>Volume<input type="range" min="0" max="1" step=".05" value={s.volume} onChange={e=>{const volume=Number(e.target.value);useMusic.setState({volume});if(audio)audio.volume=volume;}}/></label><label>Add your songs · MP3, OGG, WAV<input disabled={busy} type="file" accept="audio/*" multiple onChange={async e=>{const files=Array.from(e.target.files??[]);setBusy(true);try{for(const file of files.slice(0,Math.max(0,20-useMusic.getState().tracks.filter(t=>!t.url).length))){if(!file.type.startsWith('audio/')||file.size>30000000)continue;const id=crypto.randomUUID(),track={id,title:file.name.replace(/\.[^.]+$/,''),artist:'Your library'};await set('9lives-song-'+id,file);useMusic.setState(state=>({tracks:[...state.tracks,track]}));}await set('9lives-playlist',useMusic.getState().tracks.filter(t=>!t.url));}catch{useMusic.setState({error:'Browser storage is full or unavailable.'});}finally{setBusy(false);}}}/></label><small>Your imported songs stay on this device. Add recordings you have permission to use. Files are loaded only when selected.</small><small>“Beauty Flow” and “Carefree” — Kevin MacLeod (<a href="https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1900008" target="_blank" rel="noreferrer">incompetech.com</a>). Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Recording unmodified.</small>{s.error&&<p role="alert">{s.error}</p>}</div>;}
