import {plotObstacles} from './enterprise';
import {findRoute} from '../shared/navigation';
import {canMove,publicVehicles,vehicleSize,type VehicleKind,type Obstacle} from '../shared/city';
import {parcels,starterProperty,type Property,type Furniture} from '../shared/property';
import type {Save} from './game';
export const furnitureDefaults:Record<Furniture,{x:number;z:number;w:number;d:number}>={fridge:{x:-3,z:1.4,w:.8,d:.8},wardrobe:{x:3,z:0,w:1,d:1},computer:{x:0,z:-3,w:1.6,d:1},chair:{x:1.4,z:1,w:.6,d:.6},lamp:{x:3,z:2,w:.3,d:.3},fan:{x:-3,z:2,w:.4,d:.4},ac:{x:0,z:-3.8,w:1,d:.3},shelf:{x:3,z:1.5,w:1,d:.4},sofa:{x:-2,z:0,w:2.4,d:1},bed:{x:2,z:-2,w:2.1,d:3},tv:{x:-2,z:2.7,w:2.6,d:.6},table:{x:1,z:2,w:1.6,d:1.4},kitchen:{x:-3,z:-3,w:2.8,d:1.1},plant:{x:3,z:3,w:.6,d:.6}};
export function propertyBounds(g:Save,driving:VehicleKind|null=null):Obstacle[]{const properties=g.properties??[starterProperty()];return [...publicVehicles.filter(v=>!g.enterprise?.stolen.includes(v.id)).map(v=>({x:v.x,z:v.z,w:vehicleSize(v.kind)[0]*2,d:vehicleSize(v.kind)[1]*2})),...plotObstacles(g),...Object.entries(g.sim?.garage??{}).filter(([k])=>k!==driving).map(([k,v])=>({x:v!.parked[0],z:v!.parked[1],w:vehicleSize(k as VehicleKind)[0]*2,d:vehicleSize(k as VehicleKind)[1]*2})),...parcels.filter(p=>p.id!=='house-yaba'&&(p.built||properties.some(a=>a.id===p.id&&a.kind!=='land'))).map(p=>({x:p.x,z:p.z,w:6.4,d:6.4}))];}
export const worldFree=(g:Save,driving:VehicleKind|null=null)=>{const bounds=propertyBounds(g,driving);return (x:number,z:number)=>canMove(x,z)&&!bounds.some(b=>Math.abs(x-b.x)<b.w/2+.35&&Math.abs(z-b.z)<b.d/2+.35);};
export function roomBounds(home:Property):Obstacle[]{const edge=(7+home.level)/2-1;return [...home.furniture.map(f=>{const base=furnitureDefaults[f],t=home.placements?.[f],r=t?.rotation??0,offset=f==='kitchen'?-edge:f==='plant'?edge:null;return {x:t?.x??offset??base.x,z:t?.z??offset??base.z,w:Math.abs(Math.cos(r))*base.w+Math.abs(Math.sin(r))*base.d,d:Math.abs(Math.sin(r))*base.w+Math.abs(Math.cos(r))*base.d};}),...(home.walls??[]).map(w=>({x:w.x,z:w.z,w:w.axis==='x'?w.length:.12,d:w.axis==='z'?w.length:.12}))];}
export function roomFree(home:Property){const size=7+home.level,obstacles=roomBounds(home);return (x:number,z:number)=>Math.abs(x)<size/2-.35&&Math.abs(z)<size/2-.35&&!obstacles.some(b=>Math.abs(x-b.x)<b.w/2+.25&&Math.abs(z-b.z)<b.d/2+.25);}
export function validRoomLayout(home:Property,player:[number,number]=[0,0]){const free=roomFree(home),door:[number,number]=[0,(7+home.level)/2-.6];return free(...player)&&!!findRoute(player,door,free,1000);}
export function safeExterior(g:Save):[number,number]{const free=worldFree(g);if(free(...g.position))return [...g.position];const points=parcels.map(p=>[p.id==='house-yaba'?-6:p.x,p.id==='house-yaba'?-3:p.z+(p.size??6)/2+1.5] as [number,number]).sort((a,b)=>Math.hypot(a[0]-g.position[0],a[1]-g.position[1])-Math.hypot(b[0]-g.position[0],b[1]-g.position[1]));return points.find(p=>free(...p))??[0,6];}
