import { memo, useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { blockers, canMove, controls, locations, useGame } from './game';
import { districts, trafficAt, vehicles, type VehicleKind, type DistrictId, canDrive, sweptDrive, vehicleSize, overlapsVehicle } from '../shared/city';

import {Asset} from './GameModels';
import {RemotePlayers} from './RemotePlayers';
import {usePeers,peerTraffic} from './peer';
import {Bodyguards} from './Bodyguards';
import {Crowds} from './Crowds';
import {Atmosphere} from './Atmosphere';
import {Box,Sign,Person} from './SceneParts';
function Architecture({x,z,w,depth,h,label,style,color}:{x:number;z:number;w:number;depth:number;h:number;label:string;style:number;color:string}) {
  const asset=style===3?'city-building-skyscraper-'+['a','b','c'][Math.abs(Math.round(x))%3]:style===1||style===5?'home-building-type-'+['a','b','c','d','e','f','g','h'][Math.abs(Math.round(x+z))%8]:'city-building-'+['a','b','c','d','e','f','g','h'][Math.abs(Math.round(x+z))%8];
  return <group><Asset url={'/assets/models/'+asset+'.glb'} size={[w,h,depth]} position={[x,0,z]} fallback={<Box p={[x,h/2,z]} s={[w,h,depth]} color={color}/>}/><Sign text={label} position={[x,2.4,z+depth/2+.15]} width={w*.85}/></group>;
}
function Tree({ x, z, scale = 1 }: { x: number; z: number; scale?: number }) {
  return <group position={[x, 0, z]} scale={scale}><mesh position={[0, 1.5, 0]} castShadow><cylinderGeometry args={[.13, .24, 3, 7]} /><meshStandardMaterial color="#64533a" /></mesh>{[[0, 3.7, 0], [.7, 3.25, .3], [-.7, 3.3, -.3]].map((p, i) => <mesh key={i} position={p as [number, number, number]} castShadow><icosahedronGeometry args={[1.45, 1]} /><meshStandardMaterial color={['#536e47', '#607c4d', '#748451'][i]} roughness={1} /></mesh>)}<Box p={[0, .12, 0]} s={[1.4, .25, 1.4]} color="#8b8d74" /></group>;
}
function Bus({ x, z, rotation = 0 }: { x: number; z: number; rotation?: number }) {
  return <group position={[x, 0, z]} rotation={[0, rotation, 0]}><Box p={[0, .9, 0]} s={[1.8, 1.35, 3.8]} color="#dbb844" /><Box p={[0, 1.6, -.05]} s={[1.78, .6, 3.2]} color="#d1b459" /><Box p={[0, 1.55, 1.59]} s={[1.5, .56, .05]} color="#354842" /><Box p={[0, 1.02, 1.93]} s={[1.82, .12, .03]} color="#332f25" />{[-.92, .92].flatMap(xx => [-1, 0, 1].map(zz => <Box key={`${xx}-${zz}`} p={[xx, 1.55, zz]} s={[.03, .5, .8]} color="#41534c" />))}{[-.92, .92].flatMap(xx => [-1.2, 1.2].map(zz => <mesh key={`${xx}-${zz}`} position={[xx, .4, zz]} rotation={[0, 0, Math.PI / 2]}><cylinderGeometry args={[.4, .4, .23, 12]} /><meshStandardMaterial color="#272e29" /></mesh>))}{[-.63, .63].map(xx => <Box key={xx} p={[xx, .85, 1.96]} s={[.33, .24, .06]} color="#f5e2a5" />)}<Sign text="LAGOS • YABA" position={[0, 1.95, 1.6]} width={1.5} /></group>;
}
function Wheel({x,z,r=.36}:{x:number;z:number;r?:number}){return <mesh position={[x,r,z]} rotation={[0,0,Math.PI/2]} castShadow><cylinderGeometry args={[r,r,.17,12]}/><meshStandardMaterial color="#24312c"/></mesh>;}
export function Vehicle({kind,color='#b9c6b3'}:{kind:VehicleKind;color?:string}){if(kind==='bus')return <Bus x={0} z={0}/>;if(kind==='car')return <group><Box p={[0,.66,0]} s={[1.7,.6,3.4]} color={color}/><Box p={[0,1.12,-.18]} s={[1.45,.62,1.75]} color={color}/><Box p={[0,1.24,.7]} s={[1.35,.45,.04]} color="#355450"/><Box p={[0,1.24,-1.07]} s={[1.35,.4,.04]} color="#355450"/>{[-.74,.74].map(x=><Box key={x} p={[x,1.2,-.2]} s={[.04,.43,1.35]} color="#3e5a52"/>)}{[-.87,.87].flatMap(x=>[-1.07,1.07].map(z=><Wheel key={`${x}-${z}`} x={x} z={z}/>))}{[-.55,.55].map(x=><group key={x}><Box p={[x,.74,1.72]} s={[.38,.18,.05]} color="#f8e9b6"/><Box p={[x,.74,-1.72]} s={[.38,.18,.05]} color="#a95446"/></group>)}<Box p={[0,.4,1.75]} s={[1.6,.12,.07]} color="#737f73"/></group>;if(kind==='bike')return <group><Wheel x={0} z={-.85} r={.42}/><Wheel x={0} z={.85} r={.42}/><Box p={[0,.6,0]} s={[.22,.3,1.3]} color="#3e5547"/><Box p={[0,.97,-.22]} s={[.45,.15,.75]} color="#29372d"/><Box p={[0,.87,.3]} s={[.4,.3,.5]} color="#be8061"/><Box p={[0,1.3,.7]} s={[.9,.07,.08]} color="#bdc7b3"/><Box p={[0,.96,.87]} s={[.12,.8,.12]} color="#6c806c"/><group position={[0,.63,-.2]} scale={.8}><Person color="#788ba7" npc/></group></group>;return <group><Box p={[0,.65,-.25]} s={[1.4,.7,1.65]} color="#d5b548"/><Box p={[0,1.65,-.18]} s={[1.5,.14,1.8]} color="#3e5541"/>{[-.66,.66].map(x=><Box key={x} p={[x,1.22,-.2]} s={[.07,.8,1.4]} color="#5b704f"/>)}<Box p={[0,1.25,.66]} s={[1.3,.62,.04]} color="#4c6658"/><Wheel x={0} z={1.1}/><Wheel x={-.73} z={-.65}/><Wheel x={.73} z={-.65}/><Box p={[0,.65,1.07]} s={[.35,.5,.45]} color="#d5b548"/></group>;}
import { CameraGestures, cameraControl } from './camera';
import {Interior,PropertyWorld,propertyObstacles} from './Housing';
function PassengerCabin({kind}:{kind:VehicleKind}) { const bus=kind==='bus';return <group><Box p={[0,.45,0]} s={[bus?1.8:1.7,.16,bus?3.8:3.4]} color="#494c40"/><Box p={[0,.6,bus?1.65:1.15]} s={[1.6,.35,.35]} color="#3c4943"/>{(bus?[-1.2,-.4,.5]:[-.55,.5]).flatMap(z=>[-.45,.45].map(x=><group key={x+'-'+z}><Box p={[x,.65,z]} s={[.65,.18,.65]} color="#936d4e"/><Box p={[x,.95,z-.3]} s={[.65,.6,.12]} color="#936d4e"/></group>))}{[-.84,.84].map(x=><group key={x}><Box p={[x,.8,0]} s={[.08,.65,bus?3.8:2.4]} color="#b7b58b"/>{[-1.5,0,1.5].map(z=><Box key={z} p={[x,1.4,z]} s={[.07,1,.07]} color="#b7b58b"/>)}<Box p={[x,1.9,0]} s={[.07,.08,bus?3.8:3]} color="#b7b58b"/></group>)}<group position={[-.45,.45,bus?1.2:.7]} rotation={[0,Math.PI,0]} scale={.65}><Person npc color="#627b93"/></group><mesh position={[-.45,.94,bus?1.65:1.15]} rotation={[.7,0,0]}><torusGeometry args={[.16,.025,6,12]}/><meshStandardMaterial color="#1c2926"/></mesh><Sign text={bus?'DANFO · LAGOS RADIO':'9LIVES CITY CAB'} position={[0,1.75,bus?1.83:1.5]} width={1.5}/></group>; }
function Player() {
  const group = useRef<THREE.Group>(null!); const body = useRef<THREE.Group>(null!); const last = useRef(0); const aim = useMemo(() => new THREE.Vector3(), []); const cam = useMemo(() => new THREE.Vector3(), []);const velocity=useRef(0);const angle=useRef(Math.PI);const elapsed=useRef(0);
  const interior=useGame(s=>s.game.interior),passenger=useGame(s=>s.passengerView);const driving=useGame(s=>s.driving),rideKind=useGame(s=>s.ride?.kind),character=useGame(s=>s.game.character);
  useEffect(()=>{if(driving)angle.current=Math.PI;},[driving]);
  useEffect(()=>{const ride=useGame.getState().ride;elapsed.current=ride?ride.progress*ride.duration:0;},[rideKind]);
  const position = useGame(s => s.game.position);
  useEffect(() => { controls.position = [...position]; if (group.current) group.current.position.set(position[0], 0, position[1]); }, [position]);
  useFrame(({ camera, clock }, dt) => {
    const state = useGame.getState(); if (!state.ready) return;
    const keys = controls.keys;
    if(state.game.interior)return;const active = !state.game.captivity && !state.paused && !state.modal && state.game.created && state.game.lives > 0 && !document.hidden;
    let sx = active ? controls.x + (keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0) : 0;
    let sz = active ? controls.z + (keys.has('s') || keys.has('arrowdown') ? 1 : 0) - (keys.has('w') || keys.has('arrowup') ? 1 : 0) : 0;
    const length = Math.hypot(sx, sz); if (length > 1) { sx /= length; sz /= length; }
    const running = (controls.running || keys.has('shift')) && state.game.stats.energy > 10;
    const frame=Math.min(dt,.05),brake=keys.has(' ');if(state.driving&&active){const target=-sz*vehicles[state.driving].speed*(running?1.35:.7);velocity.current+=(target-velocity.current)*(1-Math.exp(-frame*(brake?12:sz?2.2:3)));if(brake)velocity.current*=Math.exp(-frame*10);}else velocity.current=0;
    const speed=(running?5:2.7)*frame;
    const obstacles=propertyObstacles();if(state.driving&&active){const next=angle.current-sx*Math.min(dt,.05)*1.9;if(canDrive(controls.position[0],controls.position[1],next,state.driving,[...obstacles,...trafficClock.cars.map(t=>({x:t.x,z:t.z,w:vehicleSize(t.kind)[0]*2,d:vehicleSize(t.kind)[1]*2}))]))angle.current=next;}
    const dx = state.driving?Math.sin(angle.current)*velocity.current*frame:(sx*Math.cos(cameraControl.yaw)+sz*Math.sin(cameraControl.yaw))*speed, dz = state.driving?Math.cos(angle.current)*velocity.current*frame:(sz*Math.cos(cameraControl.yaw)-sx*Math.sin(cameraControl.yaw))*speed;
    const p = controls.position;
    if(state.ride){if(active)elapsed.current+=Math.min(dt,1);const ride=state.ride,progress=Math.min(1,elapsed.current/ride.duration);const lengths=ride.route.slice(1).map((v,i)=>Math.hypot(v[0]-ride.route[i][0],v[1]-ride.route[i][1]));let distance=lengths.reduce((a,b)=>a+b,0)*progress;let i=0;while(i<lengths.length-1&&distance>lengths[i]){distance-=lengths[i];i++;}const ratio=lengths[i]?distance/lengths[i]:1;const a=ride.route[i],b=ride.route[i+1];p[0]=a[0]+(b[0]-a[0])*ratio;p[1]=a[1]+(b[1]-a[1])*ratio;angle.current=Math.atan2(b[0]-a[0],b[1]-a[1]);if(clock.elapsedTime-last.current>.2){useGame.setState({ride:{...ride,progress}});last.current=clock.elapsedTime;}if(progress>=1)state.arrive();}
    else if(state.driving){const traffic=trafficClock.cars.map(t=>{const size=vehicleSize(t.kind);return{x:t.x,z:t.z,w:size[0]*2,d:size[1]*2};});if(sweptDrive(p,[p[0]+dx,p[1]+dz],angle.current,state.driving,[...obstacles,...traffic])){p[0]+=dx;p[1]+=dz;}}else{const free=(x:number,z:number)=>canMove(x,z)&&!obstacles.some(b=>Math.abs(x-b.x)<b.w/2+.35&&Math.abs(z-b.z)<b.d/2+.35);if(free(p[0]+dx,p[1]))p[0]+=dx;if(free(p[0],p[1]+dz))p[1]+=dz;}
    trafficClock.playerAngle=angle.current;group.current.position.set(p[0], 0, p[1]);
    if (state.driving||state.ride)body.current.rotation.y=angle.current;else if (length > .05) body.current.rotation.y = Math.atan2(dx, dz);
    body.current.position.y = !state.driving&&!state.ride&&length > .05 ? Math.abs(Math.sin(clock.elapsedTime * (running ? 13 : 9))) * .07 : 0;
    if (clock.elapsedTime - last.current > .4 && active && length > .05&&!state.ride) { state.update(g => ({ ...g, position: [...p] })); last.current = clock.elapsedTime; }
    aim.set(p[0],state.driving||state.ride?1.2:0,p[1]);
    if(state.ride&&state.passengerView&&(state.ride.kind==='car'||state.ride.kind==='bus')){const a=angle.current,rear=state.ride.kind==='bus'?1.4:.75;cam.set(p[0]-Math.sin(a)*rear,1.5,p[1]-Math.cos(a)*rear);aim.set(cam.x+Math.sin(a+cameraControl.insideYaw)*5,cam.y-cameraControl.insidePitch*3,cam.z+Math.cos(a+cameraControl.insideYaw)*5);const lens=camera as THREE.PerspectiveCamera;const fov=Math.max(35,Math.min(85,cameraControl.distance*1.7));if(lens.fov!==fov){lens.fov=fov;lens.updateProjectionMatrix();}camera.position.copy(cam);camera.lookAt(aim);return;}const lens=camera as THREE.PerspectiveCamera;if(lens.fov!==43){lens.fov=43;lens.updateProjectionMatrix();}if(state.driving||state.ride){const yaw=angle.current+cameraControl.yaw-.665,radius=Math.max(4,Math.min(13,cameraControl.distance*.22));cam.set(p[0]-Math.sin(yaw)*radius,1.5+Math.sin(cameraControl.pitch)*radius,p[1]-Math.cos(yaw)*radius);aim.x+=Math.sin(angle.current)*4;aim.z+=Math.cos(angle.current)*4;}else cam.set(aim.x+Math.sin(cameraControl.yaw)*Math.cos(cameraControl.pitch)*cameraControl.distance,Math.sin(cameraControl.pitch)*cameraControl.distance,aim.z+Math.cos(cameraControl.yaw)*Math.cos(cameraControl.pitch)*cameraControl.distance);
    camera.position.lerp(cam, 1 - Math.exp(-dt * 3)); camera.lookAt(aim);
  });
  return <group ref={group} visible={!interior}><group ref={body}>{rideKind&&passenger&&(rideKind==='bus'||rideKind==='car')?<PassengerCabin kind={rideKind}/>:driving||rideKind?<Vehicle kind={driving??rideKind!} color={character?.shirt}/>:<Person character={character} walking/>}</group><mesh position={[0, .04, 0]} rotation={[-Math.PI / 2, 0, 0]}><ringGeometry args={[.42, .5, 32]} /><meshBasicMaterial color="#f2d391" transparent opacity={.85} /></mesh></group>;
}
const District = memo(function District({id}:{id:DistrictId}) {
  const d=districts.find(d=>d.id===id)!;const names:Record<DistrictId,string[]>={yaba:['ADE RESIDENCES','AMARA’S PROVISIONS','FEMI AUTO WORKS','OLUWASEUN HOUSE','IBILE STORES','YABA COMMUNITY'],ikorodu:['RIVER VIEW HOUSE','IKORODU MARKET','GENERAL HOSPITAL','SADE RESIDENCES','RIVERFRONT DEPOT','IKORODU TRADERS'],ikeja:['POLICE STATION','COMPUTER VILLAGE','EFCC FIELD OFFICE','DISPATCH OFFICE','IKEJA STORES','STATE ARCHIVES'],vi:['ISLAND CLINIC','ISLAND PROVISIONS','ISLAND LOGISTICS','EKO RESIDENCES','ATLANTIC HOUSE','VI BUSINESS HUB'],mainland:['COMMUNITY CENTER','NEIGHBORHOOD STORES','MAINLAND MOTORS','REPAIR YARD','MAINLAND TRADERS','COMMUNITY HOMES'],lekki:['GUEST HOUSE','WATERFRONT MARKET','LEKKI SECURITY','PALM ESTATE','LEKKI STORES','WATERFRONT HOMES']};
  const buildings = names[id].map((label,i)=>({label,color:i%2?d.color:'#a7ad91',h:(id==='vi'?9:id==='ikorodu'?4.5:6)+i%3}));
  return <group position={[d.x,0,d.z]}>{[-6, 6].map(x => <Box key={x} p={[x, .12, -4]} s={[1.2, .25, 28]} color="#a29d85" />)}{blockers.filter(b=>b.district===id).map((b,i)=><Architecture key={i} x={b.x-d.x} z={b.z-d.z} w={b.w} depth={b.d} h={b.h} label={i<6?buildings[i].label:b.label} style={b.style} color={i%2?d.color:'#acb799'}/>)}
    <group position={[-8,0,20]}><Vehicle kind="bus"/></group><group position={[8,0,20]}><Vehicle kind="car" color="#769baf"/></group><Sign text={`${d.name.toUpperCase()} MOTOR PARK`} position={[-4,2.5,14]} width={4}/>
    {[[-5, -9], [5.5, 8], [-13, 0], [13, -10], [-11, 11], [10, 12], [-14, -15], [15, 3]].map(([x, z], i) => <Tree key={i} x={x} z={z} scale={i % 2 ? 1.1 : .9} />)}
    {[-5.4, 5.4].flatMap(x => [-10, 1, 10].map(z => <group key={`${x}-${z}`}><Box p={[x, 2.4, z]} s={[.1, 4.8, .1]} color="#465349" /><Box p={[x + (x > 0 ? -.5 : .5), 4.7, z]} s={[1, .1, .12]} color="#465349" /><Box p={[x + (x > 0 ? -1 : 1), 4.65, z]} s={[.5, .13, .3]} color="#e8d6a2" /></group>))}
    {locations.filter(l => l.district===id&&['tunde', 'shop', 'work','story','police','efcc','security'].includes(l.type)).map((l, i) => <group key={l.id} position={[l.x-d.x, 0, l.z-d.z]} rotation={[0, -.6, 0]}><Person color={['#738f79', '#b97950', '#9aa8aa'][i%3]} npc /></group>)}
    <group position={[-5.8, 0, 8]}><Box p={[0, .4, 0]} s={[.8, .8, .8]} color="#9c8861" /><Box p={[.8, .3, .1]} s={[.55, .6, .6]} color="#b5996a" /></group>
    <group position={[5, 0, -1]}><Box p={[0, .6, 0]} s={[.7, 1.2, .7]} color="#5b7761" /><Box p={[0, 1.22, 0]} s={[.8, .08, .8]} color="#364d3e" /></group>
    <Sign text={['YABA · BUILD YOUR FUTURE','IKORODU · FRESH FROM THE FARM','IKEJA · HONEST WORK PAYS','VI · LIVE ABOVE THE ORDINARY','MAINLAND MOTORS · TEST YOUR NEXT RIDE','LEKKI · A PLACE TO CALL HOME'][districts.indexOf(d)]} position={[15,6,17]} width={9}/><Box p={[15,3,17]} s={[.2,6,.2]} color="#3c4d3e"/>
    {locations.filter(l=>l.district===id&&l.type==='terminal').map(l=><mesh key={l.id} position={[l.x-d.x,.09,l.z-d.z]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.2,1.6,40]}/><meshBasicMaterial color="#efd28a" transparent opacity={.7}/></mesh>)}
    {Array.from({length:id==='ikorodu'?10:id==='ikeja'?6:3},(_,i)=><group key={'stall'+i} position={[-17-(i%3)*3,0,2-Math.floor(i/3)*3]}><Box p={[0,.65,0]} s={[1.8,1.3,1.4]} color={['#bca66f','#d69c68','#889d75'][i%3]}/><Box p={[0,2.1,0]} s={[2.2,.12,1.8]} color={['#c56844','#649886','#d6b55c'][i%3]}/><Sign text={id==='ikeja'?'PHONES':id==='ikorodu'?'PRODUCE':'GOODS'} position={[0,1.7,.9]} width={1.8}/></group>)}
    <group position={[4,0,8]}><Person color="#be895f" npc/><Box p={[0,2,0]} s={[1,.2,.65]} color="#b9a978"/>{[-.3,0,.3].map(x=><Box key={x} p={[x,2.2,0]} s={[.15,.3,.15]} color="#a2cbce"/>)}</group>
  </group>;
});
function GarageWorld(){const garage=useGame(s=>s.game.sim?.garage),driving=useGame(s=>s.driving);return <>{Object.entries(garage??{}).filter(([k])=>k!==driving).map(([kind,v])=>v&&<group key={kind} position={[v.parked[0],0,v.parked[1]]} rotation={[0,Math.PI,0]} onClick={()=>useGame.getState().useItem(vehicles[kind as VehicleKind].key)}><Vehicle kind={kind as VehicleKind}/><Sign text="YOUR VEHICLE" position={[0,2,0]} width={2}/></group>)}</>;}
function City(){const nearby=useGame(s=>districts.filter(d=>Math.hypot(d.x-s.game.position[0],d.z-s.game.position[1])<72).map(d=>d.id).join(','));const ride=useGame(s=>s.ride?.destination);const interior=useGame(s=>s.game.interior);if(interior)return <Interior/>;return <><GarageWorld/><PropertyWorld/><Box p={[0,-.35,-50]} s={[280,.6,190]} color="#77836a"/><Box p={[0,-.15,-143]} s={[280,.2,25]} color="#587c79"/>{[-100,0,100].map(x=><group key={x}><Box p={[x,-.02,-48]} s={[12,.15,153]} color="#626e62"/>{Array.from({length:42},(_,i)=><Box key={i} p={[x,.07,-122+i*3.5]} s={[.12,.02,1.5]} color="#b2ac8f"/>)}</group>)}{[-86,14].map(z=><Box key={z} p={[0,-.02,z]} s={[250,.15,7]} color="#626e62"/>)}{districts.filter(d=>nearby.split(',').includes(d.id)||d.id===ride).map(d=><District key={d.id} id={d.id}/>)}</>;}
export const trafficClock={time:0,cars:trafficAt(0),playerAngle:Math.PI};
function Traffic(){const groups=useRef<(THREE.Group|null)[]>([]);const time=useRef(0);const phases=useRef(Array(18).fill(0) as number[]);const immunity=useRef(0);useFrame((_,dt)=>{const s=useGame.getState();if(usePeers.getState().mode!=='off'){trafficClock.cars=peerTraffic();trafficClock.cars.forEach((t,i)=>{const g=groups.current[i];if(g){g.position.set(t.x,0,t.z);g.rotation.y=t.angle;g.visible=!s.game.interior;}});return;}if(s.game.interior){groups.current.forEach(g=>{if(g)g.visible=false;});return;}if(s.paused||s.modal||!s.game.created||document.hidden)return;time.current+=Math.min(dt,.05);trafficClock.time=time.current;trafficAt(time.current).forEach((_,i)=>{let t=trafficAt(phases.current[i]+Math.min(dt,.05))[i];const size=vehicleSize(s.driving??s.ride?.kind??'car');const a=groups.current;const blocked=propertyObstacles().some(o=>overlapsVehicle(t.x,t.z,t.angle,t.kind,o))||(!!s.driving||!!s.ride)&&overlapsVehicle(t.x,t.z,t.angle,t.kind,{x:controls.position[0],z:controls.position[1],w:(Math.abs(Math.cos(trafficClock.playerAngle))*size[0]+Math.abs(Math.sin(trafficClock.playerAngle))*size[1])*2+.5,d:(Math.abs(Math.sin(trafficClock.playerAngle))*size[0]+Math.abs(Math.cos(trafficClock.playerAngle))*size[1])*2+.5}) || a.some((g,j)=>j!==i&&g&&Math.abs(g.position.x-t.x)<.1&&((g.position.z-t.z)*t.direction>0)&&Math.abs(g.position.z-t.z)<6);if(!blocked)phases.current[i]+=Math.min(dt,.05);t=trafficAt(phases.current[i])[i];trafficClock.cars[i]=t;const group=groups.current[i];if(!group)return;group.position.set(t.x,0,t.z);group.rotation.y=t.angle;group.visible=Math.hypot(t.x-controls.position[0],t.z-controls.position[1])<65;if(!s.ride&&s.game.lives>0&&time.current>immunity.current&&Math.abs(t.x-controls.position[0])<(t.kind==='bike'?.65:1.25)&&Math.abs(t.z-controls.position[1])<(t.kind==='bus'?2.5:1.8)){immunity.current=time.current+8;s.damage(s.driving?45:100,s.driving?'Vehicle collision':'Traffic collision');}});});return <>{Array.from({length:18},(_,i)=><group key={i} ref={el=>{groups.current[i]=el;}}><Vehicle kind={(['car','bus','bike','keke'] as VehicleKind[])[i%4]} color={['#b6c2b0','#bd916e','#718e97'][i%3]}/></group>)}</>;}
function Markers() {
  const projected = useMemo(() => new THREE.Vector3(), []);
  const nodes = useRef<(HTMLElement | null)[]>([]);
  useEffect(() => { nodes.current = [...locations.map(l => document.getElementById(`marker-${l.id}`)), document.getElementById('marker-player')]; return () => nodes.current.forEach(el => { if (el) el.style.opacity = '0'; }); }, []);
  useFrame(({ camera, size }) => {
    nodes.current.forEach((el, i) => { if (!el) return; const l = locations[i]; projected.set(l ? l.x : controls.position[0], l?.type === 'home' ? 3 : 2.7, l ? l.z : controls.position[1]).project(camera); const x = (projected.x + 1) * size.width / 2, y = (1 - projected.y) * size.height / 2; const visible = !useGame.getState().game.interior&&(!l||Math.hypot(l.x-controls.position[0],l.z-controls.position[1])<38)&&projected.z > -1 && projected.z < 1 && x > -80 && x < size.width + 80 && y > 0 && y < size.height; el.style.opacity = visible ? '1' : '0'; el.style.pointerEvents = visible ? 'auto' : 'none'; el.style.transform = `translate(${x}px,${y}px) translate(-50%,-50%)`; });
  });
  return null;
}
function Patrols() {
  const refs=useRef<(THREE.Group|null)[]>([]),last=useRef(0);
  useFrame(({clock},dt)=>{const s=useGame.getState();districts.forEach((d,i)=>{const group=refs.current[i];if(!group)return;group.visible=!s.game.interior&&Math.hypot(d.x-controls.position[0],d.z-controls.position[1])<60;if(!group.visible||s.paused||s.modal||s.ride||!s.game.created||!s.game.lives)return;const wanted=(s.game.wanted??0)>0,local=Math.hypot(d.x-controls.position[0],d.z-controls.position[1])<40;
    const tx=wanted&&local?controls.position[0]:d.x+4.3,tz=wanted&&local?controls.position[1]:d.z+Math.sin(clock.elapsedTime*.15+i)*9;
    const dx=tx-group.position.x,dz=tz-group.position.z,r=Math.hypot(dx,dz),step=Math.min(r,dt*(wanted?3.5:1.2));if(r>.1){const x=group.position.x+dx/r*step,z=group.position.z+dz/r*step;if(canMove(x,z)){group.position.x=x;group.position.z=z;}group.rotation.y=Math.atan2(dx,dz);}if(wanted&&local&&r<1.4&&clock.elapsedTime-last.current>5){last.current=clock.elapsedTime;s.arrest();}
  });});return <>{districts.map((d,i)=><group key={d.id} position={[d.x+4.3,0,d.z]} ref={e=>{refs.current[i]=e;}}><Person color={d.id==='ikeja'?'#5b7858':'#394c67'} npc/><Sign text={d.id==='ikeja'?'EFCC':'POLICE'} position={[0,2.2,0]} width={1.4}/></group>)}</>;
}
export default function World() {
  const quality = useGame(s => s.quality);
  return <Canvas onCreated={()=>window.dispatchEvent(new Event('9lives-world-ready'))} shadows={quality === 'high'} dpr={quality === 'high' ? [1, 1.5] : 1} camera={{ position: [18, 22, 24], fov: 43, near: .1, far: 280 }} gl={{ antialias: quality === 'high', powerPreference: 'high-performance' }}><color attach="background" args={['#adb49a']} /><fog attach="fog" args={['#adb49a', 38, 125]} /><ambientLight intensity={1.2} color="#e5e3ce" /><hemisphereLight args={['#e8ead3', '#536246', 1.3]} /><Atmosphere/><CameraGestures/><City /><RemotePlayers/><Crowds/><Bodyguards/><Player /><Traffic/><Patrols/><Markers /></Canvas>;
}
